// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteImeKeyInjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteImeKeyInject)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
   * @return Whether the appInfo field is set.
   */
  boolean hasAppInfo();
  /**
   * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
   * @return The appInfo.
   */
  com.sprit.tvremote.proto.remote.RemoteAppInfo getAppInfo();

  /**
   * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
   * @return Whether the textFieldStatus field is set.
   */
  boolean hasTextFieldStatus();
  /**
   * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
   * @return The textFieldStatus.
   */
  com.sprit.tvremote.proto.remote.RemoteTextFieldStatus getTextFieldStatus();
}
