// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf enum {@code remote.RemoteDirection}
 */
@com.google.protobuf.Generated
public enum RemoteDirection
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>UNKNOWN_DIRECTION = 0;</code>
   */
  UNKNOWN_DIRECTION(0),
  /**
   * <code>START_LONG = 1;</code>
   */
  START_LONG(1),
  /**
   * <code>END_LONG = 2;</code>
   */
  END_LONG(2),
  /**
   * <code>SHORT = 3;</code>
   */
  SHORT(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_DIRECTION = 0;</code>
   */
  public static final int UNKNOWN_DIRECTION_VALUE = 0;
  /**
   * <code>START_LONG = 1;</code>
   */
  public static final int START_LONG_VALUE = 1;
  /**
   * <code>END_LONG = 2;</code>
   */
  public static final int END_LONG_VALUE = 2;
  /**
   * <code>SHORT = 3;</code>
   */
  public static final int SHORT_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RemoteDirection valueOf(int value) {
    return forNumber(value);
  }

  public static RemoteDirection forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_DIRECTION;
      case 1: return START_LONG;
      case 2: return END_LONG;
      case 3: return SHORT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RemoteDirection>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RemoteDirection> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RemoteDirection>() {
          @java.lang.Override
          public RemoteDirection findValueByNumber(int number) {
            return RemoteDirection.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return RemoteDirectionVerifier.INSTANCE;
  }

  private static final class RemoteDirectionVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new RemoteDirectionVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return RemoteDirection.forNumber(number) != null;
          }
        };

  private final int value;

  private RemoteDirection(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:remote.RemoteDirection)
}

