// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteConfigure}
 */
@com.google.protobuf.Generated
public  final class RemoteConfigure extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteConfigure, RemoteConfigure.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteConfigure)
    RemoteConfigureOrBuilder {
  private RemoteConfigure() {
  }
  private int bitField0_;
  public static final int CODE1_FIELD_NUMBER = 1;
  private int code1_;
  /**
   * <code>optional int32 code1 = 1;</code>
   * @return Whether the code1 field is set.
   */
  @java.lang.Override
  public boolean hasCode1() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 code1 = 1;</code>
   * @return The code1.
   */
  @java.lang.Override
  public int getCode1() {
    return code1_;
  }
  /**
   * <code>optional int32 code1 = 1;</code>
   * @param value The code1 to set.
   */
  private void setCode1(int value) {
    bitField0_ |= 0x00000001;
    code1_ = value;
  }
  /**
   * <code>optional int32 code1 = 1;</code>
   */
  private void clearCode1() {
    bitField0_ = (bitField0_ & ~0x00000001);
    code1_ = 0;
  }

  public static final int DEVICE_INFO_FIELD_NUMBER = 2;
  private com.sprit.tvremote.proto.remote.RemoteDeviceInfo deviceInfo_;
  /**
   * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
   */
  @java.lang.Override
  public boolean hasDeviceInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteDeviceInfo getDeviceInfo() {
    return deviceInfo_ == null ? com.sprit.tvremote.proto.remote.RemoteDeviceInfo.getDefaultInstance() : deviceInfo_;
  }
  /**
   * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDeviceInfo(com.sprit.tvremote.proto.remote.RemoteDeviceInfo value) {
    value.getClass();  // minimal bytecode null check
    deviceInfo_ = value;
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeDeviceInfo(com.sprit.tvremote.proto.remote.RemoteDeviceInfo value) {
    value.getClass();  // minimal bytecode null check
    if (deviceInfo_ != null &&
        deviceInfo_ != com.sprit.tvremote.proto.remote.RemoteDeviceInfo.getDefaultInstance()) {
      deviceInfo_ =
        com.sprit.tvremote.proto.remote.RemoteDeviceInfo.newBuilder(deviceInfo_).mergeFrom(value).buildPartial();
    } else {
      deviceInfo_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
   */
  private void clearDeviceInfo() {
    deviceInfo_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteConfigure parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteConfigure prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteConfigure}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteConfigure, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteConfigure)
      com.sprit.tvremote.proto.remote.RemoteConfigureOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteConfigure.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 code1 = 1;</code>
     * @return Whether the code1 field is set.
     */
    @java.lang.Override
    public boolean hasCode1() {
      return instance.hasCode1();
    }
    /**
     * <code>optional int32 code1 = 1;</code>
     * @return The code1.
     */
    @java.lang.Override
    public int getCode1() {
      return instance.getCode1();
    }
    /**
     * <code>optional int32 code1 = 1;</code>
     * @param value The code1 to set.
     * @return This builder for chaining.
     */
    public Builder setCode1(int value) {
      copyOnWrite();
      instance.setCode1(value);
      return this;
    }
    /**
     * <code>optional int32 code1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode1() {
      copyOnWrite();
      instance.clearCode1();
      return this;
    }

    /**
     * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
     */
    @java.lang.Override
    public boolean hasDeviceInfo() {
      return instance.hasDeviceInfo();
    }
    /**
     * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteDeviceInfo getDeviceInfo() {
      return instance.getDeviceInfo();
    }
    /**
     * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
     */
    public Builder setDeviceInfo(com.sprit.tvremote.proto.remote.RemoteDeviceInfo value) {
      copyOnWrite();
      instance.setDeviceInfo(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
     */
    public Builder setDeviceInfo(
        com.sprit.tvremote.proto.remote.RemoteDeviceInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setDeviceInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
     */
    public Builder mergeDeviceInfo(com.sprit.tvremote.proto.remote.RemoteDeviceInfo value) {
      copyOnWrite();
      instance.mergeDeviceInfo(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
     */
    public Builder clearDeviceInfo() {  copyOnWrite();
      instance.clearDeviceInfo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteConfigure)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteConfigure();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "code1_",
            "deviceInfo_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1004\u0000\u0002" +
              "\u1009\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteConfigure> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteConfigure.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteConfigure>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteConfigure)
  private static final com.sprit.tvremote.proto.remote.RemoteConfigure DEFAULT_INSTANCE;
  static {
    RemoteConfigure defaultInstance = new RemoteConfigure();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteConfigure.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteConfigure getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteConfigure> PARSER;

  public static com.google.protobuf.Parser<RemoteConfigure> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

