// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemotePingResponse}
 */
@com.google.protobuf.Generated
public  final class RemotePingResponse extends
    com.google.protobuf.GeneratedMessageLite<
        RemotePingResponse, RemotePingResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemotePingResponse)
    RemotePingResponseOrBuilder {
  private RemotePingResponse() {
  }
  private int bitField0_;
  public static final int VAL1_FIELD_NUMBER = 1;
  private int val1_;
  /**
   * <code>optional int32 val1 = 1;</code>
   * @return Whether the val1 field is set.
   */
  @java.lang.Override
  public boolean hasVal1() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 val1 = 1;</code>
   * @return The val1.
   */
  @java.lang.Override
  public int getVal1() {
    return val1_;
  }
  /**
   * <code>optional int32 val1 = 1;</code>
   * @param value The val1 to set.
   */
  private void setVal1(int value) {
    bitField0_ |= 0x00000001;
    val1_ = value;
  }
  /**
   * <code>optional int32 val1 = 1;</code>
   */
  private void clearVal1() {
    bitField0_ = (bitField0_ & ~0x00000001);
    val1_ = 0;
  }

  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemotePingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemotePingResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemotePingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemotePingResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemotePingResponse)
      com.sprit.tvremote.proto.remote.RemotePingResponseOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemotePingResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 val1 = 1;</code>
     * @return Whether the val1 field is set.
     */
    @java.lang.Override
    public boolean hasVal1() {
      return instance.hasVal1();
    }
    /**
     * <code>optional int32 val1 = 1;</code>
     * @return The val1.
     */
    @java.lang.Override
    public int getVal1() {
      return instance.getVal1();
    }
    /**
     * <code>optional int32 val1 = 1;</code>
     * @param value The val1 to set.
     * @return This builder for chaining.
     */
    public Builder setVal1(int value) {
      copyOnWrite();
      instance.setVal1(value);
      return this;
    }
    /**
     * <code>optional int32 val1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVal1() {
      copyOnWrite();
      instance.clearVal1();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemotePingResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemotePingResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "val1_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1004\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemotePingResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemotePingResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemotePingResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemotePingResponse)
  private static final com.sprit.tvremote.proto.remote.RemotePingResponse DEFAULT_INSTANCE;
  static {
    RemotePingResponse defaultInstance = new RemotePingResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemotePingResponse.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemotePingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemotePingResponse> PARSER;

  public static com.google.protobuf.Parser<RemotePingResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

