// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteSetActiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteSetActive)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 active = 1;</code>
   * @return Whether the active field is set.
   */
  boolean hasActive();
  /**
   * <code>optional int32 active = 1;</code>
   * @return The active.
   */
  int getActive();
}
