// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteVoiceEndOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteVoiceEnd)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 session_id = 1;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>optional int32 session_id = 1;</code>
   * @return The sessionId.
   */
  int getSessionId();
}
