// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteStartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteStart)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bool started = 1;</code>
   * @return Whether the started field is set.
   */
  boolean hasStarted();
  /**
   * <code>optional bool started = 1;</code>
   * @return The started.
   */
  boolean getStarted();
}
