// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
   * @return Whether the remoteConfigure field is set.
   */
  boolean hasRemoteConfigure();
  /**
   * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
   * @return The remoteConfigure.
   */
  com.sprit.tvremote.proto.remote.RemoteConfigure getRemoteConfigure();

  /**
   * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
   * @return Whether the remoteSetActive field is set.
   */
  boolean hasRemoteSetActive();
  /**
   * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
   * @return The remoteSetActive.
   */
  com.sprit.tvremote.proto.remote.RemoteSetActive getRemoteSetActive();

  /**
   * <code>optional .remote.RemoteError remote_error = 3;</code>
   * @return Whether the remoteError field is set.
   */
  boolean hasRemoteError();
  /**
   * <code>optional .remote.RemoteError remote_error = 3;</code>
   * @return The remoteError.
   */
  com.sprit.tvremote.proto.remote.RemoteError getRemoteError();

  /**
   * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
   * @return Whether the remotePingRequest field is set.
   */
  boolean hasRemotePingRequest();
  /**
   * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
   * @return The remotePingRequest.
   */
  com.sprit.tvremote.proto.remote.RemotePingRequest getRemotePingRequest();

  /**
   * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
   * @return Whether the remotePingResponse field is set.
   */
  boolean hasRemotePingResponse();
  /**
   * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
   * @return The remotePingResponse.
   */
  com.sprit.tvremote.proto.remote.RemotePingResponse getRemotePingResponse();

  /**
   * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
   * @return Whether the remoteKeyInject field is set.
   */
  boolean hasRemoteKeyInject();
  /**
   * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
   * @return The remoteKeyInject.
   */
  com.sprit.tvremote.proto.remote.RemoteKeyInject getRemoteKeyInject();

  /**
   * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
   * @return Whether the remoteImeKeyInject field is set.
   */
  boolean hasRemoteImeKeyInject();
  /**
   * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
   * @return The remoteImeKeyInject.
   */
  com.sprit.tvremote.proto.remote.RemoteImeKeyInject getRemoteImeKeyInject();

  /**
   * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
   * @return Whether the remoteImeBatchEdit field is set.
   */
  boolean hasRemoteImeBatchEdit();
  /**
   * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
   * @return The remoteImeBatchEdit.
   */
  com.sprit.tvremote.proto.remote.RemoteImeBatchEdit getRemoteImeBatchEdit();

  /**
   * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
   * @return Whether the remoteImeShowRequest field is set.
   */
  boolean hasRemoteImeShowRequest();
  /**
   * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
   * @return The remoteImeShowRequest.
   */
  com.sprit.tvremote.proto.remote.RemoteImeShowRequest getRemoteImeShowRequest();

  /**
   * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
   * @return Whether the remoteVoiceBegin field is set.
   */
  boolean hasRemoteVoiceBegin();
  /**
   * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
   * @return The remoteVoiceBegin.
   */
  com.sprit.tvremote.proto.remote.RemoteVoiceBegin getRemoteVoiceBegin();

  /**
   * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
   * @return Whether the remoteVoicePayload field is set.
   */
  boolean hasRemoteVoicePayload();
  /**
   * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
   * @return The remoteVoicePayload.
   */
  com.sprit.tvremote.proto.remote.RemoteVoicePayload getRemoteVoicePayload();

  /**
   * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
   * @return Whether the remoteVoiceEnd field is set.
   */
  boolean hasRemoteVoiceEnd();
  /**
   * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
   * @return The remoteVoiceEnd.
   */
  com.sprit.tvremote.proto.remote.RemoteVoiceEnd getRemoteVoiceEnd();

  /**
   * <code>optional .remote.RemoteStart remote_start = 40;</code>
   * @return Whether the remoteStart field is set.
   */
  boolean hasRemoteStart();
  /**
   * <code>optional .remote.RemoteStart remote_start = 40;</code>
   * @return The remoteStart.
   */
  com.sprit.tvremote.proto.remote.RemoteStart getRemoteStart();

  /**
   * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
   * @return Whether the remoteSetVolumeLevel field is set.
   */
  boolean hasRemoteSetVolumeLevel();
  /**
   * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
   * @return The remoteSetVolumeLevel.
   */
  com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel getRemoteSetVolumeLevel();

  /**
   * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
   * @return Whether the remoteAdjustVolumeLevel field is set.
   */
  boolean hasRemoteAdjustVolumeLevel();
  /**
   * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
   * @return The remoteAdjustVolumeLevel.
   */
  com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel getRemoteAdjustVolumeLevel();

  /**
   * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
   * @return Whether the remoteSetPreferredAudioDevice field is set.
   */
  boolean hasRemoteSetPreferredAudioDevice();
  /**
   * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
   * @return The remoteSetPreferredAudioDevice.
   */
  com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice getRemoteSetPreferredAudioDevice();

  /**
   * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
   * @return Whether the remoteResetPreferredAudioDevice field is set.
   */
  boolean hasRemoteResetPreferredAudioDevice();
  /**
   * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
   * @return The remoteResetPreferredAudioDevice.
   */
  com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice getRemoteResetPreferredAudioDevice();

  /**
   * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
   * @return Whether the remoteAppLinkLaunchRequest field is set.
   */
  boolean hasRemoteAppLinkLaunchRequest();
  /**
   * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
   * @return The remoteAppLinkLaunchRequest.
   */
  com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest getRemoteAppLinkLaunchRequest();
}
