// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteKeyInjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteKeyInject)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .remote.RemoteKeyCode key_code = 1;</code>
   * @return Whether the keyCode field is set.
   */
  boolean hasKeyCode();
  /**
   * <code>optional .remote.RemoteKeyCode key_code = 1;</code>
   * @return The enum numeric value on the wire for keyCode.
   */
  int getKeyCodeValue();
  /**
   * <code>optional .remote.RemoteKeyCode key_code = 1;</code>
   * @return The keyCode.
   */
  com.sprit.tvremote.proto.remote.RemoteKeyCode getKeyCode();

  /**
   * <code>optional .remote.RemoteDirection direction = 2;</code>
   * @return Whether the direction field is set.
   */
  boolean hasDirection();
  /**
   * <code>optional .remote.RemoteDirection direction = 2;</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>optional .remote.RemoteDirection direction = 2;</code>
   * @return The direction.
   */
  com.sprit.tvremote.proto.remote.RemoteDirection getDirection();
}
