// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteImeShowRequest}
 */
@com.google.protobuf.Generated
public  final class RemoteImeShowRequest extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteImeShowRequest, RemoteImeShowRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteImeShowRequest)
    RemoteImeShowRequestOrBuilder {
  private RemoteImeShowRequest() {
  }
  private int bitField0_;
  public static final int REMOTE_TEXT_FIELD_STATUS_FIELD_NUMBER = 2;
  private com.sprit.tvremote.proto.remote.RemoteTextFieldStatus remoteTextFieldStatus_;
  /**
   * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
   */
  @java.lang.Override
  public boolean hasRemoteTextFieldStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteTextFieldStatus getRemoteTextFieldStatus() {
    return remoteTextFieldStatus_ == null ? com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.getDefaultInstance() : remoteTextFieldStatus_;
  }
  /**
   * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteTextFieldStatus(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus value) {
    value.getClass();  // minimal bytecode null check
    remoteTextFieldStatus_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteTextFieldStatus(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus value) {
    value.getClass();  // minimal bytecode null check
    if (remoteTextFieldStatus_ != null &&
        remoteTextFieldStatus_ != com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.getDefaultInstance()) {
      remoteTextFieldStatus_ =
        com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.newBuilder(remoteTextFieldStatus_).mergeFrom(value).buildPartial();
    } else {
      remoteTextFieldStatus_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
   */
  private void clearRemoteTextFieldStatus() {
    remoteTextFieldStatus_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteImeShowRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteImeShowRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteImeShowRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteImeShowRequest)
      com.sprit.tvremote.proto.remote.RemoteImeShowRequestOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteImeShowRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
     */
    @java.lang.Override
    public boolean hasRemoteTextFieldStatus() {
      return instance.hasRemoteTextFieldStatus();
    }
    /**
     * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteTextFieldStatus getRemoteTextFieldStatus() {
      return instance.getRemoteTextFieldStatus();
    }
    /**
     * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
     */
    public Builder setRemoteTextFieldStatus(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus value) {
      copyOnWrite();
      instance.setRemoteTextFieldStatus(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
     */
    public Builder setRemoteTextFieldStatus(
        com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteTextFieldStatus(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
     */
    public Builder mergeRemoteTextFieldStatus(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus value) {
      copyOnWrite();
      instance.mergeRemoteTextFieldStatus(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
     */
    public Builder clearRemoteTextFieldStatus() {  copyOnWrite();
      instance.clearRemoteTextFieldStatus();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteImeShowRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteImeShowRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "remoteTextFieldStatus_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0002\u0002\u0001\u0000\u0000\u0000\u0002\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteImeShowRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteImeShowRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteImeShowRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteImeShowRequest)
  private static final com.sprit.tvremote.proto.remote.RemoteImeShowRequest DEFAULT_INSTANCE;
  static {
    RemoteImeShowRequest defaultInstance = new RemoteImeShowRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteImeShowRequest.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeShowRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteImeShowRequest> PARSER;

  public static com.google.protobuf.Parser<RemoteImeShowRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

