// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteImeKeyInject}
 */
@com.google.protobuf.Generated
public  final class RemoteImeKeyInject extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteImeKeyInject, RemoteImeKeyInject.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteImeKeyInject)
    RemoteImeKeyInjectOrBuilder {
  private RemoteImeKeyInject() {
  }
  private int bitField0_;
  public static final int APP_INFO_FIELD_NUMBER = 1;
  private com.sprit.tvremote.proto.remote.RemoteAppInfo appInfo_;
  /**
   * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
   */
  @java.lang.Override
  public boolean hasAppInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteAppInfo getAppInfo() {
    return appInfo_ == null ? com.sprit.tvremote.proto.remote.RemoteAppInfo.getDefaultInstance() : appInfo_;
  }
  /**
   * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAppInfo(com.sprit.tvremote.proto.remote.RemoteAppInfo value) {
    value.getClass();  // minimal bytecode null check
    appInfo_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeAppInfo(com.sprit.tvremote.proto.remote.RemoteAppInfo value) {
    value.getClass();  // minimal bytecode null check
    if (appInfo_ != null &&
        appInfo_ != com.sprit.tvremote.proto.remote.RemoteAppInfo.getDefaultInstance()) {
      appInfo_ =
        com.sprit.tvremote.proto.remote.RemoteAppInfo.newBuilder(appInfo_).mergeFrom(value).buildPartial();
    } else {
      appInfo_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
   */
  private void clearAppInfo() {
    appInfo_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int TEXT_FIELD_STATUS_FIELD_NUMBER = 2;
  private com.sprit.tvremote.proto.remote.RemoteTextFieldStatus textFieldStatus_;
  /**
   * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
   */
  @java.lang.Override
  public boolean hasTextFieldStatus() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteTextFieldStatus getTextFieldStatus() {
    return textFieldStatus_ == null ? com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.getDefaultInstance() : textFieldStatus_;
  }
  /**
   * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTextFieldStatus(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus value) {
    value.getClass();  // minimal bytecode null check
    textFieldStatus_ = value;
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeTextFieldStatus(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus value) {
    value.getClass();  // minimal bytecode null check
    if (textFieldStatus_ != null &&
        textFieldStatus_ != com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.getDefaultInstance()) {
      textFieldStatus_ =
        com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.newBuilder(textFieldStatus_).mergeFrom(value).buildPartial();
    } else {
      textFieldStatus_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
   */
  private void clearTextFieldStatus() {
    textFieldStatus_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteImeKeyInject prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteImeKeyInject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteImeKeyInject, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteImeKeyInject)
      com.sprit.tvremote.proto.remote.RemoteImeKeyInjectOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteImeKeyInject.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
     */
    @java.lang.Override
    public boolean hasAppInfo() {
      return instance.hasAppInfo();
    }
    /**
     * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteAppInfo getAppInfo() {
      return instance.getAppInfo();
    }
    /**
     * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
     */
    public Builder setAppInfo(com.sprit.tvremote.proto.remote.RemoteAppInfo value) {
      copyOnWrite();
      instance.setAppInfo(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
     */
    public Builder setAppInfo(
        com.sprit.tvremote.proto.remote.RemoteAppInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setAppInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
     */
    public Builder mergeAppInfo(com.sprit.tvremote.proto.remote.RemoteAppInfo value) {
      copyOnWrite();
      instance.mergeAppInfo(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteAppInfo app_info = 1;</code>
     */
    public Builder clearAppInfo() {  copyOnWrite();
      instance.clearAppInfo();
      return this;
    }

    /**
     * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
     */
    @java.lang.Override
    public boolean hasTextFieldStatus() {
      return instance.hasTextFieldStatus();
    }
    /**
     * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteTextFieldStatus getTextFieldStatus() {
      return instance.getTextFieldStatus();
    }
    /**
     * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
     */
    public Builder setTextFieldStatus(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus value) {
      copyOnWrite();
      instance.setTextFieldStatus(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
     */
    public Builder setTextFieldStatus(
        com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.Builder builderForValue) {
      copyOnWrite();
      instance.setTextFieldStatus(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
     */
    public Builder mergeTextFieldStatus(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus value) {
      copyOnWrite();
      instance.mergeTextFieldStatus(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteTextFieldStatus text_field_status = 2;</code>
     */
    public Builder clearTextFieldStatus() {  copyOnWrite();
      instance.clearTextFieldStatus();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteImeKeyInject)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteImeKeyInject();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "appInfo_",
            "textFieldStatus_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "\u1009\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteImeKeyInject> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteImeKeyInject.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteImeKeyInject>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteImeKeyInject)
  private static final com.sprit.tvremote.proto.remote.RemoteImeKeyInject DEFAULT_INSTANCE;
  static {
    RemoteImeKeyInject defaultInstance = new RemoteImeKeyInject();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteImeKeyInject.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeKeyInject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteImeKeyInject> PARSER;

  public static com.google.protobuf.Parser<RemoteImeKeyInject> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

