// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteError)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bool value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional bool value = 1;</code>
   * @return The value.
   */
  boolean getValue();

  /**
   * <code>optional .remote.RemoteMessage message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional .remote.RemoteMessage message = 2;</code>
   * @return The message.
   */
  com.sprit.tvremote.proto.remote.RemoteMessage getMessage();
}
