// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteSetVolumeLevel}
 */
@com.google.protobuf.Generated
public  final class RemoteSetVolumeLevel extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteSetVolumeLevel, RemoteSetVolumeLevel.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteSetVolumeLevel)
    RemoteSetVolumeLevelOrBuilder {
  private RemoteSetVolumeLevel() {
    playerModel_ = "";
  }
  private int bitField0_;
  public static final int UNKNOWN1_FIELD_NUMBER = 1;
  private int unknown1_;
  /**
   * <code>optional uint32 unknown1 = 1;</code>
   * @return Whether the unknown1 field is set.
   */
  @java.lang.Override
  public boolean hasUnknown1() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint32 unknown1 = 1;</code>
   * @return The unknown1.
   */
  @java.lang.Override
  public int getUnknown1() {
    return unknown1_;
  }
  /**
   * <code>optional uint32 unknown1 = 1;</code>
   * @param value The unknown1 to set.
   */
  private void setUnknown1(int value) {
    bitField0_ |= 0x00000001;
    unknown1_ = value;
  }
  /**
   * <code>optional uint32 unknown1 = 1;</code>
   */
  private void clearUnknown1() {
    bitField0_ = (bitField0_ & ~0x00000001);
    unknown1_ = 0;
  }

  public static final int UNKNOWN2_FIELD_NUMBER = 2;
  private int unknown2_;
  /**
   * <code>optional uint32 unknown2 = 2;</code>
   * @return Whether the unknown2 field is set.
   */
  @java.lang.Override
  public boolean hasUnknown2() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional uint32 unknown2 = 2;</code>
   * @return The unknown2.
   */
  @java.lang.Override
  public int getUnknown2() {
    return unknown2_;
  }
  /**
   * <code>optional uint32 unknown2 = 2;</code>
   * @param value The unknown2 to set.
   */
  private void setUnknown2(int value) {
    bitField0_ |= 0x00000002;
    unknown2_ = value;
  }
  /**
   * <code>optional uint32 unknown2 = 2;</code>
   */
  private void clearUnknown2() {
    bitField0_ = (bitField0_ & ~0x00000002);
    unknown2_ = 0;
  }

  public static final int PLAYER_MODEL_FIELD_NUMBER = 3;
  private java.lang.String playerModel_;
  /**
   * <code>optional string player_model = 3;</code>
   * @return Whether the playerModel field is set.
   */
  @java.lang.Override
  public boolean hasPlayerModel() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string player_model = 3;</code>
   * @return The playerModel.
   */
  @java.lang.Override
  public java.lang.String getPlayerModel() {
    return playerModel_;
  }
  /**
   * <code>optional string player_model = 3;</code>
   * @return The bytes for playerModel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayerModelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(playerModel_);
  }
  /**
   * <code>optional string player_model = 3;</code>
   * @param value The playerModel to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPlayerModel(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000004;
    playerModel_ = value;
  }
  /**
   * <code>optional string player_model = 3;</code>
   */
  private void clearPlayerModel() {
    bitField0_ = (bitField0_ & ~0x00000004);
    playerModel_ = getDefaultInstance().getPlayerModel();
  }
  /**
   * <code>optional string player_model = 3;</code>
   * @param value The bytes for playerModel to set.
   */
  private void setPlayerModelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    playerModel_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static final int UNKNOWN4_FIELD_NUMBER = 4;
  private int unknown4_;
  /**
   * <code>optional uint32 unknown4 = 4;</code>
   * @return Whether the unknown4 field is set.
   */
  @java.lang.Override
  public boolean hasUnknown4() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint32 unknown4 = 4;</code>
   * @return The unknown4.
   */
  @java.lang.Override
  public int getUnknown4() {
    return unknown4_;
  }
  /**
   * <code>optional uint32 unknown4 = 4;</code>
   * @param value The unknown4 to set.
   */
  private void setUnknown4(int value) {
    bitField0_ |= 0x00000008;
    unknown4_ = value;
  }
  /**
   * <code>optional uint32 unknown4 = 4;</code>
   */
  private void clearUnknown4() {
    bitField0_ = (bitField0_ & ~0x00000008);
    unknown4_ = 0;
  }

  public static final int UNKNOWN5_FIELD_NUMBER = 5;
  private int unknown5_;
  /**
   * <code>optional uint32 unknown5 = 5;</code>
   * @return Whether the unknown5 field is set.
   */
  @java.lang.Override
  public boolean hasUnknown5() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional uint32 unknown5 = 5;</code>
   * @return The unknown5.
   */
  @java.lang.Override
  public int getUnknown5() {
    return unknown5_;
  }
  /**
   * <code>optional uint32 unknown5 = 5;</code>
   * @param value The unknown5 to set.
   */
  private void setUnknown5(int value) {
    bitField0_ |= 0x00000010;
    unknown5_ = value;
  }
  /**
   * <code>optional uint32 unknown5 = 5;</code>
   */
  private void clearUnknown5() {
    bitField0_ = (bitField0_ & ~0x00000010);
    unknown5_ = 0;
  }

  public static final int VOLUME_MAX_FIELD_NUMBER = 6;
  private int volumeMax_;
  /**
   * <code>optional uint32 volume_max = 6;</code>
   * @return Whether the volumeMax field is set.
   */
  @java.lang.Override
  public boolean hasVolumeMax() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional uint32 volume_max = 6;</code>
   * @return The volumeMax.
   */
  @java.lang.Override
  public int getVolumeMax() {
    return volumeMax_;
  }
  /**
   * <code>optional uint32 volume_max = 6;</code>
   * @param value The volumeMax to set.
   */
  private void setVolumeMax(int value) {
    bitField0_ |= 0x00000020;
    volumeMax_ = value;
  }
  /**
   * <code>optional uint32 volume_max = 6;</code>
   */
  private void clearVolumeMax() {
    bitField0_ = (bitField0_ & ~0x00000020);
    volumeMax_ = 0;
  }

  public static final int VOLUME_LEVEL_FIELD_NUMBER = 7;
  private int volumeLevel_;
  /**
   * <code>optional uint32 volume_level = 7;</code>
   * @return Whether the volumeLevel field is set.
   */
  @java.lang.Override
  public boolean hasVolumeLevel() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional uint32 volume_level = 7;</code>
   * @return The volumeLevel.
   */
  @java.lang.Override
  public int getVolumeLevel() {
    return volumeLevel_;
  }
  /**
   * <code>optional uint32 volume_level = 7;</code>
   * @param value The volumeLevel to set.
   */
  private void setVolumeLevel(int value) {
    bitField0_ |= 0x00000040;
    volumeLevel_ = value;
  }
  /**
   * <code>optional uint32 volume_level = 7;</code>
   */
  private void clearVolumeLevel() {
    bitField0_ = (bitField0_ & ~0x00000040);
    volumeLevel_ = 0;
  }

  public static final int VOLUME_MUTED_FIELD_NUMBER = 8;
  private boolean volumeMuted_;
  /**
   * <code>optional bool volume_muted = 8;</code>
   * @return Whether the volumeMuted field is set.
   */
  @java.lang.Override
  public boolean hasVolumeMuted() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional bool volume_muted = 8;</code>
   * @return The volumeMuted.
   */
  @java.lang.Override
  public boolean getVolumeMuted() {
    return volumeMuted_;
  }
  /**
   * <code>optional bool volume_muted = 8;</code>
   * @param value The volumeMuted to set.
   */
  private void setVolumeMuted(boolean value) {
    bitField0_ |= 0x00000080;
    volumeMuted_ = value;
  }
  /**
   * <code>optional bool volume_muted = 8;</code>
   */
  private void clearVolumeMuted() {
    bitField0_ = (bitField0_ & ~0x00000080);
    volumeMuted_ = false;
  }

  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteSetVolumeLevel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteSetVolumeLevel)
      com.sprit.tvremote.proto.remote.RemoteSetVolumeLevelOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional uint32 unknown1 = 1;</code>
     * @return Whether the unknown1 field is set.
     */
    @java.lang.Override
    public boolean hasUnknown1() {
      return instance.hasUnknown1();
    }
    /**
     * <code>optional uint32 unknown1 = 1;</code>
     * @return The unknown1.
     */
    @java.lang.Override
    public int getUnknown1() {
      return instance.getUnknown1();
    }
    /**
     * <code>optional uint32 unknown1 = 1;</code>
     * @param value The unknown1 to set.
     * @return This builder for chaining.
     */
    public Builder setUnknown1(int value) {
      copyOnWrite();
      instance.setUnknown1(value);
      return this;
    }
    /**
     * <code>optional uint32 unknown1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnknown1() {
      copyOnWrite();
      instance.clearUnknown1();
      return this;
    }

    /**
     * <code>optional uint32 unknown2 = 2;</code>
     * @return Whether the unknown2 field is set.
     */
    @java.lang.Override
    public boolean hasUnknown2() {
      return instance.hasUnknown2();
    }
    /**
     * <code>optional uint32 unknown2 = 2;</code>
     * @return The unknown2.
     */
    @java.lang.Override
    public int getUnknown2() {
      return instance.getUnknown2();
    }
    /**
     * <code>optional uint32 unknown2 = 2;</code>
     * @param value The unknown2 to set.
     * @return This builder for chaining.
     */
    public Builder setUnknown2(int value) {
      copyOnWrite();
      instance.setUnknown2(value);
      return this;
    }
    /**
     * <code>optional uint32 unknown2 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnknown2() {
      copyOnWrite();
      instance.clearUnknown2();
      return this;
    }

    /**
     * <code>optional string player_model = 3;</code>
     * @return Whether the playerModel field is set.
     */
    @java.lang.Override
    public boolean hasPlayerModel() {
      return instance.hasPlayerModel();
    }
    /**
     * <code>optional string player_model = 3;</code>
     * @return The playerModel.
     */
    @java.lang.Override
    public java.lang.String getPlayerModel() {
      return instance.getPlayerModel();
    }
    /**
     * <code>optional string player_model = 3;</code>
     * @return The bytes for playerModel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerModelBytes() {
      return instance.getPlayerModelBytes();
    }
    /**
     * <code>optional string player_model = 3;</code>
     * @param value The playerModel to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerModel(
        java.lang.String value) {
      copyOnWrite();
      instance.setPlayerModel(value);
      return this;
    }
    /**
     * <code>optional string player_model = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerModel() {
      copyOnWrite();
      instance.clearPlayerModel();
      return this;
    }
    /**
     * <code>optional string player_model = 3;</code>
     * @param value The bytes for playerModel to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerModelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPlayerModelBytes(value);
      return this;
    }

    /**
     * <code>optional uint32 unknown4 = 4;</code>
     * @return Whether the unknown4 field is set.
     */
    @java.lang.Override
    public boolean hasUnknown4() {
      return instance.hasUnknown4();
    }
    /**
     * <code>optional uint32 unknown4 = 4;</code>
     * @return The unknown4.
     */
    @java.lang.Override
    public int getUnknown4() {
      return instance.getUnknown4();
    }
    /**
     * <code>optional uint32 unknown4 = 4;</code>
     * @param value The unknown4 to set.
     * @return This builder for chaining.
     */
    public Builder setUnknown4(int value) {
      copyOnWrite();
      instance.setUnknown4(value);
      return this;
    }
    /**
     * <code>optional uint32 unknown4 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnknown4() {
      copyOnWrite();
      instance.clearUnknown4();
      return this;
    }

    /**
     * <code>optional uint32 unknown5 = 5;</code>
     * @return Whether the unknown5 field is set.
     */
    @java.lang.Override
    public boolean hasUnknown5() {
      return instance.hasUnknown5();
    }
    /**
     * <code>optional uint32 unknown5 = 5;</code>
     * @return The unknown5.
     */
    @java.lang.Override
    public int getUnknown5() {
      return instance.getUnknown5();
    }
    /**
     * <code>optional uint32 unknown5 = 5;</code>
     * @param value The unknown5 to set.
     * @return This builder for chaining.
     */
    public Builder setUnknown5(int value) {
      copyOnWrite();
      instance.setUnknown5(value);
      return this;
    }
    /**
     * <code>optional uint32 unknown5 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnknown5() {
      copyOnWrite();
      instance.clearUnknown5();
      return this;
    }

    /**
     * <code>optional uint32 volume_max = 6;</code>
     * @return Whether the volumeMax field is set.
     */
    @java.lang.Override
    public boolean hasVolumeMax() {
      return instance.hasVolumeMax();
    }
    /**
     * <code>optional uint32 volume_max = 6;</code>
     * @return The volumeMax.
     */
    @java.lang.Override
    public int getVolumeMax() {
      return instance.getVolumeMax();
    }
    /**
     * <code>optional uint32 volume_max = 6;</code>
     * @param value The volumeMax to set.
     * @return This builder for chaining.
     */
    public Builder setVolumeMax(int value) {
      copyOnWrite();
      instance.setVolumeMax(value);
      return this;
    }
    /**
     * <code>optional uint32 volume_max = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolumeMax() {
      copyOnWrite();
      instance.clearVolumeMax();
      return this;
    }

    /**
     * <code>optional uint32 volume_level = 7;</code>
     * @return Whether the volumeLevel field is set.
     */
    @java.lang.Override
    public boolean hasVolumeLevel() {
      return instance.hasVolumeLevel();
    }
    /**
     * <code>optional uint32 volume_level = 7;</code>
     * @return The volumeLevel.
     */
    @java.lang.Override
    public int getVolumeLevel() {
      return instance.getVolumeLevel();
    }
    /**
     * <code>optional uint32 volume_level = 7;</code>
     * @param value The volumeLevel to set.
     * @return This builder for chaining.
     */
    public Builder setVolumeLevel(int value) {
      copyOnWrite();
      instance.setVolumeLevel(value);
      return this;
    }
    /**
     * <code>optional uint32 volume_level = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolumeLevel() {
      copyOnWrite();
      instance.clearVolumeLevel();
      return this;
    }

    /**
     * <code>optional bool volume_muted = 8;</code>
     * @return Whether the volumeMuted field is set.
     */
    @java.lang.Override
    public boolean hasVolumeMuted() {
      return instance.hasVolumeMuted();
    }
    /**
     * <code>optional bool volume_muted = 8;</code>
     * @return The volumeMuted.
     */
    @java.lang.Override
    public boolean getVolumeMuted() {
      return instance.getVolumeMuted();
    }
    /**
     * <code>optional bool volume_muted = 8;</code>
     * @param value The volumeMuted to set.
     * @return This builder for chaining.
     */
    public Builder setVolumeMuted(boolean value) {
      copyOnWrite();
      instance.setVolumeMuted(value);
      return this;
    }
    /**
     * <code>optional bool volume_muted = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolumeMuted() {
      copyOnWrite();
      instance.clearVolumeMuted();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteSetVolumeLevel)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "unknown1_",
            "unknown2_",
            "playerModel_",
            "unknown4_",
            "unknown5_",
            "volumeMax_",
            "volumeLevel_",
            "volumeMuted_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0001\u0001\b\b\u0000\u0000\u0000\u0001\u100b\u0000\u0002\u100b\u0001" +
              "\u0003\u1208\u0002\u0004\u100b\u0003\u0005\u100b\u0004\u0006\u100b\u0005\u0007\u100b" +
              "\u0006\b\u1007\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteSetVolumeLevel)
  private static final com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel DEFAULT_INSTANCE;
  static {
    RemoteSetVolumeLevel defaultInstance = new RemoteSetVolumeLevel();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteSetVolumeLevel.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteSetVolumeLevel> PARSER;

  public static com.google.protobuf.Parser<RemoteSetVolumeLevel> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

