// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteAppInfo}
 */
@com.google.protobuf.Generated
public  final class RemoteAppInfo extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteAppInfo, RemoteAppInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteAppInfo)
    RemoteAppInfoOrBuilder {
  private RemoteAppInfo() {
    int4_ = "";
    label_ = "";
    appPackage_ = "";
  }
  private int bitField0_;
  public static final int COUNTER_FIELD_NUMBER = 1;
  private int counter_;
  /**
   * <code>optional int32 counter = 1;</code>
   * @return Whether the counter field is set.
   */
  @java.lang.Override
  public boolean hasCounter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 counter = 1;</code>
   * @return The counter.
   */
  @java.lang.Override
  public int getCounter() {
    return counter_;
  }
  /**
   * <code>optional int32 counter = 1;</code>
   * @param value The counter to set.
   */
  private void setCounter(int value) {
    bitField0_ |= 0x00000001;
    counter_ = value;
  }
  /**
   * <code>optional int32 counter = 1;</code>
   */
  private void clearCounter() {
    bitField0_ = (bitField0_ & ~0x00000001);
    counter_ = 0;
  }

  public static final int INT2_FIELD_NUMBER = 2;
  private int int2_;
  /**
   * <code>optional int32 int2 = 2;</code>
   * @return Whether the int2 field is set.
   */
  @java.lang.Override
  public boolean hasInt2() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 int2 = 2;</code>
   * @return The int2.
   */
  @java.lang.Override
  public int getInt2() {
    return int2_;
  }
  /**
   * <code>optional int32 int2 = 2;</code>
   * @param value The int2 to set.
   */
  private void setInt2(int value) {
    bitField0_ |= 0x00000002;
    int2_ = value;
  }
  /**
   * <code>optional int32 int2 = 2;</code>
   */
  private void clearInt2() {
    bitField0_ = (bitField0_ & ~0x00000002);
    int2_ = 0;
  }

  public static final int INT3_FIELD_NUMBER = 3;
  private int int3_;
  /**
   * <code>optional int32 int3 = 3;</code>
   * @return Whether the int3 field is set.
   */
  @java.lang.Override
  public boolean hasInt3() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 int3 = 3;</code>
   * @return The int3.
   */
  @java.lang.Override
  public int getInt3() {
    return int3_;
  }
  /**
   * <code>optional int32 int3 = 3;</code>
   * @param value The int3 to set.
   */
  private void setInt3(int value) {
    bitField0_ |= 0x00000004;
    int3_ = value;
  }
  /**
   * <code>optional int32 int3 = 3;</code>
   */
  private void clearInt3() {
    bitField0_ = (bitField0_ & ~0x00000004);
    int3_ = 0;
  }

  public static final int INT4_FIELD_NUMBER = 4;
  private java.lang.String int4_;
  /**
   * <code>optional string int4 = 4;</code>
   * @return Whether the int4 field is set.
   */
  @java.lang.Override
  public boolean hasInt4() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string int4 = 4;</code>
   * @return The int4.
   */
  @java.lang.Override
  public java.lang.String getInt4() {
    return int4_;
  }
  /**
   * <code>optional string int4 = 4;</code>
   * @return The bytes for int4.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInt4Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(int4_);
  }
  /**
   * <code>optional string int4 = 4;</code>
   * @param value The int4 to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setInt4(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000008;
    int4_ = value;
  }
  /**
   * <code>optional string int4 = 4;</code>
   */
  private void clearInt4() {
    bitField0_ = (bitField0_ & ~0x00000008);
    int4_ = getDefaultInstance().getInt4();
  }
  /**
   * <code>optional string int4 = 4;</code>
   * @param value The bytes for int4 to set.
   */
  private void setInt4Bytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    int4_ = value.toStringUtf8();
    bitField0_ |= 0x00000008;
  }

  public static final int INT7_FIELD_NUMBER = 7;
  private int int7_;
  /**
   * <code>optional int32 int7 = 7;</code>
   * @return Whether the int7 field is set.
   */
  @java.lang.Override
  public boolean hasInt7() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 int7 = 7;</code>
   * @return The int7.
   */
  @java.lang.Override
  public int getInt7() {
    return int7_;
  }
  /**
   * <code>optional int32 int7 = 7;</code>
   * @param value The int7 to set.
   */
  private void setInt7(int value) {
    bitField0_ |= 0x00000010;
    int7_ = value;
  }
  /**
   * <code>optional int32 int7 = 7;</code>
   */
  private void clearInt7() {
    bitField0_ = (bitField0_ & ~0x00000010);
    int7_ = 0;
  }

  public static final int INT8_FIELD_NUMBER = 8;
  private int int8_;
  /**
   * <code>optional int32 int8 = 8;</code>
   * @return Whether the int8 field is set.
   */
  @java.lang.Override
  public boolean hasInt8() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 int8 = 8;</code>
   * @return The int8.
   */
  @java.lang.Override
  public int getInt8() {
    return int8_;
  }
  /**
   * <code>optional int32 int8 = 8;</code>
   * @param value The int8 to set.
   */
  private void setInt8(int value) {
    bitField0_ |= 0x00000020;
    int8_ = value;
  }
  /**
   * <code>optional int32 int8 = 8;</code>
   */
  private void clearInt8() {
    bitField0_ = (bitField0_ & ~0x00000020);
    int8_ = 0;
  }

  public static final int LABEL_FIELD_NUMBER = 10;
  private java.lang.String label_;
  /**
   * <code>optional string label = 10;</code>
   * @return Whether the label field is set.
   */
  @java.lang.Override
  public boolean hasLabel() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string label = 10;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <code>optional string label = 10;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <code>optional string label = 10;</code>
   * @param value The label to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setLabel(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000040;
    label_ = value;
  }
  /**
   * <code>optional string label = 10;</code>
   */
  private void clearLabel() {
    bitField0_ = (bitField0_ & ~0x00000040);
    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <code>optional string label = 10;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    label_ = value.toStringUtf8();
    bitField0_ |= 0x00000040;
  }

  public static final int APP_PACKAGE_FIELD_NUMBER = 12;
  private java.lang.String appPackage_;
  /**
   * <code>optional string app_package = 12;</code>
   * @return Whether the appPackage field is set.
   */
  @java.lang.Override
  public boolean hasAppPackage() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional string app_package = 12;</code>
   * @return The appPackage.
   */
  @java.lang.Override
  public java.lang.String getAppPackage() {
    return appPackage_;
  }
  /**
   * <code>optional string app_package = 12;</code>
   * @return The bytes for appPackage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppPackageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(appPackage_);
  }
  /**
   * <code>optional string app_package = 12;</code>
   * @param value The appPackage to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAppPackage(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000080;
    appPackage_ = value;
  }
  /**
   * <code>optional string app_package = 12;</code>
   */
  private void clearAppPackage() {
    bitField0_ = (bitField0_ & ~0x00000080);
    appPackage_ = getDefaultInstance().getAppPackage();
  }
  /**
   * <code>optional string app_package = 12;</code>
   * @param value The bytes for appPackage to set.
   */
  private void setAppPackageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    appPackage_ = value.toStringUtf8();
    bitField0_ |= 0x00000080;
  }

  public static final int INT13_FIELD_NUMBER = 13;
  private int int13_;
  /**
   * <code>optional int32 int13 = 13;</code>
   * @return Whether the int13 field is set.
   */
  @java.lang.Override
  public boolean hasInt13() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional int32 int13 = 13;</code>
   * @return The int13.
   */
  @java.lang.Override
  public int getInt13() {
    return int13_;
  }
  /**
   * <code>optional int32 int13 = 13;</code>
   * @param value The int13 to set.
   */
  private void setInt13(int value) {
    bitField0_ |= 0x00000100;
    int13_ = value;
  }
  /**
   * <code>optional int32 int13 = 13;</code>
   */
  private void clearInt13() {
    bitField0_ = (bitField0_ & ~0x00000100);
    int13_ = 0;
  }

  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteAppInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteAppInfo prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteAppInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteAppInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteAppInfo)
      com.sprit.tvremote.proto.remote.RemoteAppInfoOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteAppInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 counter = 1;</code>
     * @return Whether the counter field is set.
     */
    @java.lang.Override
    public boolean hasCounter() {
      return instance.hasCounter();
    }
    /**
     * <code>optional int32 counter = 1;</code>
     * @return The counter.
     */
    @java.lang.Override
    public int getCounter() {
      return instance.getCounter();
    }
    /**
     * <code>optional int32 counter = 1;</code>
     * @param value The counter to set.
     * @return This builder for chaining.
     */
    public Builder setCounter(int value) {
      copyOnWrite();
      instance.setCounter(value);
      return this;
    }
    /**
     * <code>optional int32 counter = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCounter() {
      copyOnWrite();
      instance.clearCounter();
      return this;
    }

    /**
     * <code>optional int32 int2 = 2;</code>
     * @return Whether the int2 field is set.
     */
    @java.lang.Override
    public boolean hasInt2() {
      return instance.hasInt2();
    }
    /**
     * <code>optional int32 int2 = 2;</code>
     * @return The int2.
     */
    @java.lang.Override
    public int getInt2() {
      return instance.getInt2();
    }
    /**
     * <code>optional int32 int2 = 2;</code>
     * @param value The int2 to set.
     * @return This builder for chaining.
     */
    public Builder setInt2(int value) {
      copyOnWrite();
      instance.setInt2(value);
      return this;
    }
    /**
     * <code>optional int32 int2 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt2() {
      copyOnWrite();
      instance.clearInt2();
      return this;
    }

    /**
     * <code>optional int32 int3 = 3;</code>
     * @return Whether the int3 field is set.
     */
    @java.lang.Override
    public boolean hasInt3() {
      return instance.hasInt3();
    }
    /**
     * <code>optional int32 int3 = 3;</code>
     * @return The int3.
     */
    @java.lang.Override
    public int getInt3() {
      return instance.getInt3();
    }
    /**
     * <code>optional int32 int3 = 3;</code>
     * @param value The int3 to set.
     * @return This builder for chaining.
     */
    public Builder setInt3(int value) {
      copyOnWrite();
      instance.setInt3(value);
      return this;
    }
    /**
     * <code>optional int32 int3 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt3() {
      copyOnWrite();
      instance.clearInt3();
      return this;
    }

    /**
     * <code>optional string int4 = 4;</code>
     * @return Whether the int4 field is set.
     */
    @java.lang.Override
    public boolean hasInt4() {
      return instance.hasInt4();
    }
    /**
     * <code>optional string int4 = 4;</code>
     * @return The int4.
     */
    @java.lang.Override
    public java.lang.String getInt4() {
      return instance.getInt4();
    }
    /**
     * <code>optional string int4 = 4;</code>
     * @return The bytes for int4.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInt4Bytes() {
      return instance.getInt4Bytes();
    }
    /**
     * <code>optional string int4 = 4;</code>
     * @param value The int4 to set.
     * @return This builder for chaining.
     */
    public Builder setInt4(
        java.lang.String value) {
      copyOnWrite();
      instance.setInt4(value);
      return this;
    }
    /**
     * <code>optional string int4 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt4() {
      copyOnWrite();
      instance.clearInt4();
      return this;
    }
    /**
     * <code>optional string int4 = 4;</code>
     * @param value The bytes for int4 to set.
     * @return This builder for chaining.
     */
    public Builder setInt4Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setInt4Bytes(value);
      return this;
    }

    /**
     * <code>optional int32 int7 = 7;</code>
     * @return Whether the int7 field is set.
     */
    @java.lang.Override
    public boolean hasInt7() {
      return instance.hasInt7();
    }
    /**
     * <code>optional int32 int7 = 7;</code>
     * @return The int7.
     */
    @java.lang.Override
    public int getInt7() {
      return instance.getInt7();
    }
    /**
     * <code>optional int32 int7 = 7;</code>
     * @param value The int7 to set.
     * @return This builder for chaining.
     */
    public Builder setInt7(int value) {
      copyOnWrite();
      instance.setInt7(value);
      return this;
    }
    /**
     * <code>optional int32 int7 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt7() {
      copyOnWrite();
      instance.clearInt7();
      return this;
    }

    /**
     * <code>optional int32 int8 = 8;</code>
     * @return Whether the int8 field is set.
     */
    @java.lang.Override
    public boolean hasInt8() {
      return instance.hasInt8();
    }
    /**
     * <code>optional int32 int8 = 8;</code>
     * @return The int8.
     */
    @java.lang.Override
    public int getInt8() {
      return instance.getInt8();
    }
    /**
     * <code>optional int32 int8 = 8;</code>
     * @param value The int8 to set.
     * @return This builder for chaining.
     */
    public Builder setInt8(int value) {
      copyOnWrite();
      instance.setInt8(value);
      return this;
    }
    /**
     * <code>optional int32 int8 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt8() {
      copyOnWrite();
      instance.clearInt8();
      return this;
    }

    /**
     * <code>optional string label = 10;</code>
     * @return Whether the label field is set.
     */
    @java.lang.Override
    public boolean hasLabel() {
      return instance.hasLabel();
    }
    /**
     * <code>optional string label = 10;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <code>optional string label = 10;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <code>optional string label = 10;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <code>optional string label = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <code>optional string label = 10;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    /**
     * <code>optional string app_package = 12;</code>
     * @return Whether the appPackage field is set.
     */
    @java.lang.Override
    public boolean hasAppPackage() {
      return instance.hasAppPackage();
    }
    /**
     * <code>optional string app_package = 12;</code>
     * @return The appPackage.
     */
    @java.lang.Override
    public java.lang.String getAppPackage() {
      return instance.getAppPackage();
    }
    /**
     * <code>optional string app_package = 12;</code>
     * @return The bytes for appPackage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppPackageBytes() {
      return instance.getAppPackageBytes();
    }
    /**
     * <code>optional string app_package = 12;</code>
     * @param value The appPackage to set.
     * @return This builder for chaining.
     */
    public Builder setAppPackage(
        java.lang.String value) {
      copyOnWrite();
      instance.setAppPackage(value);
      return this;
    }
    /**
     * <code>optional string app_package = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppPackage() {
      copyOnWrite();
      instance.clearAppPackage();
      return this;
    }
    /**
     * <code>optional string app_package = 12;</code>
     * @param value The bytes for appPackage to set.
     * @return This builder for chaining.
     */
    public Builder setAppPackageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppPackageBytes(value);
      return this;
    }

    /**
     * <code>optional int32 int13 = 13;</code>
     * @return Whether the int13 field is set.
     */
    @java.lang.Override
    public boolean hasInt13() {
      return instance.hasInt13();
    }
    /**
     * <code>optional int32 int13 = 13;</code>
     * @return The int13.
     */
    @java.lang.Override
    public int getInt13() {
      return instance.getInt13();
    }
    /**
     * <code>optional int32 int13 = 13;</code>
     * @param value The int13 to set.
     * @return This builder for chaining.
     */
    public Builder setInt13(int value) {
      copyOnWrite();
      instance.setInt13(value);
      return this;
    }
    /**
     * <code>optional int32 int13 = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt13() {
      copyOnWrite();
      instance.clearInt13();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteAppInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteAppInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "counter_",
            "int2_",
            "int3_",
            "int4_",
            "int7_",
            "int8_",
            "label_",
            "appPackage_",
            "int13_",
          };
          java.lang.String info =
              "\u0000\t\u0000\u0001\u0001\r\t\u0000\u0000\u0000\u0001\u1004\u0000\u0002\u1004\u0001" +
              "\u0003\u1004\u0002\u0004\u1208\u0003\u0007\u1004\u0004\b\u1004\u0005\n\u1208\u0006" +
              "\f\u1208\u0007\r\u1004\b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteAppInfo> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteAppInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteAppInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteAppInfo)
  private static final com.sprit.tvremote.proto.remote.RemoteAppInfo DEFAULT_INSTANCE;
  static {
    RemoteAppInfo defaultInstance = new RemoteAppInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteAppInfo.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteAppInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteAppInfo> PARSER;

  public static com.google.protobuf.Parser<RemoteAppInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

