// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteTextFieldStatus}
 */
@com.google.protobuf.Generated
public  final class RemoteTextFieldStatus extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteTextFieldStatus, RemoteTextFieldStatus.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteTextFieldStatus)
    RemoteTextFieldStatusOrBuilder {
  private RemoteTextFieldStatus() {
    value_ = "";
    label_ = "";
  }
  private int bitField0_;
  public static final int COUNTER_FIELD_FIELD_NUMBER = 1;
  private int counterField_;
  /**
   * <code>optional int32 counter_field = 1;</code>
   * @return Whether the counterField field is set.
   */
  @java.lang.Override
  public boolean hasCounterField() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 counter_field = 1;</code>
   * @return The counterField.
   */
  @java.lang.Override
  public int getCounterField() {
    return counterField_;
  }
  /**
   * <code>optional int32 counter_field = 1;</code>
   * @param value The counterField to set.
   */
  private void setCounterField(int value) {
    bitField0_ |= 0x00000001;
    counterField_ = value;
  }
  /**
   * <code>optional int32 counter_field = 1;</code>
   */
  private void clearCounterField() {
    bitField0_ = (bitField0_ & ~0x00000001);
    counterField_ = 0;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private java.lang.String value_;
  /**
   * <code>optional string value = 2;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    return value_;
  }
  /**
   * <code>optional string value = 2;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(value_);
  }
  /**
   * <code>optional string value = 2;</code>
   * @param value The value to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setValue(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000002;
    value_ = value;
  }
  /**
   * <code>optional string value = 2;</code>
   */
  private void clearValue() {
    bitField0_ = (bitField0_ & ~0x00000002);
    value_ = getDefaultInstance().getValue();
  }
  /**
   * <code>optional string value = 2;</code>
   * @param value The bytes for value to set.
   */
  private void setValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    value_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static final int START_FIELD_NUMBER = 3;
  private int start_;
  /**
   * <code>optional int32 start = 3;</code>
   * @return Whether the start field is set.
   */
  @java.lang.Override
  public boolean hasStart() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 start = 3;</code>
   * @return The start.
   */
  @java.lang.Override
  public int getStart() {
    return start_;
  }
  /**
   * <code>optional int32 start = 3;</code>
   * @param value The start to set.
   */
  private void setStart(int value) {
    bitField0_ |= 0x00000004;
    start_ = value;
  }
  /**
   * <code>optional int32 start = 3;</code>
   */
  private void clearStart() {
    bitField0_ = (bitField0_ & ~0x00000004);
    start_ = 0;
  }

  public static final int END_FIELD_NUMBER = 4;
  private int end_;
  /**
   * <code>optional int32 end = 4;</code>
   * @return Whether the end field is set.
   */
  @java.lang.Override
  public boolean hasEnd() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 end = 4;</code>
   * @return The end.
   */
  @java.lang.Override
  public int getEnd() {
    return end_;
  }
  /**
   * <code>optional int32 end = 4;</code>
   * @param value The end to set.
   */
  private void setEnd(int value) {
    bitField0_ |= 0x00000008;
    end_ = value;
  }
  /**
   * <code>optional int32 end = 4;</code>
   */
  private void clearEnd() {
    bitField0_ = (bitField0_ & ~0x00000008);
    end_ = 0;
  }

  public static final int INT5_FIELD_NUMBER = 5;
  private int int5_;
  /**
   * <code>optional int32 int5 = 5;</code>
   * @return Whether the int5 field is set.
   */
  @java.lang.Override
  public boolean hasInt5() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 int5 = 5;</code>
   * @return The int5.
   */
  @java.lang.Override
  public int getInt5() {
    return int5_;
  }
  /**
   * <code>optional int32 int5 = 5;</code>
   * @param value The int5 to set.
   */
  private void setInt5(int value) {
    bitField0_ |= 0x00000010;
    int5_ = value;
  }
  /**
   * <code>optional int32 int5 = 5;</code>
   */
  private void clearInt5() {
    bitField0_ = (bitField0_ & ~0x00000010);
    int5_ = 0;
  }

  public static final int LABEL_FIELD_NUMBER = 6;
  private java.lang.String label_;
  /**
   * <code>optional string label = 6;</code>
   * @return Whether the label field is set.
   */
  @java.lang.Override
  public boolean hasLabel() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string label = 6;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <code>optional string label = 6;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <code>optional string label = 6;</code>
   * @param value The label to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setLabel(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000020;
    label_ = value;
  }
  /**
   * <code>optional string label = 6;</code>
   */
  private void clearLabel() {
    bitField0_ = (bitField0_ & ~0x00000020);
    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <code>optional string label = 6;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    label_ = value.toStringUtf8();
    bitField0_ |= 0x00000020;
  }

  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteTextFieldStatus prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteTextFieldStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteTextFieldStatus, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteTextFieldStatus)
      com.sprit.tvremote.proto.remote.RemoteTextFieldStatusOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 counter_field = 1;</code>
     * @return Whether the counterField field is set.
     */
    @java.lang.Override
    public boolean hasCounterField() {
      return instance.hasCounterField();
    }
    /**
     * <code>optional int32 counter_field = 1;</code>
     * @return The counterField.
     */
    @java.lang.Override
    public int getCounterField() {
      return instance.getCounterField();
    }
    /**
     * <code>optional int32 counter_field = 1;</code>
     * @param value The counterField to set.
     * @return This builder for chaining.
     */
    public Builder setCounterField(int value) {
      copyOnWrite();
      instance.setCounterField(value);
      return this;
    }
    /**
     * <code>optional int32 counter_field = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCounterField() {
      copyOnWrite();
      instance.clearCounterField();
      return this;
    }

    /**
     * <code>optional string value = 2;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return instance.hasValue();
    }
    /**
     * <code>optional string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return instance.getValue();
    }
    /**
     * <code>optional string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return instance.getValueBytes();
    }
    /**
     * <code>optional string value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
    }
    /**
     * <code>optional string value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }
    /**
     * <code>optional string value = 2;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValueBytes(value);
      return this;
    }

    /**
     * <code>optional int32 start = 3;</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return instance.hasStart();
    }
    /**
     * <code>optional int32 start = 3;</code>
     * @return The start.
     */
    @java.lang.Override
    public int getStart() {
      return instance.getStart();
    }
    /**
     * <code>optional int32 start = 3;</code>
     * @param value The start to set.
     * @return This builder for chaining.
     */
    public Builder setStart(int value) {
      copyOnWrite();
      instance.setStart(value);
      return this;
    }
    /**
     * <code>optional int32 start = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStart() {
      copyOnWrite();
      instance.clearStart();
      return this;
    }

    /**
     * <code>optional int32 end = 4;</code>
     * @return Whether the end field is set.
     */
    @java.lang.Override
    public boolean hasEnd() {
      return instance.hasEnd();
    }
    /**
     * <code>optional int32 end = 4;</code>
     * @return The end.
     */
    @java.lang.Override
    public int getEnd() {
      return instance.getEnd();
    }
    /**
     * <code>optional int32 end = 4;</code>
     * @param value The end to set.
     * @return This builder for chaining.
     */
    public Builder setEnd(int value) {
      copyOnWrite();
      instance.setEnd(value);
      return this;
    }
    /**
     * <code>optional int32 end = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnd() {
      copyOnWrite();
      instance.clearEnd();
      return this;
    }

    /**
     * <code>optional int32 int5 = 5;</code>
     * @return Whether the int5 field is set.
     */
    @java.lang.Override
    public boolean hasInt5() {
      return instance.hasInt5();
    }
    /**
     * <code>optional int32 int5 = 5;</code>
     * @return The int5.
     */
    @java.lang.Override
    public int getInt5() {
      return instance.getInt5();
    }
    /**
     * <code>optional int32 int5 = 5;</code>
     * @param value The int5 to set.
     * @return This builder for chaining.
     */
    public Builder setInt5(int value) {
      copyOnWrite();
      instance.setInt5(value);
      return this;
    }
    /**
     * <code>optional int32 int5 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt5() {
      copyOnWrite();
      instance.clearInt5();
      return this;
    }

    /**
     * <code>optional string label = 6;</code>
     * @return Whether the label field is set.
     */
    @java.lang.Override
    public boolean hasLabel() {
      return instance.hasLabel();
    }
    /**
     * <code>optional string label = 6;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <code>optional string label = 6;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <code>optional string label = 6;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <code>optional string label = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <code>optional string label = 6;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteTextFieldStatus)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteTextFieldStatus();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "counterField_",
            "value_",
            "start_",
            "end_",
            "int5_",
            "label_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u1004\u0000\u0002" +
              "\u1208\u0001\u0003\u1004\u0002\u0004\u1004\u0003\u0005\u1004\u0004\u0006\u1208\u0005" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteTextFieldStatus> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteTextFieldStatus.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteTextFieldStatus>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteTextFieldStatus)
  private static final com.sprit.tvremote.proto.remote.RemoteTextFieldStatus DEFAULT_INSTANCE;
  static {
    RemoteTextFieldStatus defaultInstance = new RemoteTextFieldStatus();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteTextFieldStatus.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteTextFieldStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteTextFieldStatus> PARSER;

  public static com.google.protobuf.Parser<RemoteTextFieldStatus> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

