// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteMessage}
 */
@com.google.protobuf.Generated
public  final class RemoteMessage extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteMessage, RemoteMessage.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteMessage)
    RemoteMessageOrBuilder {
  private RemoteMessage() {
  }
  private int bitField0_;
  public static final int REMOTE_CONFIGURE_FIELD_NUMBER = 1;
  private com.sprit.tvremote.proto.remote.RemoteConfigure remoteConfigure_;
  /**
   * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
   */
  @java.lang.Override
  public boolean hasRemoteConfigure() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteConfigure getRemoteConfigure() {
    return remoteConfigure_ == null ? com.sprit.tvremote.proto.remote.RemoteConfigure.getDefaultInstance() : remoteConfigure_;
  }
  /**
   * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteConfigure(com.sprit.tvremote.proto.remote.RemoteConfigure value) {
    value.getClass();  // minimal bytecode null check
    remoteConfigure_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteConfigure(com.sprit.tvremote.proto.remote.RemoteConfigure value) {
    value.getClass();  // minimal bytecode null check
    if (remoteConfigure_ != null &&
        remoteConfigure_ != com.sprit.tvremote.proto.remote.RemoteConfigure.getDefaultInstance()) {
      remoteConfigure_ =
        com.sprit.tvremote.proto.remote.RemoteConfigure.newBuilder(remoteConfigure_).mergeFrom(value).buildPartial();
    } else {
      remoteConfigure_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
   */
  private void clearRemoteConfigure() {
    remoteConfigure_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int REMOTE_SET_ACTIVE_FIELD_NUMBER = 2;
  private com.sprit.tvremote.proto.remote.RemoteSetActive remoteSetActive_;
  /**
   * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
   */
  @java.lang.Override
  public boolean hasRemoteSetActive() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteSetActive getRemoteSetActive() {
    return remoteSetActive_ == null ? com.sprit.tvremote.proto.remote.RemoteSetActive.getDefaultInstance() : remoteSetActive_;
  }
  /**
   * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteSetActive(com.sprit.tvremote.proto.remote.RemoteSetActive value) {
    value.getClass();  // minimal bytecode null check
    remoteSetActive_ = value;
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteSetActive(com.sprit.tvremote.proto.remote.RemoteSetActive value) {
    value.getClass();  // minimal bytecode null check
    if (remoteSetActive_ != null &&
        remoteSetActive_ != com.sprit.tvremote.proto.remote.RemoteSetActive.getDefaultInstance()) {
      remoteSetActive_ =
        com.sprit.tvremote.proto.remote.RemoteSetActive.newBuilder(remoteSetActive_).mergeFrom(value).buildPartial();
    } else {
      remoteSetActive_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
   */
  private void clearRemoteSetActive() {
    remoteSetActive_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int REMOTE_ERROR_FIELD_NUMBER = 3;
  private com.sprit.tvremote.proto.remote.RemoteError remoteError_;
  /**
   * <code>optional .remote.RemoteError remote_error = 3;</code>
   */
  @java.lang.Override
  public boolean hasRemoteError() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .remote.RemoteError remote_error = 3;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteError getRemoteError() {
    return remoteError_ == null ? com.sprit.tvremote.proto.remote.RemoteError.getDefaultInstance() : remoteError_;
  }
  /**
   * <code>optional .remote.RemoteError remote_error = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteError(com.sprit.tvremote.proto.remote.RemoteError value) {
    value.getClass();  // minimal bytecode null check
    remoteError_ = value;
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .remote.RemoteError remote_error = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteError(com.sprit.tvremote.proto.remote.RemoteError value) {
    value.getClass();  // minimal bytecode null check
    if (remoteError_ != null &&
        remoteError_ != com.sprit.tvremote.proto.remote.RemoteError.getDefaultInstance()) {
      remoteError_ =
        com.sprit.tvremote.proto.remote.RemoteError.newBuilder(remoteError_).mergeFrom(value).buildPartial();
    } else {
      remoteError_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .remote.RemoteError remote_error = 3;</code>
   */
  private void clearRemoteError() {
    remoteError_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int REMOTE_PING_REQUEST_FIELD_NUMBER = 8;
  private com.sprit.tvremote.proto.remote.RemotePingRequest remotePingRequest_;
  /**
   * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
   */
  @java.lang.Override
  public boolean hasRemotePingRequest() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemotePingRequest getRemotePingRequest() {
    return remotePingRequest_ == null ? com.sprit.tvremote.proto.remote.RemotePingRequest.getDefaultInstance() : remotePingRequest_;
  }
  /**
   * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemotePingRequest(com.sprit.tvremote.proto.remote.RemotePingRequest value) {
    value.getClass();  // minimal bytecode null check
    remotePingRequest_ = value;
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemotePingRequest(com.sprit.tvremote.proto.remote.RemotePingRequest value) {
    value.getClass();  // minimal bytecode null check
    if (remotePingRequest_ != null &&
        remotePingRequest_ != com.sprit.tvremote.proto.remote.RemotePingRequest.getDefaultInstance()) {
      remotePingRequest_ =
        com.sprit.tvremote.proto.remote.RemotePingRequest.newBuilder(remotePingRequest_).mergeFrom(value).buildPartial();
    } else {
      remotePingRequest_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
   */
  private void clearRemotePingRequest() {
    remotePingRequest_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public static final int REMOTE_PING_RESPONSE_FIELD_NUMBER = 9;
  private com.sprit.tvremote.proto.remote.RemotePingResponse remotePingResponse_;
  /**
   * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
   */
  @java.lang.Override
  public boolean hasRemotePingResponse() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemotePingResponse getRemotePingResponse() {
    return remotePingResponse_ == null ? com.sprit.tvremote.proto.remote.RemotePingResponse.getDefaultInstance() : remotePingResponse_;
  }
  /**
   * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemotePingResponse(com.sprit.tvremote.proto.remote.RemotePingResponse value) {
    value.getClass();  // minimal bytecode null check
    remotePingResponse_ = value;
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemotePingResponse(com.sprit.tvremote.proto.remote.RemotePingResponse value) {
    value.getClass();  // minimal bytecode null check
    if (remotePingResponse_ != null &&
        remotePingResponse_ != com.sprit.tvremote.proto.remote.RemotePingResponse.getDefaultInstance()) {
      remotePingResponse_ =
        com.sprit.tvremote.proto.remote.RemotePingResponse.newBuilder(remotePingResponse_).mergeFrom(value).buildPartial();
    } else {
      remotePingResponse_ = value;
    }
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
   */
  private void clearRemotePingResponse() {
    remotePingResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000010);
  }

  public static final int REMOTE_KEY_INJECT_FIELD_NUMBER = 10;
  private com.sprit.tvremote.proto.remote.RemoteKeyInject remoteKeyInject_;
  /**
   * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
   */
  @java.lang.Override
  public boolean hasRemoteKeyInject() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteKeyInject getRemoteKeyInject() {
    return remoteKeyInject_ == null ? com.sprit.tvremote.proto.remote.RemoteKeyInject.getDefaultInstance() : remoteKeyInject_;
  }
  /**
   * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteKeyInject(com.sprit.tvremote.proto.remote.RemoteKeyInject value) {
    value.getClass();  // minimal bytecode null check
    remoteKeyInject_ = value;
    bitField0_ |= 0x00000020;
  }
  /**
   * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteKeyInject(com.sprit.tvremote.proto.remote.RemoteKeyInject value) {
    value.getClass();  // minimal bytecode null check
    if (remoteKeyInject_ != null &&
        remoteKeyInject_ != com.sprit.tvremote.proto.remote.RemoteKeyInject.getDefaultInstance()) {
      remoteKeyInject_ =
        com.sprit.tvremote.proto.remote.RemoteKeyInject.newBuilder(remoteKeyInject_).mergeFrom(value).buildPartial();
    } else {
      remoteKeyInject_ = value;
    }
    bitField0_ |= 0x00000020;
  }
  /**
   * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
   */
  private void clearRemoteKeyInject() {
    remoteKeyInject_ = null;
    bitField0_ = (bitField0_ & ~0x00000020);
  }

  public static final int REMOTE_IME_KEY_INJECT_FIELD_NUMBER = 20;
  private com.sprit.tvremote.proto.remote.RemoteImeKeyInject remoteImeKeyInject_;
  /**
   * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
   */
  @java.lang.Override
  public boolean hasRemoteImeKeyInject() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteImeKeyInject getRemoteImeKeyInject() {
    return remoteImeKeyInject_ == null ? com.sprit.tvremote.proto.remote.RemoteImeKeyInject.getDefaultInstance() : remoteImeKeyInject_;
  }
  /**
   * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteImeKeyInject(com.sprit.tvremote.proto.remote.RemoteImeKeyInject value) {
    value.getClass();  // minimal bytecode null check
    remoteImeKeyInject_ = value;
    bitField0_ |= 0x00000040;
  }
  /**
   * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteImeKeyInject(com.sprit.tvremote.proto.remote.RemoteImeKeyInject value) {
    value.getClass();  // minimal bytecode null check
    if (remoteImeKeyInject_ != null &&
        remoteImeKeyInject_ != com.sprit.tvremote.proto.remote.RemoteImeKeyInject.getDefaultInstance()) {
      remoteImeKeyInject_ =
        com.sprit.tvremote.proto.remote.RemoteImeKeyInject.newBuilder(remoteImeKeyInject_).mergeFrom(value).buildPartial();
    } else {
      remoteImeKeyInject_ = value;
    }
    bitField0_ |= 0x00000040;
  }
  /**
   * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
   */
  private void clearRemoteImeKeyInject() {
    remoteImeKeyInject_ = null;
    bitField0_ = (bitField0_ & ~0x00000040);
  }

  public static final int REMOTE_IME_BATCH_EDIT_FIELD_NUMBER = 21;
  private com.sprit.tvremote.proto.remote.RemoteImeBatchEdit remoteImeBatchEdit_;
  /**
   * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
   */
  @java.lang.Override
  public boolean hasRemoteImeBatchEdit() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteImeBatchEdit getRemoteImeBatchEdit() {
    return remoteImeBatchEdit_ == null ? com.sprit.tvremote.proto.remote.RemoteImeBatchEdit.getDefaultInstance() : remoteImeBatchEdit_;
  }
  /**
   * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteImeBatchEdit(com.sprit.tvremote.proto.remote.RemoteImeBatchEdit value) {
    value.getClass();  // minimal bytecode null check
    remoteImeBatchEdit_ = value;
    bitField0_ |= 0x00000080;
  }
  /**
   * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteImeBatchEdit(com.sprit.tvremote.proto.remote.RemoteImeBatchEdit value) {
    value.getClass();  // minimal bytecode null check
    if (remoteImeBatchEdit_ != null &&
        remoteImeBatchEdit_ != com.sprit.tvremote.proto.remote.RemoteImeBatchEdit.getDefaultInstance()) {
      remoteImeBatchEdit_ =
        com.sprit.tvremote.proto.remote.RemoteImeBatchEdit.newBuilder(remoteImeBatchEdit_).mergeFrom(value).buildPartial();
    } else {
      remoteImeBatchEdit_ = value;
    }
    bitField0_ |= 0x00000080;
  }
  /**
   * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
   */
  private void clearRemoteImeBatchEdit() {
    remoteImeBatchEdit_ = null;
    bitField0_ = (bitField0_ & ~0x00000080);
  }

  public static final int REMOTE_IME_SHOW_REQUEST_FIELD_NUMBER = 22;
  private com.sprit.tvremote.proto.remote.RemoteImeShowRequest remoteImeShowRequest_;
  /**
   * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
   */
  @java.lang.Override
  public boolean hasRemoteImeShowRequest() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteImeShowRequest getRemoteImeShowRequest() {
    return remoteImeShowRequest_ == null ? com.sprit.tvremote.proto.remote.RemoteImeShowRequest.getDefaultInstance() : remoteImeShowRequest_;
  }
  /**
   * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteImeShowRequest(com.sprit.tvremote.proto.remote.RemoteImeShowRequest value) {
    value.getClass();  // minimal bytecode null check
    remoteImeShowRequest_ = value;
    bitField0_ |= 0x00000100;
  }
  /**
   * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteImeShowRequest(com.sprit.tvremote.proto.remote.RemoteImeShowRequest value) {
    value.getClass();  // minimal bytecode null check
    if (remoteImeShowRequest_ != null &&
        remoteImeShowRequest_ != com.sprit.tvremote.proto.remote.RemoteImeShowRequest.getDefaultInstance()) {
      remoteImeShowRequest_ =
        com.sprit.tvremote.proto.remote.RemoteImeShowRequest.newBuilder(remoteImeShowRequest_).mergeFrom(value).buildPartial();
    } else {
      remoteImeShowRequest_ = value;
    }
    bitField0_ |= 0x00000100;
  }
  /**
   * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
   */
  private void clearRemoteImeShowRequest() {
    remoteImeShowRequest_ = null;
    bitField0_ = (bitField0_ & ~0x00000100);
  }

  public static final int REMOTE_VOICE_BEGIN_FIELD_NUMBER = 30;
  private com.sprit.tvremote.proto.remote.RemoteVoiceBegin remoteVoiceBegin_;
  /**
   * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
   */
  @java.lang.Override
  public boolean hasRemoteVoiceBegin() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteVoiceBegin getRemoteVoiceBegin() {
    return remoteVoiceBegin_ == null ? com.sprit.tvremote.proto.remote.RemoteVoiceBegin.getDefaultInstance() : remoteVoiceBegin_;
  }
  /**
   * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteVoiceBegin(com.sprit.tvremote.proto.remote.RemoteVoiceBegin value) {
    value.getClass();  // minimal bytecode null check
    remoteVoiceBegin_ = value;
    bitField0_ |= 0x00000200;
  }
  /**
   * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteVoiceBegin(com.sprit.tvremote.proto.remote.RemoteVoiceBegin value) {
    value.getClass();  // minimal bytecode null check
    if (remoteVoiceBegin_ != null &&
        remoteVoiceBegin_ != com.sprit.tvremote.proto.remote.RemoteVoiceBegin.getDefaultInstance()) {
      remoteVoiceBegin_ =
        com.sprit.tvremote.proto.remote.RemoteVoiceBegin.newBuilder(remoteVoiceBegin_).mergeFrom(value).buildPartial();
    } else {
      remoteVoiceBegin_ = value;
    }
    bitField0_ |= 0x00000200;
  }
  /**
   * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
   */
  private void clearRemoteVoiceBegin() {
    remoteVoiceBegin_ = null;
    bitField0_ = (bitField0_ & ~0x00000200);
  }

  public static final int REMOTE_VOICE_PAYLOAD_FIELD_NUMBER = 31;
  private com.sprit.tvremote.proto.remote.RemoteVoicePayload remoteVoicePayload_;
  /**
   * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
   */
  @java.lang.Override
  public boolean hasRemoteVoicePayload() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteVoicePayload getRemoteVoicePayload() {
    return remoteVoicePayload_ == null ? com.sprit.tvremote.proto.remote.RemoteVoicePayload.getDefaultInstance() : remoteVoicePayload_;
  }
  /**
   * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteVoicePayload(com.sprit.tvremote.proto.remote.RemoteVoicePayload value) {
    value.getClass();  // minimal bytecode null check
    remoteVoicePayload_ = value;
    bitField0_ |= 0x00000400;
  }
  /**
   * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteVoicePayload(com.sprit.tvremote.proto.remote.RemoteVoicePayload value) {
    value.getClass();  // minimal bytecode null check
    if (remoteVoicePayload_ != null &&
        remoteVoicePayload_ != com.sprit.tvremote.proto.remote.RemoteVoicePayload.getDefaultInstance()) {
      remoteVoicePayload_ =
        com.sprit.tvremote.proto.remote.RemoteVoicePayload.newBuilder(remoteVoicePayload_).mergeFrom(value).buildPartial();
    } else {
      remoteVoicePayload_ = value;
    }
    bitField0_ |= 0x00000400;
  }
  /**
   * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
   */
  private void clearRemoteVoicePayload() {
    remoteVoicePayload_ = null;
    bitField0_ = (bitField0_ & ~0x00000400);
  }

  public static final int REMOTE_VOICE_END_FIELD_NUMBER = 32;
  private com.sprit.tvremote.proto.remote.RemoteVoiceEnd remoteVoiceEnd_;
  /**
   * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
   */
  @java.lang.Override
  public boolean hasRemoteVoiceEnd() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteVoiceEnd getRemoteVoiceEnd() {
    return remoteVoiceEnd_ == null ? com.sprit.tvremote.proto.remote.RemoteVoiceEnd.getDefaultInstance() : remoteVoiceEnd_;
  }
  /**
   * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteVoiceEnd(com.sprit.tvremote.proto.remote.RemoteVoiceEnd value) {
    value.getClass();  // minimal bytecode null check
    remoteVoiceEnd_ = value;
    bitField0_ |= 0x00000800;
  }
  /**
   * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteVoiceEnd(com.sprit.tvremote.proto.remote.RemoteVoiceEnd value) {
    value.getClass();  // minimal bytecode null check
    if (remoteVoiceEnd_ != null &&
        remoteVoiceEnd_ != com.sprit.tvremote.proto.remote.RemoteVoiceEnd.getDefaultInstance()) {
      remoteVoiceEnd_ =
        com.sprit.tvremote.proto.remote.RemoteVoiceEnd.newBuilder(remoteVoiceEnd_).mergeFrom(value).buildPartial();
    } else {
      remoteVoiceEnd_ = value;
    }
    bitField0_ |= 0x00000800;
  }
  /**
   * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
   */
  private void clearRemoteVoiceEnd() {
    remoteVoiceEnd_ = null;
    bitField0_ = (bitField0_ & ~0x00000800);
  }

  public static final int REMOTE_START_FIELD_NUMBER = 40;
  private com.sprit.tvremote.proto.remote.RemoteStart remoteStart_;
  /**
   * <code>optional .remote.RemoteStart remote_start = 40;</code>
   */
  @java.lang.Override
  public boolean hasRemoteStart() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <code>optional .remote.RemoteStart remote_start = 40;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteStart getRemoteStart() {
    return remoteStart_ == null ? com.sprit.tvremote.proto.remote.RemoteStart.getDefaultInstance() : remoteStart_;
  }
  /**
   * <code>optional .remote.RemoteStart remote_start = 40;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteStart(com.sprit.tvremote.proto.remote.RemoteStart value) {
    value.getClass();  // minimal bytecode null check
    remoteStart_ = value;
    bitField0_ |= 0x00001000;
  }
  /**
   * <code>optional .remote.RemoteStart remote_start = 40;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteStart(com.sprit.tvremote.proto.remote.RemoteStart value) {
    value.getClass();  // minimal bytecode null check
    if (remoteStart_ != null &&
        remoteStart_ != com.sprit.tvremote.proto.remote.RemoteStart.getDefaultInstance()) {
      remoteStart_ =
        com.sprit.tvremote.proto.remote.RemoteStart.newBuilder(remoteStart_).mergeFrom(value).buildPartial();
    } else {
      remoteStart_ = value;
    }
    bitField0_ |= 0x00001000;
  }
  /**
   * <code>optional .remote.RemoteStart remote_start = 40;</code>
   */
  private void clearRemoteStart() {
    remoteStart_ = null;
    bitField0_ = (bitField0_ & ~0x00001000);
  }

  public static final int REMOTE_SET_VOLUME_LEVEL_FIELD_NUMBER = 50;
  private com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel remoteSetVolumeLevel_;
  /**
   * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
   */
  @java.lang.Override
  public boolean hasRemoteSetVolumeLevel() {
    return ((bitField0_ & 0x00002000) != 0);
  }
  /**
   * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel getRemoteSetVolumeLevel() {
    return remoteSetVolumeLevel_ == null ? com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel.getDefaultInstance() : remoteSetVolumeLevel_;
  }
  /**
   * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteSetVolumeLevel(com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel value) {
    value.getClass();  // minimal bytecode null check
    remoteSetVolumeLevel_ = value;
    bitField0_ |= 0x00002000;
  }
  /**
   * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteSetVolumeLevel(com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel value) {
    value.getClass();  // minimal bytecode null check
    if (remoteSetVolumeLevel_ != null &&
        remoteSetVolumeLevel_ != com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel.getDefaultInstance()) {
      remoteSetVolumeLevel_ =
        com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel.newBuilder(remoteSetVolumeLevel_).mergeFrom(value).buildPartial();
    } else {
      remoteSetVolumeLevel_ = value;
    }
    bitField0_ |= 0x00002000;
  }
  /**
   * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
   */
  private void clearRemoteSetVolumeLevel() {
    remoteSetVolumeLevel_ = null;
    bitField0_ = (bitField0_ & ~0x00002000);
  }

  public static final int REMOTE_ADJUST_VOLUME_LEVEL_FIELD_NUMBER = 51;
  private com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel remoteAdjustVolumeLevel_;
  /**
   * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
   */
  @java.lang.Override
  public boolean hasRemoteAdjustVolumeLevel() {
    return ((bitField0_ & 0x00004000) != 0);
  }
  /**
   * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel getRemoteAdjustVolumeLevel() {
    return remoteAdjustVolumeLevel_ == null ? com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel.getDefaultInstance() : remoteAdjustVolumeLevel_;
  }
  /**
   * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteAdjustVolumeLevel(com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel value) {
    value.getClass();  // minimal bytecode null check
    remoteAdjustVolumeLevel_ = value;
    bitField0_ |= 0x00004000;
  }
  /**
   * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteAdjustVolumeLevel(com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel value) {
    value.getClass();  // minimal bytecode null check
    if (remoteAdjustVolumeLevel_ != null &&
        remoteAdjustVolumeLevel_ != com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel.getDefaultInstance()) {
      remoteAdjustVolumeLevel_ =
        com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel.newBuilder(remoteAdjustVolumeLevel_).mergeFrom(value).buildPartial();
    } else {
      remoteAdjustVolumeLevel_ = value;
    }
    bitField0_ |= 0x00004000;
  }
  /**
   * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
   */
  private void clearRemoteAdjustVolumeLevel() {
    remoteAdjustVolumeLevel_ = null;
    bitField0_ = (bitField0_ & ~0x00004000);
  }

  public static final int REMOTE_SET_PREFERRED_AUDIO_DEVICE_FIELD_NUMBER = 60;
  private com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice remoteSetPreferredAudioDevice_;
  /**
   * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
   */
  @java.lang.Override
  public boolean hasRemoteSetPreferredAudioDevice() {
    return ((bitField0_ & 0x00008000) != 0);
  }
  /**
   * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice getRemoteSetPreferredAudioDevice() {
    return remoteSetPreferredAudioDevice_ == null ? com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice.getDefaultInstance() : remoteSetPreferredAudioDevice_;
  }
  /**
   * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteSetPreferredAudioDevice(com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice value) {
    value.getClass();  // minimal bytecode null check
    remoteSetPreferredAudioDevice_ = value;
    bitField0_ |= 0x00008000;
  }
  /**
   * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteSetPreferredAudioDevice(com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice value) {
    value.getClass();  // minimal bytecode null check
    if (remoteSetPreferredAudioDevice_ != null &&
        remoteSetPreferredAudioDevice_ != com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice.getDefaultInstance()) {
      remoteSetPreferredAudioDevice_ =
        com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice.newBuilder(remoteSetPreferredAudioDevice_).mergeFrom(value).buildPartial();
    } else {
      remoteSetPreferredAudioDevice_ = value;
    }
    bitField0_ |= 0x00008000;
  }
  /**
   * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
   */
  private void clearRemoteSetPreferredAudioDevice() {
    remoteSetPreferredAudioDevice_ = null;
    bitField0_ = (bitField0_ & ~0x00008000);
  }

  public static final int REMOTE_RESET_PREFERRED_AUDIO_DEVICE_FIELD_NUMBER = 61;
  private com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice remoteResetPreferredAudioDevice_;
  /**
   * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
   */
  @java.lang.Override
  public boolean hasRemoteResetPreferredAudioDevice() {
    return ((bitField0_ & 0x00010000) != 0);
  }
  /**
   * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice getRemoteResetPreferredAudioDevice() {
    return remoteResetPreferredAudioDevice_ == null ? com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice.getDefaultInstance() : remoteResetPreferredAudioDevice_;
  }
  /**
   * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteResetPreferredAudioDevice(com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice value) {
    value.getClass();  // minimal bytecode null check
    remoteResetPreferredAudioDevice_ = value;
    bitField0_ |= 0x00010000;
  }
  /**
   * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteResetPreferredAudioDevice(com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice value) {
    value.getClass();  // minimal bytecode null check
    if (remoteResetPreferredAudioDevice_ != null &&
        remoteResetPreferredAudioDevice_ != com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice.getDefaultInstance()) {
      remoteResetPreferredAudioDevice_ =
        com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice.newBuilder(remoteResetPreferredAudioDevice_).mergeFrom(value).buildPartial();
    } else {
      remoteResetPreferredAudioDevice_ = value;
    }
    bitField0_ |= 0x00010000;
  }
  /**
   * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
   */
  private void clearRemoteResetPreferredAudioDevice() {
    remoteResetPreferredAudioDevice_ = null;
    bitField0_ = (bitField0_ & ~0x00010000);
  }

  public static final int REMOTE_APP_LINK_LAUNCH_REQUEST_FIELD_NUMBER = 90;
  private com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest remoteAppLinkLaunchRequest_;
  /**
   * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
   */
  @java.lang.Override
  public boolean hasRemoteAppLinkLaunchRequest() {
    return ((bitField0_ & 0x00020000) != 0);
  }
  /**
   * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest getRemoteAppLinkLaunchRequest() {
    return remoteAppLinkLaunchRequest_ == null ? com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest.getDefaultInstance() : remoteAppLinkLaunchRequest_;
  }
  /**
   * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRemoteAppLinkLaunchRequest(com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest value) {
    value.getClass();  // minimal bytecode null check
    remoteAppLinkLaunchRequest_ = value;
    bitField0_ |= 0x00020000;
  }
  /**
   * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeRemoteAppLinkLaunchRequest(com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest value) {
    value.getClass();  // minimal bytecode null check
    if (remoteAppLinkLaunchRequest_ != null &&
        remoteAppLinkLaunchRequest_ != com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest.getDefaultInstance()) {
      remoteAppLinkLaunchRequest_ =
        com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest.newBuilder(remoteAppLinkLaunchRequest_).mergeFrom(value).buildPartial();
    } else {
      remoteAppLinkLaunchRequest_ = value;
    }
    bitField0_ |= 0x00020000;
  }
  /**
   * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
   */
  private void clearRemoteAppLinkLaunchRequest() {
    remoteAppLinkLaunchRequest_ = null;
    bitField0_ = (bitField0_ & ~0x00020000);
  }

  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteMessage prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteMessage, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteMessage)
      com.sprit.tvremote.proto.remote.RemoteMessageOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteMessage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
     */
    @java.lang.Override
    public boolean hasRemoteConfigure() {
      return instance.hasRemoteConfigure();
    }
    /**
     * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteConfigure getRemoteConfigure() {
      return instance.getRemoteConfigure();
    }
    /**
     * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
     */
    public Builder setRemoteConfigure(com.sprit.tvremote.proto.remote.RemoteConfigure value) {
      copyOnWrite();
      instance.setRemoteConfigure(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
     */
    public Builder setRemoteConfigure(
        com.sprit.tvremote.proto.remote.RemoteConfigure.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteConfigure(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
     */
    public Builder mergeRemoteConfigure(com.sprit.tvremote.proto.remote.RemoteConfigure value) {
      copyOnWrite();
      instance.mergeRemoteConfigure(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteConfigure remote_configure = 1;</code>
     */
    public Builder clearRemoteConfigure() {  copyOnWrite();
      instance.clearRemoteConfigure();
      return this;
    }

    /**
     * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
     */
    @java.lang.Override
    public boolean hasRemoteSetActive() {
      return instance.hasRemoteSetActive();
    }
    /**
     * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteSetActive getRemoteSetActive() {
      return instance.getRemoteSetActive();
    }
    /**
     * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
     */
    public Builder setRemoteSetActive(com.sprit.tvremote.proto.remote.RemoteSetActive value) {
      copyOnWrite();
      instance.setRemoteSetActive(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
     */
    public Builder setRemoteSetActive(
        com.sprit.tvremote.proto.remote.RemoteSetActive.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteSetActive(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
     */
    public Builder mergeRemoteSetActive(com.sprit.tvremote.proto.remote.RemoteSetActive value) {
      copyOnWrite();
      instance.mergeRemoteSetActive(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteSetActive remote_set_active = 2;</code>
     */
    public Builder clearRemoteSetActive() {  copyOnWrite();
      instance.clearRemoteSetActive();
      return this;
    }

    /**
     * <code>optional .remote.RemoteError remote_error = 3;</code>
     */
    @java.lang.Override
    public boolean hasRemoteError() {
      return instance.hasRemoteError();
    }
    /**
     * <code>optional .remote.RemoteError remote_error = 3;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteError getRemoteError() {
      return instance.getRemoteError();
    }
    /**
     * <code>optional .remote.RemoteError remote_error = 3;</code>
     */
    public Builder setRemoteError(com.sprit.tvremote.proto.remote.RemoteError value) {
      copyOnWrite();
      instance.setRemoteError(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteError remote_error = 3;</code>
     */
    public Builder setRemoteError(
        com.sprit.tvremote.proto.remote.RemoteError.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteError(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteError remote_error = 3;</code>
     */
    public Builder mergeRemoteError(com.sprit.tvremote.proto.remote.RemoteError value) {
      copyOnWrite();
      instance.mergeRemoteError(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteError remote_error = 3;</code>
     */
    public Builder clearRemoteError() {  copyOnWrite();
      instance.clearRemoteError();
      return this;
    }

    /**
     * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
     */
    @java.lang.Override
    public boolean hasRemotePingRequest() {
      return instance.hasRemotePingRequest();
    }
    /**
     * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemotePingRequest getRemotePingRequest() {
      return instance.getRemotePingRequest();
    }
    /**
     * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
     */
    public Builder setRemotePingRequest(com.sprit.tvremote.proto.remote.RemotePingRequest value) {
      copyOnWrite();
      instance.setRemotePingRequest(value);
      return this;
      }
    /**
     * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
     */
    public Builder setRemotePingRequest(
        com.sprit.tvremote.proto.remote.RemotePingRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setRemotePingRequest(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
     */
    public Builder mergeRemotePingRequest(com.sprit.tvremote.proto.remote.RemotePingRequest value) {
      copyOnWrite();
      instance.mergeRemotePingRequest(value);
      return this;
    }
    /**
     * <code>optional .remote.RemotePingRequest remote_ping_request = 8;</code>
     */
    public Builder clearRemotePingRequest() {  copyOnWrite();
      instance.clearRemotePingRequest();
      return this;
    }

    /**
     * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
     */
    @java.lang.Override
    public boolean hasRemotePingResponse() {
      return instance.hasRemotePingResponse();
    }
    /**
     * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemotePingResponse getRemotePingResponse() {
      return instance.getRemotePingResponse();
    }
    /**
     * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
     */
    public Builder setRemotePingResponse(com.sprit.tvremote.proto.remote.RemotePingResponse value) {
      copyOnWrite();
      instance.setRemotePingResponse(value);
      return this;
      }
    /**
     * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
     */
    public Builder setRemotePingResponse(
        com.sprit.tvremote.proto.remote.RemotePingResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setRemotePingResponse(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
     */
    public Builder mergeRemotePingResponse(com.sprit.tvremote.proto.remote.RemotePingResponse value) {
      copyOnWrite();
      instance.mergeRemotePingResponse(value);
      return this;
    }
    /**
     * <code>optional .remote.RemotePingResponse remote_ping_response = 9;</code>
     */
    public Builder clearRemotePingResponse() {  copyOnWrite();
      instance.clearRemotePingResponse();
      return this;
    }

    /**
     * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
     */
    @java.lang.Override
    public boolean hasRemoteKeyInject() {
      return instance.hasRemoteKeyInject();
    }
    /**
     * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteKeyInject getRemoteKeyInject() {
      return instance.getRemoteKeyInject();
    }
    /**
     * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
     */
    public Builder setRemoteKeyInject(com.sprit.tvremote.proto.remote.RemoteKeyInject value) {
      copyOnWrite();
      instance.setRemoteKeyInject(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
     */
    public Builder setRemoteKeyInject(
        com.sprit.tvremote.proto.remote.RemoteKeyInject.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteKeyInject(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
     */
    public Builder mergeRemoteKeyInject(com.sprit.tvremote.proto.remote.RemoteKeyInject value) {
      copyOnWrite();
      instance.mergeRemoteKeyInject(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteKeyInject remote_key_inject = 10;</code>
     */
    public Builder clearRemoteKeyInject() {  copyOnWrite();
      instance.clearRemoteKeyInject();
      return this;
    }

    /**
     * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
     */
    @java.lang.Override
    public boolean hasRemoteImeKeyInject() {
      return instance.hasRemoteImeKeyInject();
    }
    /**
     * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteImeKeyInject getRemoteImeKeyInject() {
      return instance.getRemoteImeKeyInject();
    }
    /**
     * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
     */
    public Builder setRemoteImeKeyInject(com.sprit.tvremote.proto.remote.RemoteImeKeyInject value) {
      copyOnWrite();
      instance.setRemoteImeKeyInject(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
     */
    public Builder setRemoteImeKeyInject(
        com.sprit.tvremote.proto.remote.RemoteImeKeyInject.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteImeKeyInject(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
     */
    public Builder mergeRemoteImeKeyInject(com.sprit.tvremote.proto.remote.RemoteImeKeyInject value) {
      copyOnWrite();
      instance.mergeRemoteImeKeyInject(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteImeKeyInject remote_ime_key_inject = 20;</code>
     */
    public Builder clearRemoteImeKeyInject() {  copyOnWrite();
      instance.clearRemoteImeKeyInject();
      return this;
    }

    /**
     * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
     */
    @java.lang.Override
    public boolean hasRemoteImeBatchEdit() {
      return instance.hasRemoteImeBatchEdit();
    }
    /**
     * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteImeBatchEdit getRemoteImeBatchEdit() {
      return instance.getRemoteImeBatchEdit();
    }
    /**
     * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
     */
    public Builder setRemoteImeBatchEdit(com.sprit.tvremote.proto.remote.RemoteImeBatchEdit value) {
      copyOnWrite();
      instance.setRemoteImeBatchEdit(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
     */
    public Builder setRemoteImeBatchEdit(
        com.sprit.tvremote.proto.remote.RemoteImeBatchEdit.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteImeBatchEdit(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
     */
    public Builder mergeRemoteImeBatchEdit(com.sprit.tvremote.proto.remote.RemoteImeBatchEdit value) {
      copyOnWrite();
      instance.mergeRemoteImeBatchEdit(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteImeBatchEdit remote_ime_batch_edit = 21;</code>
     */
    public Builder clearRemoteImeBatchEdit() {  copyOnWrite();
      instance.clearRemoteImeBatchEdit();
      return this;
    }

    /**
     * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
     */
    @java.lang.Override
    public boolean hasRemoteImeShowRequest() {
      return instance.hasRemoteImeShowRequest();
    }
    /**
     * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteImeShowRequest getRemoteImeShowRequest() {
      return instance.getRemoteImeShowRequest();
    }
    /**
     * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
     */
    public Builder setRemoteImeShowRequest(com.sprit.tvremote.proto.remote.RemoteImeShowRequest value) {
      copyOnWrite();
      instance.setRemoteImeShowRequest(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
     */
    public Builder setRemoteImeShowRequest(
        com.sprit.tvremote.proto.remote.RemoteImeShowRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteImeShowRequest(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
     */
    public Builder mergeRemoteImeShowRequest(com.sprit.tvremote.proto.remote.RemoteImeShowRequest value) {
      copyOnWrite();
      instance.mergeRemoteImeShowRequest(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteImeShowRequest remote_ime_show_request = 22;</code>
     */
    public Builder clearRemoteImeShowRequest() {  copyOnWrite();
      instance.clearRemoteImeShowRequest();
      return this;
    }

    /**
     * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
     */
    @java.lang.Override
    public boolean hasRemoteVoiceBegin() {
      return instance.hasRemoteVoiceBegin();
    }
    /**
     * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteVoiceBegin getRemoteVoiceBegin() {
      return instance.getRemoteVoiceBegin();
    }
    /**
     * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
     */
    public Builder setRemoteVoiceBegin(com.sprit.tvremote.proto.remote.RemoteVoiceBegin value) {
      copyOnWrite();
      instance.setRemoteVoiceBegin(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
     */
    public Builder setRemoteVoiceBegin(
        com.sprit.tvremote.proto.remote.RemoteVoiceBegin.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteVoiceBegin(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
     */
    public Builder mergeRemoteVoiceBegin(com.sprit.tvremote.proto.remote.RemoteVoiceBegin value) {
      copyOnWrite();
      instance.mergeRemoteVoiceBegin(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteVoiceBegin remote_voice_begin = 30;</code>
     */
    public Builder clearRemoteVoiceBegin() {  copyOnWrite();
      instance.clearRemoteVoiceBegin();
      return this;
    }

    /**
     * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
     */
    @java.lang.Override
    public boolean hasRemoteVoicePayload() {
      return instance.hasRemoteVoicePayload();
    }
    /**
     * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteVoicePayload getRemoteVoicePayload() {
      return instance.getRemoteVoicePayload();
    }
    /**
     * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
     */
    public Builder setRemoteVoicePayload(com.sprit.tvremote.proto.remote.RemoteVoicePayload value) {
      copyOnWrite();
      instance.setRemoteVoicePayload(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
     */
    public Builder setRemoteVoicePayload(
        com.sprit.tvremote.proto.remote.RemoteVoicePayload.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteVoicePayload(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
     */
    public Builder mergeRemoteVoicePayload(com.sprit.tvremote.proto.remote.RemoteVoicePayload value) {
      copyOnWrite();
      instance.mergeRemoteVoicePayload(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteVoicePayload remote_voice_payload = 31;</code>
     */
    public Builder clearRemoteVoicePayload() {  copyOnWrite();
      instance.clearRemoteVoicePayload();
      return this;
    }

    /**
     * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
     */
    @java.lang.Override
    public boolean hasRemoteVoiceEnd() {
      return instance.hasRemoteVoiceEnd();
    }
    /**
     * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteVoiceEnd getRemoteVoiceEnd() {
      return instance.getRemoteVoiceEnd();
    }
    /**
     * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
     */
    public Builder setRemoteVoiceEnd(com.sprit.tvremote.proto.remote.RemoteVoiceEnd value) {
      copyOnWrite();
      instance.setRemoteVoiceEnd(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
     */
    public Builder setRemoteVoiceEnd(
        com.sprit.tvremote.proto.remote.RemoteVoiceEnd.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteVoiceEnd(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
     */
    public Builder mergeRemoteVoiceEnd(com.sprit.tvremote.proto.remote.RemoteVoiceEnd value) {
      copyOnWrite();
      instance.mergeRemoteVoiceEnd(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteVoiceEnd remote_voice_end = 32;</code>
     */
    public Builder clearRemoteVoiceEnd() {  copyOnWrite();
      instance.clearRemoteVoiceEnd();
      return this;
    }

    /**
     * <code>optional .remote.RemoteStart remote_start = 40;</code>
     */
    @java.lang.Override
    public boolean hasRemoteStart() {
      return instance.hasRemoteStart();
    }
    /**
     * <code>optional .remote.RemoteStart remote_start = 40;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteStart getRemoteStart() {
      return instance.getRemoteStart();
    }
    /**
     * <code>optional .remote.RemoteStart remote_start = 40;</code>
     */
    public Builder setRemoteStart(com.sprit.tvremote.proto.remote.RemoteStart value) {
      copyOnWrite();
      instance.setRemoteStart(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteStart remote_start = 40;</code>
     */
    public Builder setRemoteStart(
        com.sprit.tvremote.proto.remote.RemoteStart.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteStart(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteStart remote_start = 40;</code>
     */
    public Builder mergeRemoteStart(com.sprit.tvremote.proto.remote.RemoteStart value) {
      copyOnWrite();
      instance.mergeRemoteStart(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteStart remote_start = 40;</code>
     */
    public Builder clearRemoteStart() {  copyOnWrite();
      instance.clearRemoteStart();
      return this;
    }

    /**
     * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
     */
    @java.lang.Override
    public boolean hasRemoteSetVolumeLevel() {
      return instance.hasRemoteSetVolumeLevel();
    }
    /**
     * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel getRemoteSetVolumeLevel() {
      return instance.getRemoteSetVolumeLevel();
    }
    /**
     * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
     */
    public Builder setRemoteSetVolumeLevel(com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel value) {
      copyOnWrite();
      instance.setRemoteSetVolumeLevel(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
     */
    public Builder setRemoteSetVolumeLevel(
        com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteSetVolumeLevel(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
     */
    public Builder mergeRemoteSetVolumeLevel(com.sprit.tvremote.proto.remote.RemoteSetVolumeLevel value) {
      copyOnWrite();
      instance.mergeRemoteSetVolumeLevel(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteSetVolumeLevel remote_set_volume_level = 50;</code>
     */
    public Builder clearRemoteSetVolumeLevel() {  copyOnWrite();
      instance.clearRemoteSetVolumeLevel();
      return this;
    }

    /**
     * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
     */
    @java.lang.Override
    public boolean hasRemoteAdjustVolumeLevel() {
      return instance.hasRemoteAdjustVolumeLevel();
    }
    /**
     * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel getRemoteAdjustVolumeLevel() {
      return instance.getRemoteAdjustVolumeLevel();
    }
    /**
     * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
     */
    public Builder setRemoteAdjustVolumeLevel(com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel value) {
      copyOnWrite();
      instance.setRemoteAdjustVolumeLevel(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
     */
    public Builder setRemoteAdjustVolumeLevel(
        com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteAdjustVolumeLevel(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
     */
    public Builder mergeRemoteAdjustVolumeLevel(com.sprit.tvremote.proto.remote.RemoteAdjustVolumeLevel value) {
      copyOnWrite();
      instance.mergeRemoteAdjustVolumeLevel(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteAdjustVolumeLevel remote_adjust_volume_level = 51;</code>
     */
    public Builder clearRemoteAdjustVolumeLevel() {  copyOnWrite();
      instance.clearRemoteAdjustVolumeLevel();
      return this;
    }

    /**
     * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
     */
    @java.lang.Override
    public boolean hasRemoteSetPreferredAudioDevice() {
      return instance.hasRemoteSetPreferredAudioDevice();
    }
    /**
     * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice getRemoteSetPreferredAudioDevice() {
      return instance.getRemoteSetPreferredAudioDevice();
    }
    /**
     * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
     */
    public Builder setRemoteSetPreferredAudioDevice(com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice value) {
      copyOnWrite();
      instance.setRemoteSetPreferredAudioDevice(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
     */
    public Builder setRemoteSetPreferredAudioDevice(
        com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteSetPreferredAudioDevice(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
     */
    public Builder mergeRemoteSetPreferredAudioDevice(com.sprit.tvremote.proto.remote.RemoteSetPreferredAudioDevice value) {
      copyOnWrite();
      instance.mergeRemoteSetPreferredAudioDevice(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteSetPreferredAudioDevice remote_set_preferred_audio_device = 60;</code>
     */
    public Builder clearRemoteSetPreferredAudioDevice() {  copyOnWrite();
      instance.clearRemoteSetPreferredAudioDevice();
      return this;
    }

    /**
     * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
     */
    @java.lang.Override
    public boolean hasRemoteResetPreferredAudioDevice() {
      return instance.hasRemoteResetPreferredAudioDevice();
    }
    /**
     * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice getRemoteResetPreferredAudioDevice() {
      return instance.getRemoteResetPreferredAudioDevice();
    }
    /**
     * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
     */
    public Builder setRemoteResetPreferredAudioDevice(com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice value) {
      copyOnWrite();
      instance.setRemoteResetPreferredAudioDevice(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
     */
    public Builder setRemoteResetPreferredAudioDevice(
        com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteResetPreferredAudioDevice(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
     */
    public Builder mergeRemoteResetPreferredAudioDevice(com.sprit.tvremote.proto.remote.RemoteResetPreferredAudioDevice value) {
      copyOnWrite();
      instance.mergeRemoteResetPreferredAudioDevice(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteResetPreferredAudioDevice remote_reset_preferred_audio_device = 61;</code>
     */
    public Builder clearRemoteResetPreferredAudioDevice() {  copyOnWrite();
      instance.clearRemoteResetPreferredAudioDevice();
      return this;
    }

    /**
     * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
     */
    @java.lang.Override
    public boolean hasRemoteAppLinkLaunchRequest() {
      return instance.hasRemoteAppLinkLaunchRequest();
    }
    /**
     * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest getRemoteAppLinkLaunchRequest() {
      return instance.getRemoteAppLinkLaunchRequest();
    }
    /**
     * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
     */
    public Builder setRemoteAppLinkLaunchRequest(com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest value) {
      copyOnWrite();
      instance.setRemoteAppLinkLaunchRequest(value);
      return this;
      }
    /**
     * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
     */
    public Builder setRemoteAppLinkLaunchRequest(
        com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setRemoteAppLinkLaunchRequest(builderForValue.build());
      return this;
    }
    /**
     * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
     */
    public Builder mergeRemoteAppLinkLaunchRequest(com.sprit.tvremote.proto.remote.RemoteAppLinkLaunchRequest value) {
      copyOnWrite();
      instance.mergeRemoteAppLinkLaunchRequest(value);
      return this;
    }
    /**
     * <code>optional .remote.RemoteAppLinkLaunchRequest remote_app_link_launch_request = 90;</code>
     */
    public Builder clearRemoteAppLinkLaunchRequest() {  copyOnWrite();
      instance.clearRemoteAppLinkLaunchRequest();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteMessage)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteMessage();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "remoteConfigure_",
            "remoteSetActive_",
            "remoteError_",
            "remotePingRequest_",
            "remotePingResponse_",
            "remoteKeyInject_",
            "remoteImeKeyInject_",
            "remoteImeBatchEdit_",
            "remoteImeShowRequest_",
            "remoteVoiceBegin_",
            "remoteVoicePayload_",
            "remoteVoiceEnd_",
            "remoteStart_",
            "remoteSetVolumeLevel_",
            "remoteAdjustVolumeLevel_",
            "remoteSetPreferredAudioDevice_",
            "remoteResetPreferredAudioDevice_",
            "remoteAppLinkLaunchRequest_",
          };
          java.lang.String info =
              "\u0000\u0012\u0000\u0001\u0001Z\u0012\u0000\u0000\u0000\u0001\u1009\u0000\u0002\u1009" +
              "\u0001\u0003\u1009\u0002\b\u1009\u0003\t\u1009\u0004\n\u1009\u0005\u0014\u1009\u0006" +
              "\u0015\u1009\u0007\u0016\u1009\b\u001e\u1009\t\u001f\u1009\n \u1009\u000b(\u1009" +
              "\f2\u1009\r3\u1009\u000e<\u1009\u000f=\u1009\u0010Z\u1009\u0011";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteMessage> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteMessage.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteMessage>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteMessage)
  private static final com.sprit.tvremote.proto.remote.RemoteMessage DEFAULT_INSTANCE;
  static {
    RemoteMessage defaultInstance = new RemoteMessage();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteMessage.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteMessage> PARSER;

  public static com.google.protobuf.Parser<RemoteMessage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

