// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteImeShowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteImeShowRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
   * @return Whether the remoteTextFieldStatus field is set.
   */
  boolean hasRemoteTextFieldStatus();
  /**
   * <code>optional .remote.RemoteTextFieldStatus remote_text_field_status = 2;</code>
   * @return The remoteTextFieldStatus.
   */
  com.sprit.tvremote.proto.remote.RemoteTextFieldStatus getRemoteTextFieldStatus();
}
