// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteDeviceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteDeviceInfo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string model = 1;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>optional string model = 1;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 1;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>optional string vendor = 2;</code>
   * @return Whether the vendor field is set.
   */
  boolean hasVendor();
  /**
   * <code>optional string vendor = 2;</code>
   * @return The vendor.
   */
  java.lang.String getVendor();
  /**
   * <code>optional string vendor = 2;</code>
   * @return The bytes for vendor.
   */
  com.google.protobuf.ByteString
      getVendorBytes();

  /**
   * <code>optional int32 unknown1 = 3;</code>
   * @return Whether the unknown1 field is set.
   */
  boolean hasUnknown1();
  /**
   * <code>optional int32 unknown1 = 3;</code>
   * @return The unknown1.
   */
  int getUnknown1();

  /**
   * <code>optional string unknown2 = 4;</code>
   * @return Whether the unknown2 field is set.
   */
  boolean hasUnknown2();
  /**
   * <code>optional string unknown2 = 4;</code>
   * @return The unknown2.
   */
  java.lang.String getUnknown2();
  /**
   * <code>optional string unknown2 = 4;</code>
   * @return The bytes for unknown2.
   */
  com.google.protobuf.ByteString
      getUnknown2Bytes();

  /**
   * <code>optional string package_name = 5;</code>
   * @return Whether the packageName field is set.
   */
  boolean hasPackageName();
  /**
   * <code>optional string package_name = 5;</code>
   * @return The packageName.
   */
  java.lang.String getPackageName();
  /**
   * <code>optional string package_name = 5;</code>
   * @return The bytes for packageName.
   */
  com.google.protobuf.ByteString
      getPackageNameBytes();

  /**
   * <code>optional string app_version = 6;</code>
   * @return Whether the appVersion field is set.
   */
  boolean hasAppVersion();
  /**
   * <code>optional string app_version = 6;</code>
   * @return The appVersion.
   */
  java.lang.String getAppVersion();
  /**
   * <code>optional string app_version = 6;</code>
   * @return The bytes for appVersion.
   */
  com.google.protobuf.ByteString
      getAppVersionBytes();
}
