// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteTextFieldStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteTextFieldStatus)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 counter_field = 1;</code>
   * @return Whether the counterField field is set.
   */
  boolean hasCounterField();
  /**
   * <code>optional int32 counter_field = 1;</code>
   * @return The counterField.
   */
  int getCounterField();

  /**
   * <code>optional string value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>optional int32 start = 3;</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <code>optional int32 start = 3;</code>
   * @return The start.
   */
  int getStart();

  /**
   * <code>optional int32 end = 4;</code>
   * @return Whether the end field is set.
   */
  boolean hasEnd();
  /**
   * <code>optional int32 end = 4;</code>
   * @return The end.
   */
  int getEnd();

  /**
   * <code>optional int32 int5 = 5;</code>
   * @return Whether the int5 field is set.
   */
  boolean hasInt5();
  /**
   * <code>optional int32 int5 = 5;</code>
   * @return The int5.
   */
  int getInt5();

  /**
   * <code>optional string label = 6;</code>
   * @return Whether the label field is set.
   */
  boolean hasLabel();
  /**
   * <code>optional string label = 6;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>optional string label = 6;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();
}
