// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteVoiceBegin}
 */
@com.google.protobuf.Generated
public  final class RemoteVoiceBegin extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteVoiceBegin, RemoteVoiceBegin.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteVoiceBegin)
    RemoteVoiceBeginOrBuilder {
  private RemoteVoiceBegin() {
    packageName_ = "";
  }
  private int bitField0_;
  public static final int SESSION_ID_FIELD_NUMBER = 1;
  private int sessionId_;
  /**
   * <code>optional int32 session_id = 1;</code>
   * @return Whether the sessionId field is set.
   */
  @java.lang.Override
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public int getSessionId() {
    return sessionId_;
  }
  /**
   * <code>optional int32 session_id = 1;</code>
   * @param value The sessionId to set.
   */
  private void setSessionId(int value) {
    bitField0_ |= 0x00000001;
    sessionId_ = value;
  }
  /**
   * <code>optional int32 session_id = 1;</code>
   */
  private void clearSessionId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    sessionId_ = 0;
  }

  public static final int PACKAGE_NAME_FIELD_NUMBER = 2;
  private java.lang.String packageName_;
  /**
   * <code>optional string package_name = 2;</code>
   * @return Whether the packageName field is set.
   */
  @java.lang.Override
  public boolean hasPackageName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string package_name = 2;</code>
   * @return The packageName.
   */
  @java.lang.Override
  public java.lang.String getPackageName() {
    return packageName_;
  }
  /**
   * <code>optional string package_name = 2;</code>
   * @return The bytes for packageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(packageName_);
  }
  /**
   * <code>optional string package_name = 2;</code>
   * @param value The packageName to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPackageName(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000002;
    packageName_ = value;
  }
  /**
   * <code>optional string package_name = 2;</code>
   */
  private void clearPackageName() {
    bitField0_ = (bitField0_ & ~0x00000002);
    packageName_ = getDefaultInstance().getPackageName();
  }
  /**
   * <code>optional string package_name = 2;</code>
   * @param value The bytes for packageName to set.
   */
  private void setPackageNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    packageName_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteVoiceBegin prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteVoiceBegin}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteVoiceBegin, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteVoiceBegin)
      com.sprit.tvremote.proto.remote.RemoteVoiceBeginOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteVoiceBegin.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 session_id = 1;</code>
     * @return Whether the sessionId field is set.
     */
    @java.lang.Override
    public boolean hasSessionId() {
      return instance.hasSessionId();
    }
    /**
     * <code>optional int32 session_id = 1;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public int getSessionId() {
      return instance.getSessionId();
    }
    /**
     * <code>optional int32 session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(int value) {
      copyOnWrite();
      instance.setSessionId(value);
      return this;
    }
    /**
     * <code>optional int32 session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      copyOnWrite();
      instance.clearSessionId();
      return this;
    }

    /**
     * <code>optional string package_name = 2;</code>
     * @return Whether the packageName field is set.
     */
    @java.lang.Override
    public boolean hasPackageName() {
      return instance.hasPackageName();
    }
    /**
     * <code>optional string package_name = 2;</code>
     * @return The packageName.
     */
    @java.lang.Override
    public java.lang.String getPackageName() {
      return instance.getPackageName();
    }
    /**
     * <code>optional string package_name = 2;</code>
     * @return The bytes for packageName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      return instance.getPackageNameBytes();
    }
    /**
     * <code>optional string package_name = 2;</code>
     * @param value The packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageName(
        java.lang.String value) {
      copyOnWrite();
      instance.setPackageName(value);
      return this;
    }
    /**
     * <code>optional string package_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageName() {
      copyOnWrite();
      instance.clearPackageName();
      return this;
    }
    /**
     * <code>optional string package_name = 2;</code>
     * @param value The bytes for packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPackageNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteVoiceBegin)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteVoiceBegin();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "sessionId_",
            "packageName_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1004\u0000\u0002" +
              "\u1208\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteVoiceBegin> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteVoiceBegin.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteVoiceBegin>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteVoiceBegin)
  private static final com.sprit.tvremote.proto.remote.RemoteVoiceBegin DEFAULT_INSTANCE;
  static {
    RemoteVoiceBegin defaultInstance = new RemoteVoiceBegin();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteVoiceBegin.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteVoiceBegin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteVoiceBegin> PARSER;

  public static com.google.protobuf.Parser<RemoteVoiceBegin> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

