// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemotePingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemotePingRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 val1 = 1;</code>
   * @return Whether the val1 field is set.
   */
  boolean hasVal1();
  /**
   * <code>optional int32 val1 = 1;</code>
   * @return The val1.
   */
  int getVal1();

  /**
   * <code>optional int32 val2 = 2;</code>
   * @return Whether the val2 field is set.
   */
  boolean hasVal2();
  /**
   * <code>optional int32 val2 = 2;</code>
   * @return The val2.
   */
  int getVal2();
}
