// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf type {@code remote.RemoteImeObject}
 */
@com.google.protobuf.Generated
public  final class RemoteImeObject extends
    com.google.protobuf.GeneratedMessageLite<
        RemoteImeObject, RemoteImeObject.Builder> implements
    // @@protoc_insertion_point(message_implements:remote.RemoteImeObject)
    RemoteImeObjectOrBuilder {
  private RemoteImeObject() {
    value_ = "";
  }
  private int bitField0_;
  public static final int START_FIELD_NUMBER = 1;
  private int start_;
  /**
   * <code>optional int32 start = 1;</code>
   * @return Whether the start field is set.
   */
  @java.lang.Override
  public boolean hasStart() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 start = 1;</code>
   * @return The start.
   */
  @java.lang.Override
  public int getStart() {
    return start_;
  }
  /**
   * <code>optional int32 start = 1;</code>
   * @param value The start to set.
   */
  private void setStart(int value) {
    bitField0_ |= 0x00000001;
    start_ = value;
  }
  /**
   * <code>optional int32 start = 1;</code>
   */
  private void clearStart() {
    bitField0_ = (bitField0_ & ~0x00000001);
    start_ = 0;
  }

  public static final int END_FIELD_NUMBER = 2;
  private int end_;
  /**
   * <code>optional int32 end = 2;</code>
   * @return Whether the end field is set.
   */
  @java.lang.Override
  public boolean hasEnd() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 end = 2;</code>
   * @return The end.
   */
  @java.lang.Override
  public int getEnd() {
    return end_;
  }
  /**
   * <code>optional int32 end = 2;</code>
   * @param value The end to set.
   */
  private void setEnd(int value) {
    bitField0_ |= 0x00000002;
    end_ = value;
  }
  /**
   * <code>optional int32 end = 2;</code>
   */
  private void clearEnd() {
    bitField0_ = (bitField0_ & ~0x00000002);
    end_ = 0;
  }

  public static final int VALUE_FIELD_NUMBER = 3;
  private java.lang.String value_;
  /**
   * <code>optional string value = 3;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string value = 3;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    return value_;
  }
  /**
   * <code>optional string value = 3;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(value_);
  }
  /**
   * <code>optional string value = 3;</code>
   * @param value The value to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setValue(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000004;
    value_ = value;
  }
  /**
   * <code>optional string value = 3;</code>
   */
  private void clearValue() {
    bitField0_ = (bitField0_ & ~0x00000004);
    value_ = getDefaultInstance().getValue();
  }
  /**
   * <code>optional string value = 3;</code>
   * @param value The bytes for value to set.
   */
  private void setValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    value_ = value.toStringUtf8();
    bitField0_ |= 0x00000004;
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.remote.RemoteImeObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.remote.RemoteImeObject prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code remote.RemoteImeObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.remote.RemoteImeObject, Builder> implements
      // @@protoc_insertion_point(builder_implements:remote.RemoteImeObject)
      com.sprit.tvremote.proto.remote.RemoteImeObjectOrBuilder {
    // Construct using com.sprit.tvremote.proto.remote.RemoteImeObject.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 start = 1;</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return instance.hasStart();
    }
    /**
     * <code>optional int32 start = 1;</code>
     * @return The start.
     */
    @java.lang.Override
    public int getStart() {
      return instance.getStart();
    }
    /**
     * <code>optional int32 start = 1;</code>
     * @param value The start to set.
     * @return This builder for chaining.
     */
    public Builder setStart(int value) {
      copyOnWrite();
      instance.setStart(value);
      return this;
    }
    /**
     * <code>optional int32 start = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStart() {
      copyOnWrite();
      instance.clearStart();
      return this;
    }

    /**
     * <code>optional int32 end = 2;</code>
     * @return Whether the end field is set.
     */
    @java.lang.Override
    public boolean hasEnd() {
      return instance.hasEnd();
    }
    /**
     * <code>optional int32 end = 2;</code>
     * @return The end.
     */
    @java.lang.Override
    public int getEnd() {
      return instance.getEnd();
    }
    /**
     * <code>optional int32 end = 2;</code>
     * @param value The end to set.
     * @return This builder for chaining.
     */
    public Builder setEnd(int value) {
      copyOnWrite();
      instance.setEnd(value);
      return this;
    }
    /**
     * <code>optional int32 end = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnd() {
      copyOnWrite();
      instance.clearEnd();
      return this;
    }

    /**
     * <code>optional string value = 3;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return instance.hasValue();
    }
    /**
     * <code>optional string value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      return instance.getValue();
    }
    /**
     * <code>optional string value = 3;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return instance.getValueBytes();
    }
    /**
     * <code>optional string value = 3;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
    }
    /**
     * <code>optional string value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }
    /**
     * <code>optional string value = 3;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValueBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:remote.RemoteImeObject)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.remote.RemoteImeObject();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "start_",
            "end_",
            "value_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1004\u0000\u0002" +
              "\u1004\u0001\u0003\u1208\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.remote.RemoteImeObject> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.remote.RemoteImeObject.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.remote.RemoteImeObject>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:remote.RemoteImeObject)
  private static final com.sprit.tvremote.proto.remote.RemoteImeObject DEFAULT_INSTANCE;
  static {
    RemoteImeObject defaultInstance = new RemoteImeObject();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoteImeObject.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.remote.RemoteImeObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoteImeObject> PARSER;

  public static com.google.protobuf.Parser<RemoteImeObject> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

