// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

@com.google.protobuf.Generated
public interface RemoteConfigureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:remote.RemoteConfigure)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 code1 = 1;</code>
   * @return Whether the code1 field is set.
   */
  boolean hasCode1();
  /**
   * <code>optional int32 code1 = 1;</code>
   * @return The code1.
   */
  int getCode1();

  /**
   * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
   * @return Whether the deviceInfo field is set.
   */
  boolean hasDeviceInfo();
  /**
   * <code>optional .remote.RemoteDeviceInfo device_info = 2;</code>
   * @return The deviceInfo.
   */
  com.sprit.tvremote.proto.remote.RemoteDeviceInfo getDeviceInfo();
}
