// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: remotemessage.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.remote;

/**
 * Protobuf enum {@code remote.RemoteKeyCode}
 */
@com.google.protobuf.Generated
public enum RemoteKeyCode
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>KEYCODE_UNKNOWN = 0;</code>
   */
  KEYCODE_UNKNOWN(0),
  /**
   * <code>KEYCODE_SOFT_LEFT = 1;</code>
   */
  KEYCODE_SOFT_LEFT(1),
  /**
   * <code>KEYCODE_SOFT_RIGHT = 2;</code>
   */
  KEYCODE_SOFT_RIGHT(2),
  /**
   * <code>KEYCODE_HOME = 3;</code>
   */
  KEYCODE_HOME(3),
  /**
   * <code>KEYCODE_BACK = 4;</code>
   */
  KEYCODE_BACK(4),
  /**
   * <code>KEYCODE_CALL = 5;</code>
   */
  KEYCODE_CALL(5),
  /**
   * <code>KEYCODE_ENDCALL = 6;</code>
   */
  KEYCODE_ENDCALL(6),
  /**
   * <code>KEYCODE_0 = 7;</code>
   */
  KEYCODE_0(7),
  /**
   * <code>KEYCODE_1 = 8;</code>
   */
  KEYCODE_1(8),
  /**
   * <code>KEYCODE_2 = 9;</code>
   */
  KEYCODE_2(9),
  /**
   * <code>KEYCODE_3 = 10;</code>
   */
  KEYCODE_3(10),
  /**
   * <code>KEYCODE_4 = 11;</code>
   */
  KEYCODE_4(11),
  /**
   * <code>KEYCODE_5 = 12;</code>
   */
  KEYCODE_5(12),
  /**
   * <code>KEYCODE_6 = 13;</code>
   */
  KEYCODE_6(13),
  /**
   * <code>KEYCODE_7 = 14;</code>
   */
  KEYCODE_7(14),
  /**
   * <code>KEYCODE_8 = 15;</code>
   */
  KEYCODE_8(15),
  /**
   * <code>KEYCODE_9 = 16;</code>
   */
  KEYCODE_9(16),
  /**
   * <code>KEYCODE_STAR = 17;</code>
   */
  KEYCODE_STAR(17),
  /**
   * <code>KEYCODE_POUND = 18;</code>
   */
  KEYCODE_POUND(18),
  /**
   * <code>KEYCODE_DPAD_UP = 19;</code>
   */
  KEYCODE_DPAD_UP(19),
  /**
   * <code>KEYCODE_DPAD_DOWN = 20;</code>
   */
  KEYCODE_DPAD_DOWN(20),
  /**
   * <code>KEYCODE_DPAD_LEFT = 21;</code>
   */
  KEYCODE_DPAD_LEFT(21),
  /**
   * <code>KEYCODE_DPAD_RIGHT = 22;</code>
   */
  KEYCODE_DPAD_RIGHT(22),
  /**
   * <code>KEYCODE_DPAD_CENTER = 23;</code>
   */
  KEYCODE_DPAD_CENTER(23),
  /**
   * <code>KEYCODE_VOLUME_UP = 24;</code>
   */
  KEYCODE_VOLUME_UP(24),
  /**
   * <code>KEYCODE_VOLUME_DOWN = 25;</code>
   */
  KEYCODE_VOLUME_DOWN(25),
  /**
   * <code>KEYCODE_POWER = 26;</code>
   */
  KEYCODE_POWER(26),
  /**
   * <code>KEYCODE_CAMERA = 27;</code>
   */
  KEYCODE_CAMERA(27),
  /**
   * <code>KEYCODE_CLEAR = 28;</code>
   */
  KEYCODE_CLEAR(28),
  /**
   * <code>KEYCODE_A = 29;</code>
   */
  KEYCODE_A(29),
  /**
   * <code>KEYCODE_B = 30;</code>
   */
  KEYCODE_B(30),
  /**
   * <code>KEYCODE_C = 31;</code>
   */
  KEYCODE_C(31),
  /**
   * <code>KEYCODE_D = 32;</code>
   */
  KEYCODE_D(32),
  /**
   * <code>KEYCODE_E = 33;</code>
   */
  KEYCODE_E(33),
  /**
   * <code>KEYCODE_F = 34;</code>
   */
  KEYCODE_F(34),
  /**
   * <code>KEYCODE_G = 35;</code>
   */
  KEYCODE_G(35),
  /**
   * <code>KEYCODE_H = 36;</code>
   */
  KEYCODE_H(36),
  /**
   * <code>KEYCODE_I = 37;</code>
   */
  KEYCODE_I(37),
  /**
   * <code>KEYCODE_J = 38;</code>
   */
  KEYCODE_J(38),
  /**
   * <code>KEYCODE_K = 39;</code>
   */
  KEYCODE_K(39),
  /**
   * <code>KEYCODE_L = 40;</code>
   */
  KEYCODE_L(40),
  /**
   * <code>KEYCODE_M = 41;</code>
   */
  KEYCODE_M(41),
  /**
   * <code>KEYCODE_N = 42;</code>
   */
  KEYCODE_N(42),
  /**
   * <code>KEYCODE_O = 43;</code>
   */
  KEYCODE_O(43),
  /**
   * <code>KEYCODE_P = 44;</code>
   */
  KEYCODE_P(44),
  /**
   * <code>KEYCODE_Q = 45;</code>
   */
  KEYCODE_Q(45),
  /**
   * <code>KEYCODE_R = 46;</code>
   */
  KEYCODE_R(46),
  /**
   * <code>KEYCODE_S = 47;</code>
   */
  KEYCODE_S(47),
  /**
   * <code>KEYCODE_T = 48;</code>
   */
  KEYCODE_T(48),
  /**
   * <code>KEYCODE_U = 49;</code>
   */
  KEYCODE_U(49),
  /**
   * <code>KEYCODE_V = 50;</code>
   */
  KEYCODE_V(50),
  /**
   * <code>KEYCODE_W = 51;</code>
   */
  KEYCODE_W(51),
  /**
   * <code>KEYCODE_X = 52;</code>
   */
  KEYCODE_X(52),
  /**
   * <code>KEYCODE_Y = 53;</code>
   */
  KEYCODE_Y(53),
  /**
   * <code>KEYCODE_Z = 54;</code>
   */
  KEYCODE_Z(54),
  /**
   * <code>KEYCODE_COMMA = 55;</code>
   */
  KEYCODE_COMMA(55),
  /**
   * <code>KEYCODE_PERIOD = 56;</code>
   */
  KEYCODE_PERIOD(56),
  /**
   * <code>KEYCODE_ALT_LEFT = 57;</code>
   */
  KEYCODE_ALT_LEFT(57),
  /**
   * <code>KEYCODE_ALT_RIGHT = 58;</code>
   */
  KEYCODE_ALT_RIGHT(58),
  /**
   * <code>KEYCODE_SHIFT_LEFT = 59;</code>
   */
  KEYCODE_SHIFT_LEFT(59),
  /**
   * <code>KEYCODE_SHIFT_RIGHT = 60;</code>
   */
  KEYCODE_SHIFT_RIGHT(60),
  /**
   * <code>KEYCODE_TAB = 61;</code>
   */
  KEYCODE_TAB(61),
  /**
   * <code>KEYCODE_SPACE = 62;</code>
   */
  KEYCODE_SPACE(62),
  /**
   * <code>KEYCODE_SYM = 63;</code>
   */
  KEYCODE_SYM(63),
  /**
   * <code>KEYCODE_EXPLORER = 64;</code>
   */
  KEYCODE_EXPLORER(64),
  /**
   * <code>KEYCODE_ENVELOPE = 65;</code>
   */
  KEYCODE_ENVELOPE(65),
  /**
   * <code>KEYCODE_ENTER = 66;</code>
   */
  KEYCODE_ENTER(66),
  /**
   * <code>KEYCODE_DEL = 67;</code>
   */
  KEYCODE_DEL(67),
  /**
   * <code>KEYCODE_GRAVE = 68;</code>
   */
  KEYCODE_GRAVE(68),
  /**
   * <code>KEYCODE_MINUS = 69;</code>
   */
  KEYCODE_MINUS(69),
  /**
   * <code>KEYCODE_EQUALS = 70;</code>
   */
  KEYCODE_EQUALS(70),
  /**
   * <code>KEYCODE_LEFT_BRACKET = 71;</code>
   */
  KEYCODE_LEFT_BRACKET(71),
  /**
   * <code>KEYCODE_RIGHT_BRACKET = 72;</code>
   */
  KEYCODE_RIGHT_BRACKET(72),
  /**
   * <code>KEYCODE_BACKSLASH = 73;</code>
   */
  KEYCODE_BACKSLASH(73),
  /**
   * <code>KEYCODE_SEMICOLON = 74;</code>
   */
  KEYCODE_SEMICOLON(74),
  /**
   * <code>KEYCODE_APOSTROPHE = 75;</code>
   */
  KEYCODE_APOSTROPHE(75),
  /**
   * <code>KEYCODE_SLASH = 76;</code>
   */
  KEYCODE_SLASH(76),
  /**
   * <code>KEYCODE_AT = 77;</code>
   */
  KEYCODE_AT(77),
  /**
   * <code>KEYCODE_NUM = 78;</code>
   */
  KEYCODE_NUM(78),
  /**
   * <code>KEYCODE_HEADSETHOOK = 79;</code>
   */
  KEYCODE_HEADSETHOOK(79),
  /**
   * <code>KEYCODE_FOCUS = 80;</code>
   */
  KEYCODE_FOCUS(80),
  /**
   * <code>KEYCODE_PLUS = 81;</code>
   */
  KEYCODE_PLUS(81),
  /**
   * <code>KEYCODE_MENU = 82;</code>
   */
  KEYCODE_MENU(82),
  /**
   * <code>KEYCODE_NOTIFICATION = 83;</code>
   */
  KEYCODE_NOTIFICATION(83),
  /**
   * <code>KEYCODE_SEARCH = 84;</code>
   */
  KEYCODE_SEARCH(84),
  /**
   * <code>KEYCODE_MEDIA_PLAY_PAUSE = 85;</code>
   */
  KEYCODE_MEDIA_PLAY_PAUSE(85),
  /**
   * <code>KEYCODE_MEDIA_STOP = 86;</code>
   */
  KEYCODE_MEDIA_STOP(86),
  /**
   * <code>KEYCODE_MEDIA_NEXT = 87;</code>
   */
  KEYCODE_MEDIA_NEXT(87),
  /**
   * <code>KEYCODE_MEDIA_PREVIOUS = 88;</code>
   */
  KEYCODE_MEDIA_PREVIOUS(88),
  /**
   * <code>KEYCODE_MEDIA_REWIND = 89;</code>
   */
  KEYCODE_MEDIA_REWIND(89),
  /**
   * <code>KEYCODE_MEDIA_FAST_FORWARD = 90;</code>
   */
  KEYCODE_MEDIA_FAST_FORWARD(90),
  /**
   * <code>KEYCODE_MUTE = 91;</code>
   */
  KEYCODE_MUTE(91),
  /**
   * <code>KEYCODE_PAGE_UP = 92;</code>
   */
  KEYCODE_PAGE_UP(92),
  /**
   * <code>KEYCODE_PAGE_DOWN = 93;</code>
   */
  KEYCODE_PAGE_DOWN(93),
  /**
   * <code>KEYCODE_PICTSYMBOLS = 94;</code>
   */
  KEYCODE_PICTSYMBOLS(94),
  /**
   * <code>KEYCODE_SWITCH_CHARSET = 95;</code>
   */
  KEYCODE_SWITCH_CHARSET(95),
  /**
   * <code>KEYCODE_BUTTON_A = 96;</code>
   */
  KEYCODE_BUTTON_A(96),
  /**
   * <code>KEYCODE_BUTTON_B = 97;</code>
   */
  KEYCODE_BUTTON_B(97),
  /**
   * <code>KEYCODE_BUTTON_C = 98;</code>
   */
  KEYCODE_BUTTON_C(98),
  /**
   * <code>KEYCODE_BUTTON_X = 99;</code>
   */
  KEYCODE_BUTTON_X(99),
  /**
   * <code>KEYCODE_BUTTON_Y = 100;</code>
   */
  KEYCODE_BUTTON_Y(100),
  /**
   * <code>KEYCODE_BUTTON_Z = 101;</code>
   */
  KEYCODE_BUTTON_Z(101),
  /**
   * <code>KEYCODE_BUTTON_L1 = 102;</code>
   */
  KEYCODE_BUTTON_L1(102),
  /**
   * <code>KEYCODE_BUTTON_R1 = 103;</code>
   */
  KEYCODE_BUTTON_R1(103),
  /**
   * <code>KEYCODE_BUTTON_L2 = 104;</code>
   */
  KEYCODE_BUTTON_L2(104),
  /**
   * <code>KEYCODE_BUTTON_R2 = 105;</code>
   */
  KEYCODE_BUTTON_R2(105),
  /**
   * <code>KEYCODE_BUTTON_THUMBL = 106;</code>
   */
  KEYCODE_BUTTON_THUMBL(106),
  /**
   * <code>KEYCODE_BUTTON_THUMBR = 107;</code>
   */
  KEYCODE_BUTTON_THUMBR(107),
  /**
   * <code>KEYCODE_BUTTON_START = 108;</code>
   */
  KEYCODE_BUTTON_START(108),
  /**
   * <code>KEYCODE_BUTTON_SELECT = 109;</code>
   */
  KEYCODE_BUTTON_SELECT(109),
  /**
   * <code>KEYCODE_BUTTON_MODE = 110;</code>
   */
  KEYCODE_BUTTON_MODE(110),
  /**
   * <code>KEYCODE_ESCAPE = 111;</code>
   */
  KEYCODE_ESCAPE(111),
  /**
   * <code>KEYCODE_FORWARD_DEL = 112;</code>
   */
  KEYCODE_FORWARD_DEL(112),
  /**
   * <code>KEYCODE_CTRL_LEFT = 113;</code>
   */
  KEYCODE_CTRL_LEFT(113),
  /**
   * <code>KEYCODE_CTRL_RIGHT = 114;</code>
   */
  KEYCODE_CTRL_RIGHT(114),
  /**
   * <code>KEYCODE_CAPS_LOCK = 115;</code>
   */
  KEYCODE_CAPS_LOCK(115),
  /**
   * <code>KEYCODE_SCROLL_LOCK = 116;</code>
   */
  KEYCODE_SCROLL_LOCK(116),
  /**
   * <code>KEYCODE_META_LEFT = 117;</code>
   */
  KEYCODE_META_LEFT(117),
  /**
   * <code>KEYCODE_META_RIGHT = 118;</code>
   */
  KEYCODE_META_RIGHT(118),
  /**
   * <code>KEYCODE_FUNCTION = 119;</code>
   */
  KEYCODE_FUNCTION(119),
  /**
   * <code>KEYCODE_SYSRQ = 120;</code>
   */
  KEYCODE_SYSRQ(120),
  /**
   * <code>KEYCODE_BREAK = 121;</code>
   */
  KEYCODE_BREAK(121),
  /**
   * <code>KEYCODE_MOVE_HOME = 122;</code>
   */
  KEYCODE_MOVE_HOME(122),
  /**
   * <code>KEYCODE_MOVE_END = 123;</code>
   */
  KEYCODE_MOVE_END(123),
  /**
   * <code>KEYCODE_INSERT = 124;</code>
   */
  KEYCODE_INSERT(124),
  /**
   * <code>KEYCODE_FORWARD = 125;</code>
   */
  KEYCODE_FORWARD(125),
  /**
   * <code>KEYCODE_MEDIA_PLAY = 126;</code>
   */
  KEYCODE_MEDIA_PLAY(126),
  /**
   * <code>KEYCODE_MEDIA_PAUSE = 127;</code>
   */
  KEYCODE_MEDIA_PAUSE(127),
  /**
   * <code>KEYCODE_MEDIA_CLOSE = 128;</code>
   */
  KEYCODE_MEDIA_CLOSE(128),
  /**
   * <code>KEYCODE_MEDIA_EJECT = 129;</code>
   */
  KEYCODE_MEDIA_EJECT(129),
  /**
   * <code>KEYCODE_MEDIA_RECORD = 130;</code>
   */
  KEYCODE_MEDIA_RECORD(130),
  /**
   * <code>KEYCODE_F1 = 131;</code>
   */
  KEYCODE_F1(131),
  /**
   * <code>KEYCODE_F2 = 132;</code>
   */
  KEYCODE_F2(132),
  /**
   * <code>KEYCODE_F3 = 133;</code>
   */
  KEYCODE_F3(133),
  /**
   * <code>KEYCODE_F4 = 134;</code>
   */
  KEYCODE_F4(134),
  /**
   * <code>KEYCODE_F5 = 135;</code>
   */
  KEYCODE_F5(135),
  /**
   * <code>KEYCODE_F6 = 136;</code>
   */
  KEYCODE_F6(136),
  /**
   * <code>KEYCODE_F7 = 137;</code>
   */
  KEYCODE_F7(137),
  /**
   * <code>KEYCODE_F8 = 138;</code>
   */
  KEYCODE_F8(138),
  /**
   * <code>KEYCODE_F9 = 139;</code>
   */
  KEYCODE_F9(139),
  /**
   * <code>KEYCODE_F10 = 140;</code>
   */
  KEYCODE_F10(140),
  /**
   * <code>KEYCODE_F11 = 141;</code>
   */
  KEYCODE_F11(141),
  /**
   * <code>KEYCODE_F12 = 142;</code>
   */
  KEYCODE_F12(142),
  /**
   * <code>KEYCODE_NUM_LOCK = 143;</code>
   */
  KEYCODE_NUM_LOCK(143),
  /**
   * <code>KEYCODE_NUMPAD_0 = 144;</code>
   */
  KEYCODE_NUMPAD_0(144),
  /**
   * <code>KEYCODE_NUMPAD_1 = 145;</code>
   */
  KEYCODE_NUMPAD_1(145),
  /**
   * <code>KEYCODE_NUMPAD_2 = 146;</code>
   */
  KEYCODE_NUMPAD_2(146),
  /**
   * <code>KEYCODE_NUMPAD_3 = 147;</code>
   */
  KEYCODE_NUMPAD_3(147),
  /**
   * <code>KEYCODE_NUMPAD_4 = 148;</code>
   */
  KEYCODE_NUMPAD_4(148),
  /**
   * <code>KEYCODE_NUMPAD_5 = 149;</code>
   */
  KEYCODE_NUMPAD_5(149),
  /**
   * <code>KEYCODE_NUMPAD_6 = 150;</code>
   */
  KEYCODE_NUMPAD_6(150),
  /**
   * <code>KEYCODE_NUMPAD_7 = 151;</code>
   */
  KEYCODE_NUMPAD_7(151),
  /**
   * <code>KEYCODE_NUMPAD_8 = 152;</code>
   */
  KEYCODE_NUMPAD_8(152),
  /**
   * <code>KEYCODE_NUMPAD_9 = 153;</code>
   */
  KEYCODE_NUMPAD_9(153),
  /**
   * <code>KEYCODE_NUMPAD_DIVIDE = 154;</code>
   */
  KEYCODE_NUMPAD_DIVIDE(154),
  /**
   * <code>KEYCODE_NUMPAD_MULTIPLY = 155;</code>
   */
  KEYCODE_NUMPAD_MULTIPLY(155),
  /**
   * <code>KEYCODE_NUMPAD_SUBTRACT = 156;</code>
   */
  KEYCODE_NUMPAD_SUBTRACT(156),
  /**
   * <code>KEYCODE_NUMPAD_ADD = 157;</code>
   */
  KEYCODE_NUMPAD_ADD(157),
  /**
   * <code>KEYCODE_NUMPAD_DOT = 158;</code>
   */
  KEYCODE_NUMPAD_DOT(158),
  /**
   * <code>KEYCODE_NUMPAD_COMMA = 159;</code>
   */
  KEYCODE_NUMPAD_COMMA(159),
  /**
   * <code>KEYCODE_NUMPAD_ENTER = 160;</code>
   */
  KEYCODE_NUMPAD_ENTER(160),
  /**
   * <code>KEYCODE_NUMPAD_EQUALS = 161;</code>
   */
  KEYCODE_NUMPAD_EQUALS(161),
  /**
   * <code>KEYCODE_NUMPAD_LEFT_PAREN = 162;</code>
   */
  KEYCODE_NUMPAD_LEFT_PAREN(162),
  /**
   * <code>KEYCODE_NUMPAD_RIGHT_PAREN = 163;</code>
   */
  KEYCODE_NUMPAD_RIGHT_PAREN(163),
  /**
   * <code>KEYCODE_VOLUME_MUTE = 164;</code>
   */
  KEYCODE_VOLUME_MUTE(164),
  /**
   * <code>KEYCODE_INFO = 165;</code>
   */
  KEYCODE_INFO(165),
  /**
   * <code>KEYCODE_CHANNEL_UP = 166;</code>
   */
  KEYCODE_CHANNEL_UP(166),
  /**
   * <code>KEYCODE_CHANNEL_DOWN = 167;</code>
   */
  KEYCODE_CHANNEL_DOWN(167),
  /**
   * <code>KEYCODE_ZOOM_IN = 168;</code>
   */
  KEYCODE_ZOOM_IN(168),
  /**
   * <code>KEYCODE_ZOOM_OUT = 169;</code>
   */
  KEYCODE_ZOOM_OUT(169),
  /**
   * <code>KEYCODE_TV = 170;</code>
   */
  KEYCODE_TV(170),
  /**
   * <code>KEYCODE_WINDOW = 171;</code>
   */
  KEYCODE_WINDOW(171),
  /**
   * <code>KEYCODE_GUIDE = 172;</code>
   */
  KEYCODE_GUIDE(172),
  /**
   * <code>KEYCODE_DVR = 173;</code>
   */
  KEYCODE_DVR(173),
  /**
   * <code>KEYCODE_BOOKMARK = 174;</code>
   */
  KEYCODE_BOOKMARK(174),
  /**
   * <code>KEYCODE_CAPTIONS = 175;</code>
   */
  KEYCODE_CAPTIONS(175),
  /**
   * <code>KEYCODE_SETTINGS = 176;</code>
   */
  KEYCODE_SETTINGS(176),
  /**
   * <code>KEYCODE_TV_POWER = 177;</code>
   */
  KEYCODE_TV_POWER(177),
  /**
   * <code>KEYCODE_TV_INPUT = 178;</code>
   */
  KEYCODE_TV_INPUT(178),
  /**
   * <code>KEYCODE_STB_POWER = 179;</code>
   */
  KEYCODE_STB_POWER(179),
  /**
   * <code>KEYCODE_STB_INPUT = 180;</code>
   */
  KEYCODE_STB_INPUT(180),
  /**
   * <code>KEYCODE_AVR_POWER = 181;</code>
   */
  KEYCODE_AVR_POWER(181),
  /**
   * <code>KEYCODE_AVR_INPUT = 182;</code>
   */
  KEYCODE_AVR_INPUT(182),
  /**
   * <code>KEYCODE_PROG_RED = 183;</code>
   */
  KEYCODE_PROG_RED(183),
  /**
   * <code>KEYCODE_PROG_GREEN = 184;</code>
   */
  KEYCODE_PROG_GREEN(184),
  /**
   * <code>KEYCODE_PROG_YELLOW = 185;</code>
   */
  KEYCODE_PROG_YELLOW(185),
  /**
   * <code>KEYCODE_PROG_BLUE = 186;</code>
   */
  KEYCODE_PROG_BLUE(186),
  /**
   * <code>KEYCODE_APP_SWITCH = 187;</code>
   */
  KEYCODE_APP_SWITCH(187),
  /**
   * <code>KEYCODE_BUTTON_1 = 188;</code>
   */
  KEYCODE_BUTTON_1(188),
  /**
   * <code>KEYCODE_BUTTON_2 = 189;</code>
   */
  KEYCODE_BUTTON_2(189),
  /**
   * <code>KEYCODE_BUTTON_3 = 190;</code>
   */
  KEYCODE_BUTTON_3(190),
  /**
   * <code>KEYCODE_BUTTON_4 = 191;</code>
   */
  KEYCODE_BUTTON_4(191),
  /**
   * <code>KEYCODE_BUTTON_5 = 192;</code>
   */
  KEYCODE_BUTTON_5(192),
  /**
   * <code>KEYCODE_BUTTON_6 = 193;</code>
   */
  KEYCODE_BUTTON_6(193),
  /**
   * <code>KEYCODE_BUTTON_7 = 194;</code>
   */
  KEYCODE_BUTTON_7(194),
  /**
   * <code>KEYCODE_BUTTON_8 = 195;</code>
   */
  KEYCODE_BUTTON_8(195),
  /**
   * <code>KEYCODE_BUTTON_9 = 196;</code>
   */
  KEYCODE_BUTTON_9(196),
  /**
   * <code>KEYCODE_BUTTON_10 = 197;</code>
   */
  KEYCODE_BUTTON_10(197),
  /**
   * <code>KEYCODE_BUTTON_11 = 198;</code>
   */
  KEYCODE_BUTTON_11(198),
  /**
   * <code>KEYCODE_BUTTON_12 = 199;</code>
   */
  KEYCODE_BUTTON_12(199),
  /**
   * <code>KEYCODE_BUTTON_13 = 200;</code>
   */
  KEYCODE_BUTTON_13(200),
  /**
   * <code>KEYCODE_BUTTON_14 = 201;</code>
   */
  KEYCODE_BUTTON_14(201),
  /**
   * <code>KEYCODE_BUTTON_15 = 202;</code>
   */
  KEYCODE_BUTTON_15(202),
  /**
   * <code>KEYCODE_BUTTON_16 = 203;</code>
   */
  KEYCODE_BUTTON_16(203),
  /**
   * <code>KEYCODE_LANGUAGE_SWITCH = 204;</code>
   */
  KEYCODE_LANGUAGE_SWITCH(204),
  /**
   * <code>KEYCODE_MANNER_MODE = 205;</code>
   */
  KEYCODE_MANNER_MODE(205),
  /**
   * <code>KEYCODE_3D_MODE = 206;</code>
   */
  KEYCODE_3D_MODE(206),
  /**
   * <code>KEYCODE_CONTACTS = 207;</code>
   */
  KEYCODE_CONTACTS(207),
  /**
   * <code>KEYCODE_CALENDAR = 208;</code>
   */
  KEYCODE_CALENDAR(208),
  /**
   * <code>KEYCODE_MUSIC = 209;</code>
   */
  KEYCODE_MUSIC(209),
  /**
   * <code>KEYCODE_CALCULATOR = 210;</code>
   */
  KEYCODE_CALCULATOR(210),
  /**
   * <code>KEYCODE_ZENKAKU_HANKAKU = 211;</code>
   */
  KEYCODE_ZENKAKU_HANKAKU(211),
  /**
   * <code>KEYCODE_EISU = 212;</code>
   */
  KEYCODE_EISU(212),
  /**
   * <code>KEYCODE_MUHENKAN = 213;</code>
   */
  KEYCODE_MUHENKAN(213),
  /**
   * <code>KEYCODE_HENKAN = 214;</code>
   */
  KEYCODE_HENKAN(214),
  /**
   * <code>KEYCODE_KATAKANA_HIRAGANA = 215;</code>
   */
  KEYCODE_KATAKANA_HIRAGANA(215),
  /**
   * <code>KEYCODE_YEN = 216;</code>
   */
  KEYCODE_YEN(216),
  /**
   * <code>KEYCODE_RO = 217;</code>
   */
  KEYCODE_RO(217),
  /**
   * <code>KEYCODE_KANA = 218;</code>
   */
  KEYCODE_KANA(218),
  /**
   * <code>KEYCODE_ASSIST = 219;</code>
   */
  KEYCODE_ASSIST(219),
  /**
   * <code>KEYCODE_BRIGHTNESS_DOWN = 220;</code>
   */
  KEYCODE_BRIGHTNESS_DOWN(220),
  /**
   * <code>KEYCODE_BRIGHTNESS_UP = 221;</code>
   */
  KEYCODE_BRIGHTNESS_UP(221),
  /**
   * <code>KEYCODE_MEDIA_AUDIO_TRACK = 222;</code>
   */
  KEYCODE_MEDIA_AUDIO_TRACK(222),
  /**
   * <code>KEYCODE_SLEEP = 223;</code>
   */
  KEYCODE_SLEEP(223),
  /**
   * <code>KEYCODE_WAKEUP = 224;</code>
   */
  KEYCODE_WAKEUP(224),
  /**
   * <code>KEYCODE_PAIRING = 225;</code>
   */
  KEYCODE_PAIRING(225),
  /**
   * <code>KEYCODE_MEDIA_TOP_MENU = 226;</code>
   */
  KEYCODE_MEDIA_TOP_MENU(226),
  /**
   * <code>KEYCODE_11 = 227;</code>
   */
  KEYCODE_11(227),
  /**
   * <code>KEYCODE_12 = 228;</code>
   */
  KEYCODE_12(228),
  /**
   * <code>KEYCODE_LAST_CHANNEL = 229;</code>
   */
  KEYCODE_LAST_CHANNEL(229),
  /**
   * <code>KEYCODE_TV_DATA_SERVICE = 230;</code>
   */
  KEYCODE_TV_DATA_SERVICE(230),
  /**
   * <code>KEYCODE_VOICE_ASSIST = 231;</code>
   */
  KEYCODE_VOICE_ASSIST(231),
  /**
   * <code>KEYCODE_TV_RADIO_SERVICE = 232;</code>
   */
  KEYCODE_TV_RADIO_SERVICE(232),
  /**
   * <code>KEYCODE_TV_TELETEXT = 233;</code>
   */
  KEYCODE_TV_TELETEXT(233),
  /**
   * <code>KEYCODE_TV_NUMBER_ENTRY = 234;</code>
   */
  KEYCODE_TV_NUMBER_ENTRY(234),
  /**
   * <code>KEYCODE_TV_TERRESTRIAL_ANALOG = 235;</code>
   */
  KEYCODE_TV_TERRESTRIAL_ANALOG(235),
  /**
   * <code>KEYCODE_TV_TERRESTRIAL_DIGITAL = 236;</code>
   */
  KEYCODE_TV_TERRESTRIAL_DIGITAL(236),
  /**
   * <code>KEYCODE_TV_SATELLITE = 237;</code>
   */
  KEYCODE_TV_SATELLITE(237),
  /**
   * <code>KEYCODE_TV_SATELLITE_BS = 238;</code>
   */
  KEYCODE_TV_SATELLITE_BS(238),
  /**
   * <code>KEYCODE_TV_SATELLITE_CS = 239;</code>
   */
  KEYCODE_TV_SATELLITE_CS(239),
  /**
   * <code>KEYCODE_TV_SATELLITE_SERVICE = 240;</code>
   */
  KEYCODE_TV_SATELLITE_SERVICE(240),
  /**
   * <code>KEYCODE_TV_NETWORK = 241;</code>
   */
  KEYCODE_TV_NETWORK(241),
  /**
   * <code>KEYCODE_TV_ANTENNA_CABLE = 242;</code>
   */
  KEYCODE_TV_ANTENNA_CABLE(242),
  /**
   * <code>KEYCODE_TV_INPUT_HDMI_1 = 243;</code>
   */
  KEYCODE_TV_INPUT_HDMI_1(243),
  /**
   * <code>KEYCODE_TV_INPUT_HDMI_2 = 244;</code>
   */
  KEYCODE_TV_INPUT_HDMI_2(244),
  /**
   * <code>KEYCODE_TV_INPUT_HDMI_3 = 245;</code>
   */
  KEYCODE_TV_INPUT_HDMI_3(245),
  /**
   * <code>KEYCODE_TV_INPUT_HDMI_4 = 246;</code>
   */
  KEYCODE_TV_INPUT_HDMI_4(246),
  /**
   * <code>KEYCODE_TV_INPUT_COMPOSITE_1 = 247;</code>
   */
  KEYCODE_TV_INPUT_COMPOSITE_1(247),
  /**
   * <code>KEYCODE_TV_INPUT_COMPOSITE_2 = 248;</code>
   */
  KEYCODE_TV_INPUT_COMPOSITE_2(248),
  /**
   * <code>KEYCODE_TV_INPUT_COMPONENT_1 = 249;</code>
   */
  KEYCODE_TV_INPUT_COMPONENT_1(249),
  /**
   * <code>KEYCODE_TV_INPUT_COMPONENT_2 = 250;</code>
   */
  KEYCODE_TV_INPUT_COMPONENT_2(250),
  /**
   * <code>KEYCODE_TV_INPUT_VGA_1 = 251;</code>
   */
  KEYCODE_TV_INPUT_VGA_1(251),
  /**
   * <code>KEYCODE_TV_AUDIO_DESCRIPTION = 252;</code>
   */
  KEYCODE_TV_AUDIO_DESCRIPTION(252),
  /**
   * <code>KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP = 253;</code>
   */
  KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP(253),
  /**
   * <code>KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN = 254;</code>
   */
  KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN(254),
  /**
   * <code>KEYCODE_TV_ZOOM_MODE = 255;</code>
   */
  KEYCODE_TV_ZOOM_MODE(255),
  /**
   * <code>KEYCODE_TV_CONTENTS_MENU = 256;</code>
   */
  KEYCODE_TV_CONTENTS_MENU(256),
  /**
   * <code>KEYCODE_TV_MEDIA_CONTEXT_MENU = 257;</code>
   */
  KEYCODE_TV_MEDIA_CONTEXT_MENU(257),
  /**
   * <code>KEYCODE_TV_TIMER_PROGRAMMING = 258;</code>
   */
  KEYCODE_TV_TIMER_PROGRAMMING(258),
  /**
   * <code>KEYCODE_HELP = 259;</code>
   */
  KEYCODE_HELP(259),
  /**
   * <code>KEYCODE_NAVIGATE_PREVIOUS = 260;</code>
   */
  KEYCODE_NAVIGATE_PREVIOUS(260),
  /**
   * <code>KEYCODE_NAVIGATE_NEXT = 261;</code>
   */
  KEYCODE_NAVIGATE_NEXT(261),
  /**
   * <code>KEYCODE_NAVIGATE_IN = 262;</code>
   */
  KEYCODE_NAVIGATE_IN(262),
  /**
   * <code>KEYCODE_NAVIGATE_OUT = 263;</code>
   */
  KEYCODE_NAVIGATE_OUT(263),
  /**
   * <code>KEYCODE_STEM_PRIMARY = 264;</code>
   */
  KEYCODE_STEM_PRIMARY(264),
  /**
   * <code>KEYCODE_STEM_1 = 265;</code>
   */
  KEYCODE_STEM_1(265),
  /**
   * <code>KEYCODE_STEM_2 = 266;</code>
   */
  KEYCODE_STEM_2(266),
  /**
   * <code>KEYCODE_STEM_3 = 267;</code>
   */
  KEYCODE_STEM_3(267),
  /**
   * <code>KEYCODE_DPAD_UP_LEFT = 268;</code>
   */
  KEYCODE_DPAD_UP_LEFT(268),
  /**
   * <code>KEYCODE_DPAD_DOWN_LEFT = 269;</code>
   */
  KEYCODE_DPAD_DOWN_LEFT(269),
  /**
   * <code>KEYCODE_DPAD_UP_RIGHT = 270;</code>
   */
  KEYCODE_DPAD_UP_RIGHT(270),
  /**
   * <code>KEYCODE_DPAD_DOWN_RIGHT = 271;</code>
   */
  KEYCODE_DPAD_DOWN_RIGHT(271),
  /**
   * <code>KEYCODE_MEDIA_SKIP_FORWARD = 272;</code>
   */
  KEYCODE_MEDIA_SKIP_FORWARD(272),
  /**
   * <code>KEYCODE_MEDIA_SKIP_BACKWARD = 273;</code>
   */
  KEYCODE_MEDIA_SKIP_BACKWARD(273),
  /**
   * <code>KEYCODE_MEDIA_STEP_FORWARD = 274;</code>
   */
  KEYCODE_MEDIA_STEP_FORWARD(274),
  /**
   * <code>KEYCODE_MEDIA_STEP_BACKWARD = 275;</code>
   */
  KEYCODE_MEDIA_STEP_BACKWARD(275),
  /**
   * <code>KEYCODE_SOFT_SLEEP = 276;</code>
   */
  KEYCODE_SOFT_SLEEP(276),
  /**
   * <code>KEYCODE_CUT = 277;</code>
   */
  KEYCODE_CUT(277),
  /**
   * <code>KEYCODE_COPY = 278;</code>
   */
  KEYCODE_COPY(278),
  /**
   * <code>KEYCODE_PASTE = 279;</code>
   */
  KEYCODE_PASTE(279),
  /**
   * <code>KEYCODE_SYSTEM_NAVIGATION_UP = 280;</code>
   */
  KEYCODE_SYSTEM_NAVIGATION_UP(280),
  /**
   * <code>KEYCODE_SYSTEM_NAVIGATION_DOWN = 281;</code>
   */
  KEYCODE_SYSTEM_NAVIGATION_DOWN(281),
  /**
   * <code>KEYCODE_SYSTEM_NAVIGATION_LEFT = 282;</code>
   */
  KEYCODE_SYSTEM_NAVIGATION_LEFT(282),
  /**
   * <code>KEYCODE_SYSTEM_NAVIGATION_RIGHT = 283;</code>
   */
  KEYCODE_SYSTEM_NAVIGATION_RIGHT(283),
  /**
   * <code>KEYCODE_ALL_APPS = 284;</code>
   */
  KEYCODE_ALL_APPS(284),
  /**
   * <code>KEYCODE_REFRESH = 285;</code>
   */
  KEYCODE_REFRESH(285),
  /**
   * <code>KEYCODE_THUMBS_UP = 286;</code>
   */
  KEYCODE_THUMBS_UP(286),
  /**
   * <code>KEYCODE_THUMBS_DOWN = 287;</code>
   */
  KEYCODE_THUMBS_DOWN(287),
  /**
   * <code>KEYCODE_PROFILE_SWITCH = 288;</code>
   */
  KEYCODE_PROFILE_SWITCH(288),
  /**
   * <code>KEYCODE_VIDEO_APP_1 = 289;</code>
   */
  KEYCODE_VIDEO_APP_1(289),
  /**
   * <code>KEYCODE_VIDEO_APP_2 = 290;</code>
   */
  KEYCODE_VIDEO_APP_2(290),
  /**
   * <code>KEYCODE_VIDEO_APP_3 = 291;</code>
   */
  KEYCODE_VIDEO_APP_3(291),
  /**
   * <code>KEYCODE_VIDEO_APP_4 = 292;</code>
   */
  KEYCODE_VIDEO_APP_4(292),
  /**
   * <code>KEYCODE_VIDEO_APP_5 = 293;</code>
   */
  KEYCODE_VIDEO_APP_5(293),
  /**
   * <code>KEYCODE_VIDEO_APP_6 = 294;</code>
   */
  KEYCODE_VIDEO_APP_6(294),
  /**
   * <code>KEYCODE_VIDEO_APP_7 = 295;</code>
   */
  KEYCODE_VIDEO_APP_7(295),
  /**
   * <code>KEYCODE_VIDEO_APP_8 = 296;</code>
   */
  KEYCODE_VIDEO_APP_8(296),
  /**
   * <code>KEYCODE_FEATURED_APP_1 = 297;</code>
   */
  KEYCODE_FEATURED_APP_1(297),
  /**
   * <code>KEYCODE_FEATURED_APP_2 = 298;</code>
   */
  KEYCODE_FEATURED_APP_2(298),
  /**
   * <code>KEYCODE_FEATURED_APP_3 = 299;</code>
   */
  KEYCODE_FEATURED_APP_3(299),
  /**
   * <code>KEYCODE_FEATURED_APP_4 = 300;</code>
   */
  KEYCODE_FEATURED_APP_4(300),
  /**
   * <code>KEYCODE_DEMO_APP_1 = 301;</code>
   */
  KEYCODE_DEMO_APP_1(301),
  /**
   * <code>KEYCODE_DEMO_APP_2 = 302;</code>
   */
  KEYCODE_DEMO_APP_2(302),
  /**
   * <code>KEYCODE_DEMO_APP_3 = 303;</code>
   */
  KEYCODE_DEMO_APP_3(303),
  /**
   * <code>KEYCODE_DEMO_APP_4 = 304;</code>
   */
  KEYCODE_DEMO_APP_4(304),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>KEYCODE_UNKNOWN = 0;</code>
   */
  public static final int KEYCODE_UNKNOWN_VALUE = 0;
  /**
   * <code>KEYCODE_SOFT_LEFT = 1;</code>
   */
  public static final int KEYCODE_SOFT_LEFT_VALUE = 1;
  /**
   * <code>KEYCODE_SOFT_RIGHT = 2;</code>
   */
  public static final int KEYCODE_SOFT_RIGHT_VALUE = 2;
  /**
   * <code>KEYCODE_HOME = 3;</code>
   */
  public static final int KEYCODE_HOME_VALUE = 3;
  /**
   * <code>KEYCODE_BACK = 4;</code>
   */
  public static final int KEYCODE_BACK_VALUE = 4;
  /**
   * <code>KEYCODE_CALL = 5;</code>
   */
  public static final int KEYCODE_CALL_VALUE = 5;
  /**
   * <code>KEYCODE_ENDCALL = 6;</code>
   */
  public static final int KEYCODE_ENDCALL_VALUE = 6;
  /**
   * <code>KEYCODE_0 = 7;</code>
   */
  public static final int KEYCODE_0_VALUE = 7;
  /**
   * <code>KEYCODE_1 = 8;</code>
   */
  public static final int KEYCODE_1_VALUE = 8;
  /**
   * <code>KEYCODE_2 = 9;</code>
   */
  public static final int KEYCODE_2_VALUE = 9;
  /**
   * <code>KEYCODE_3 = 10;</code>
   */
  public static final int KEYCODE_3_VALUE = 10;
  /**
   * <code>KEYCODE_4 = 11;</code>
   */
  public static final int KEYCODE_4_VALUE = 11;
  /**
   * <code>KEYCODE_5 = 12;</code>
   */
  public static final int KEYCODE_5_VALUE = 12;
  /**
   * <code>KEYCODE_6 = 13;</code>
   */
  public static final int KEYCODE_6_VALUE = 13;
  /**
   * <code>KEYCODE_7 = 14;</code>
   */
  public static final int KEYCODE_7_VALUE = 14;
  /**
   * <code>KEYCODE_8 = 15;</code>
   */
  public static final int KEYCODE_8_VALUE = 15;
  /**
   * <code>KEYCODE_9 = 16;</code>
   */
  public static final int KEYCODE_9_VALUE = 16;
  /**
   * <code>KEYCODE_STAR = 17;</code>
   */
  public static final int KEYCODE_STAR_VALUE = 17;
  /**
   * <code>KEYCODE_POUND = 18;</code>
   */
  public static final int KEYCODE_POUND_VALUE = 18;
  /**
   * <code>KEYCODE_DPAD_UP = 19;</code>
   */
  public static final int KEYCODE_DPAD_UP_VALUE = 19;
  /**
   * <code>KEYCODE_DPAD_DOWN = 20;</code>
   */
  public static final int KEYCODE_DPAD_DOWN_VALUE = 20;
  /**
   * <code>KEYCODE_DPAD_LEFT = 21;</code>
   */
  public static final int KEYCODE_DPAD_LEFT_VALUE = 21;
  /**
   * <code>KEYCODE_DPAD_RIGHT = 22;</code>
   */
  public static final int KEYCODE_DPAD_RIGHT_VALUE = 22;
  /**
   * <code>KEYCODE_DPAD_CENTER = 23;</code>
   */
  public static final int KEYCODE_DPAD_CENTER_VALUE = 23;
  /**
   * <code>KEYCODE_VOLUME_UP = 24;</code>
   */
  public static final int KEYCODE_VOLUME_UP_VALUE = 24;
  /**
   * <code>KEYCODE_VOLUME_DOWN = 25;</code>
   */
  public static final int KEYCODE_VOLUME_DOWN_VALUE = 25;
  /**
   * <code>KEYCODE_POWER = 26;</code>
   */
  public static final int KEYCODE_POWER_VALUE = 26;
  /**
   * <code>KEYCODE_CAMERA = 27;</code>
   */
  public static final int KEYCODE_CAMERA_VALUE = 27;
  /**
   * <code>KEYCODE_CLEAR = 28;</code>
   */
  public static final int KEYCODE_CLEAR_VALUE = 28;
  /**
   * <code>KEYCODE_A = 29;</code>
   */
  public static final int KEYCODE_A_VALUE = 29;
  /**
   * <code>KEYCODE_B = 30;</code>
   */
  public static final int KEYCODE_B_VALUE = 30;
  /**
   * <code>KEYCODE_C = 31;</code>
   */
  public static final int KEYCODE_C_VALUE = 31;
  /**
   * <code>KEYCODE_D = 32;</code>
   */
  public static final int KEYCODE_D_VALUE = 32;
  /**
   * <code>KEYCODE_E = 33;</code>
   */
  public static final int KEYCODE_E_VALUE = 33;
  /**
   * <code>KEYCODE_F = 34;</code>
   */
  public static final int KEYCODE_F_VALUE = 34;
  /**
   * <code>KEYCODE_G = 35;</code>
   */
  public static final int KEYCODE_G_VALUE = 35;
  /**
   * <code>KEYCODE_H = 36;</code>
   */
  public static final int KEYCODE_H_VALUE = 36;
  /**
   * <code>KEYCODE_I = 37;</code>
   */
  public static final int KEYCODE_I_VALUE = 37;
  /**
   * <code>KEYCODE_J = 38;</code>
   */
  public static final int KEYCODE_J_VALUE = 38;
  /**
   * <code>KEYCODE_K = 39;</code>
   */
  public static final int KEYCODE_K_VALUE = 39;
  /**
   * <code>KEYCODE_L = 40;</code>
   */
  public static final int KEYCODE_L_VALUE = 40;
  /**
   * <code>KEYCODE_M = 41;</code>
   */
  public static final int KEYCODE_M_VALUE = 41;
  /**
   * <code>KEYCODE_N = 42;</code>
   */
  public static final int KEYCODE_N_VALUE = 42;
  /**
   * <code>KEYCODE_O = 43;</code>
   */
  public static final int KEYCODE_O_VALUE = 43;
  /**
   * <code>KEYCODE_P = 44;</code>
   */
  public static final int KEYCODE_P_VALUE = 44;
  /**
   * <code>KEYCODE_Q = 45;</code>
   */
  public static final int KEYCODE_Q_VALUE = 45;
  /**
   * <code>KEYCODE_R = 46;</code>
   */
  public static final int KEYCODE_R_VALUE = 46;
  /**
   * <code>KEYCODE_S = 47;</code>
   */
  public static final int KEYCODE_S_VALUE = 47;
  /**
   * <code>KEYCODE_T = 48;</code>
   */
  public static final int KEYCODE_T_VALUE = 48;
  /**
   * <code>KEYCODE_U = 49;</code>
   */
  public static final int KEYCODE_U_VALUE = 49;
  /**
   * <code>KEYCODE_V = 50;</code>
   */
  public static final int KEYCODE_V_VALUE = 50;
  /**
   * <code>KEYCODE_W = 51;</code>
   */
  public static final int KEYCODE_W_VALUE = 51;
  /**
   * <code>KEYCODE_X = 52;</code>
   */
  public static final int KEYCODE_X_VALUE = 52;
  /**
   * <code>KEYCODE_Y = 53;</code>
   */
  public static final int KEYCODE_Y_VALUE = 53;
  /**
   * <code>KEYCODE_Z = 54;</code>
   */
  public static final int KEYCODE_Z_VALUE = 54;
  /**
   * <code>KEYCODE_COMMA = 55;</code>
   */
  public static final int KEYCODE_COMMA_VALUE = 55;
  /**
   * <code>KEYCODE_PERIOD = 56;</code>
   */
  public static final int KEYCODE_PERIOD_VALUE = 56;
  /**
   * <code>KEYCODE_ALT_LEFT = 57;</code>
   */
  public static final int KEYCODE_ALT_LEFT_VALUE = 57;
  /**
   * <code>KEYCODE_ALT_RIGHT = 58;</code>
   */
  public static final int KEYCODE_ALT_RIGHT_VALUE = 58;
  /**
   * <code>KEYCODE_SHIFT_LEFT = 59;</code>
   */
  public static final int KEYCODE_SHIFT_LEFT_VALUE = 59;
  /**
   * <code>KEYCODE_SHIFT_RIGHT = 60;</code>
   */
  public static final int KEYCODE_SHIFT_RIGHT_VALUE = 60;
  /**
   * <code>KEYCODE_TAB = 61;</code>
   */
  public static final int KEYCODE_TAB_VALUE = 61;
  /**
   * <code>KEYCODE_SPACE = 62;</code>
   */
  public static final int KEYCODE_SPACE_VALUE = 62;
  /**
   * <code>KEYCODE_SYM = 63;</code>
   */
  public static final int KEYCODE_SYM_VALUE = 63;
  /**
   * <code>KEYCODE_EXPLORER = 64;</code>
   */
  public static final int KEYCODE_EXPLORER_VALUE = 64;
  /**
   * <code>KEYCODE_ENVELOPE = 65;</code>
   */
  public static final int KEYCODE_ENVELOPE_VALUE = 65;
  /**
   * <code>KEYCODE_ENTER = 66;</code>
   */
  public static final int KEYCODE_ENTER_VALUE = 66;
  /**
   * <code>KEYCODE_DEL = 67;</code>
   */
  public static final int KEYCODE_DEL_VALUE = 67;
  /**
   * <code>KEYCODE_GRAVE = 68;</code>
   */
  public static final int KEYCODE_GRAVE_VALUE = 68;
  /**
   * <code>KEYCODE_MINUS = 69;</code>
   */
  public static final int KEYCODE_MINUS_VALUE = 69;
  /**
   * <code>KEYCODE_EQUALS = 70;</code>
   */
  public static final int KEYCODE_EQUALS_VALUE = 70;
  /**
   * <code>KEYCODE_LEFT_BRACKET = 71;</code>
   */
  public static final int KEYCODE_LEFT_BRACKET_VALUE = 71;
  /**
   * <code>KEYCODE_RIGHT_BRACKET = 72;</code>
   */
  public static final int KEYCODE_RIGHT_BRACKET_VALUE = 72;
  /**
   * <code>KEYCODE_BACKSLASH = 73;</code>
   */
  public static final int KEYCODE_BACKSLASH_VALUE = 73;
  /**
   * <code>KEYCODE_SEMICOLON = 74;</code>
   */
  public static final int KEYCODE_SEMICOLON_VALUE = 74;
  /**
   * <code>KEYCODE_APOSTROPHE = 75;</code>
   */
  public static final int KEYCODE_APOSTROPHE_VALUE = 75;
  /**
   * <code>KEYCODE_SLASH = 76;</code>
   */
  public static final int KEYCODE_SLASH_VALUE = 76;
  /**
   * <code>KEYCODE_AT = 77;</code>
   */
  public static final int KEYCODE_AT_VALUE = 77;
  /**
   * <code>KEYCODE_NUM = 78;</code>
   */
  public static final int KEYCODE_NUM_VALUE = 78;
  /**
   * <code>KEYCODE_HEADSETHOOK = 79;</code>
   */
  public static final int KEYCODE_HEADSETHOOK_VALUE = 79;
  /**
   * <code>KEYCODE_FOCUS = 80;</code>
   */
  public static final int KEYCODE_FOCUS_VALUE = 80;
  /**
   * <code>KEYCODE_PLUS = 81;</code>
   */
  public static final int KEYCODE_PLUS_VALUE = 81;
  /**
   * <code>KEYCODE_MENU = 82;</code>
   */
  public static final int KEYCODE_MENU_VALUE = 82;
  /**
   * <code>KEYCODE_NOTIFICATION = 83;</code>
   */
  public static final int KEYCODE_NOTIFICATION_VALUE = 83;
  /**
   * <code>KEYCODE_SEARCH = 84;</code>
   */
  public static final int KEYCODE_SEARCH_VALUE = 84;
  /**
   * <code>KEYCODE_MEDIA_PLAY_PAUSE = 85;</code>
   */
  public static final int KEYCODE_MEDIA_PLAY_PAUSE_VALUE = 85;
  /**
   * <code>KEYCODE_MEDIA_STOP = 86;</code>
   */
  public static final int KEYCODE_MEDIA_STOP_VALUE = 86;
  /**
   * <code>KEYCODE_MEDIA_NEXT = 87;</code>
   */
  public static final int KEYCODE_MEDIA_NEXT_VALUE = 87;
  /**
   * <code>KEYCODE_MEDIA_PREVIOUS = 88;</code>
   */
  public static final int KEYCODE_MEDIA_PREVIOUS_VALUE = 88;
  /**
   * <code>KEYCODE_MEDIA_REWIND = 89;</code>
   */
  public static final int KEYCODE_MEDIA_REWIND_VALUE = 89;
  /**
   * <code>KEYCODE_MEDIA_FAST_FORWARD = 90;</code>
   */
  public static final int KEYCODE_MEDIA_FAST_FORWARD_VALUE = 90;
  /**
   * <code>KEYCODE_MUTE = 91;</code>
   */
  public static final int KEYCODE_MUTE_VALUE = 91;
  /**
   * <code>KEYCODE_PAGE_UP = 92;</code>
   */
  public static final int KEYCODE_PAGE_UP_VALUE = 92;
  /**
   * <code>KEYCODE_PAGE_DOWN = 93;</code>
   */
  public static final int KEYCODE_PAGE_DOWN_VALUE = 93;
  /**
   * <code>KEYCODE_PICTSYMBOLS = 94;</code>
   */
  public static final int KEYCODE_PICTSYMBOLS_VALUE = 94;
  /**
   * <code>KEYCODE_SWITCH_CHARSET = 95;</code>
   */
  public static final int KEYCODE_SWITCH_CHARSET_VALUE = 95;
  /**
   * <code>KEYCODE_BUTTON_A = 96;</code>
   */
  public static final int KEYCODE_BUTTON_A_VALUE = 96;
  /**
   * <code>KEYCODE_BUTTON_B = 97;</code>
   */
  public static final int KEYCODE_BUTTON_B_VALUE = 97;
  /**
   * <code>KEYCODE_BUTTON_C = 98;</code>
   */
  public static final int KEYCODE_BUTTON_C_VALUE = 98;
  /**
   * <code>KEYCODE_BUTTON_X = 99;</code>
   */
  public static final int KEYCODE_BUTTON_X_VALUE = 99;
  /**
   * <code>KEYCODE_BUTTON_Y = 100;</code>
   */
  public static final int KEYCODE_BUTTON_Y_VALUE = 100;
  /**
   * <code>KEYCODE_BUTTON_Z = 101;</code>
   */
  public static final int KEYCODE_BUTTON_Z_VALUE = 101;
  /**
   * <code>KEYCODE_BUTTON_L1 = 102;</code>
   */
  public static final int KEYCODE_BUTTON_L1_VALUE = 102;
  /**
   * <code>KEYCODE_BUTTON_R1 = 103;</code>
   */
  public static final int KEYCODE_BUTTON_R1_VALUE = 103;
  /**
   * <code>KEYCODE_BUTTON_L2 = 104;</code>
   */
  public static final int KEYCODE_BUTTON_L2_VALUE = 104;
  /**
   * <code>KEYCODE_BUTTON_R2 = 105;</code>
   */
  public static final int KEYCODE_BUTTON_R2_VALUE = 105;
  /**
   * <code>KEYCODE_BUTTON_THUMBL = 106;</code>
   */
  public static final int KEYCODE_BUTTON_THUMBL_VALUE = 106;
  /**
   * <code>KEYCODE_BUTTON_THUMBR = 107;</code>
   */
  public static final int KEYCODE_BUTTON_THUMBR_VALUE = 107;
  /**
   * <code>KEYCODE_BUTTON_START = 108;</code>
   */
  public static final int KEYCODE_BUTTON_START_VALUE = 108;
  /**
   * <code>KEYCODE_BUTTON_SELECT = 109;</code>
   */
  public static final int KEYCODE_BUTTON_SELECT_VALUE = 109;
  /**
   * <code>KEYCODE_BUTTON_MODE = 110;</code>
   */
  public static final int KEYCODE_BUTTON_MODE_VALUE = 110;
  /**
   * <code>KEYCODE_ESCAPE = 111;</code>
   */
  public static final int KEYCODE_ESCAPE_VALUE = 111;
  /**
   * <code>KEYCODE_FORWARD_DEL = 112;</code>
   */
  public static final int KEYCODE_FORWARD_DEL_VALUE = 112;
  /**
   * <code>KEYCODE_CTRL_LEFT = 113;</code>
   */
  public static final int KEYCODE_CTRL_LEFT_VALUE = 113;
  /**
   * <code>KEYCODE_CTRL_RIGHT = 114;</code>
   */
  public static final int KEYCODE_CTRL_RIGHT_VALUE = 114;
  /**
   * <code>KEYCODE_CAPS_LOCK = 115;</code>
   */
  public static final int KEYCODE_CAPS_LOCK_VALUE = 115;
  /**
   * <code>KEYCODE_SCROLL_LOCK = 116;</code>
   */
  public static final int KEYCODE_SCROLL_LOCK_VALUE = 116;
  /**
   * <code>KEYCODE_META_LEFT = 117;</code>
   */
  public static final int KEYCODE_META_LEFT_VALUE = 117;
  /**
   * <code>KEYCODE_META_RIGHT = 118;</code>
   */
  public static final int KEYCODE_META_RIGHT_VALUE = 118;
  /**
   * <code>KEYCODE_FUNCTION = 119;</code>
   */
  public static final int KEYCODE_FUNCTION_VALUE = 119;
  /**
   * <code>KEYCODE_SYSRQ = 120;</code>
   */
  public static final int KEYCODE_SYSRQ_VALUE = 120;
  /**
   * <code>KEYCODE_BREAK = 121;</code>
   */
  public static final int KEYCODE_BREAK_VALUE = 121;
  /**
   * <code>KEYCODE_MOVE_HOME = 122;</code>
   */
  public static final int KEYCODE_MOVE_HOME_VALUE = 122;
  /**
   * <code>KEYCODE_MOVE_END = 123;</code>
   */
  public static final int KEYCODE_MOVE_END_VALUE = 123;
  /**
   * <code>KEYCODE_INSERT = 124;</code>
   */
  public static final int KEYCODE_INSERT_VALUE = 124;
  /**
   * <code>KEYCODE_FORWARD = 125;</code>
   */
  public static final int KEYCODE_FORWARD_VALUE = 125;
  /**
   * <code>KEYCODE_MEDIA_PLAY = 126;</code>
   */
  public static final int KEYCODE_MEDIA_PLAY_VALUE = 126;
  /**
   * <code>KEYCODE_MEDIA_PAUSE = 127;</code>
   */
  public static final int KEYCODE_MEDIA_PAUSE_VALUE = 127;
  /**
   * <code>KEYCODE_MEDIA_CLOSE = 128;</code>
   */
  public static final int KEYCODE_MEDIA_CLOSE_VALUE = 128;
  /**
   * <code>KEYCODE_MEDIA_EJECT = 129;</code>
   */
  public static final int KEYCODE_MEDIA_EJECT_VALUE = 129;
  /**
   * <code>KEYCODE_MEDIA_RECORD = 130;</code>
   */
  public static final int KEYCODE_MEDIA_RECORD_VALUE = 130;
  /**
   * <code>KEYCODE_F1 = 131;</code>
   */
  public static final int KEYCODE_F1_VALUE = 131;
  /**
   * <code>KEYCODE_F2 = 132;</code>
   */
  public static final int KEYCODE_F2_VALUE = 132;
  /**
   * <code>KEYCODE_F3 = 133;</code>
   */
  public static final int KEYCODE_F3_VALUE = 133;
  /**
   * <code>KEYCODE_F4 = 134;</code>
   */
  public static final int KEYCODE_F4_VALUE = 134;
  /**
   * <code>KEYCODE_F5 = 135;</code>
   */
  public static final int KEYCODE_F5_VALUE = 135;
  /**
   * <code>KEYCODE_F6 = 136;</code>
   */
  public static final int KEYCODE_F6_VALUE = 136;
  /**
   * <code>KEYCODE_F7 = 137;</code>
   */
  public static final int KEYCODE_F7_VALUE = 137;
  /**
   * <code>KEYCODE_F8 = 138;</code>
   */
  public static final int KEYCODE_F8_VALUE = 138;
  /**
   * <code>KEYCODE_F9 = 139;</code>
   */
  public static final int KEYCODE_F9_VALUE = 139;
  /**
   * <code>KEYCODE_F10 = 140;</code>
   */
  public static final int KEYCODE_F10_VALUE = 140;
  /**
   * <code>KEYCODE_F11 = 141;</code>
   */
  public static final int KEYCODE_F11_VALUE = 141;
  /**
   * <code>KEYCODE_F12 = 142;</code>
   */
  public static final int KEYCODE_F12_VALUE = 142;
  /**
   * <code>KEYCODE_NUM_LOCK = 143;</code>
   */
  public static final int KEYCODE_NUM_LOCK_VALUE = 143;
  /**
   * <code>KEYCODE_NUMPAD_0 = 144;</code>
   */
  public static final int KEYCODE_NUMPAD_0_VALUE = 144;
  /**
   * <code>KEYCODE_NUMPAD_1 = 145;</code>
   */
  public static final int KEYCODE_NUMPAD_1_VALUE = 145;
  /**
   * <code>KEYCODE_NUMPAD_2 = 146;</code>
   */
  public static final int KEYCODE_NUMPAD_2_VALUE = 146;
  /**
   * <code>KEYCODE_NUMPAD_3 = 147;</code>
   */
  public static final int KEYCODE_NUMPAD_3_VALUE = 147;
  /**
   * <code>KEYCODE_NUMPAD_4 = 148;</code>
   */
  public static final int KEYCODE_NUMPAD_4_VALUE = 148;
  /**
   * <code>KEYCODE_NUMPAD_5 = 149;</code>
   */
  public static final int KEYCODE_NUMPAD_5_VALUE = 149;
  /**
   * <code>KEYCODE_NUMPAD_6 = 150;</code>
   */
  public static final int KEYCODE_NUMPAD_6_VALUE = 150;
  /**
   * <code>KEYCODE_NUMPAD_7 = 151;</code>
   */
  public static final int KEYCODE_NUMPAD_7_VALUE = 151;
  /**
   * <code>KEYCODE_NUMPAD_8 = 152;</code>
   */
  public static final int KEYCODE_NUMPAD_8_VALUE = 152;
  /**
   * <code>KEYCODE_NUMPAD_9 = 153;</code>
   */
  public static final int KEYCODE_NUMPAD_9_VALUE = 153;
  /**
   * <code>KEYCODE_NUMPAD_DIVIDE = 154;</code>
   */
  public static final int KEYCODE_NUMPAD_DIVIDE_VALUE = 154;
  /**
   * <code>KEYCODE_NUMPAD_MULTIPLY = 155;</code>
   */
  public static final int KEYCODE_NUMPAD_MULTIPLY_VALUE = 155;
  /**
   * <code>KEYCODE_NUMPAD_SUBTRACT = 156;</code>
   */
  public static final int KEYCODE_NUMPAD_SUBTRACT_VALUE = 156;
  /**
   * <code>KEYCODE_NUMPAD_ADD = 157;</code>
   */
  public static final int KEYCODE_NUMPAD_ADD_VALUE = 157;
  /**
   * <code>KEYCODE_NUMPAD_DOT = 158;</code>
   */
  public static final int KEYCODE_NUMPAD_DOT_VALUE = 158;
  /**
   * <code>KEYCODE_NUMPAD_COMMA = 159;</code>
   */
  public static final int KEYCODE_NUMPAD_COMMA_VALUE = 159;
  /**
   * <code>KEYCODE_NUMPAD_ENTER = 160;</code>
   */
  public static final int KEYCODE_NUMPAD_ENTER_VALUE = 160;
  /**
   * <code>KEYCODE_NUMPAD_EQUALS = 161;</code>
   */
  public static final int KEYCODE_NUMPAD_EQUALS_VALUE = 161;
  /**
   * <code>KEYCODE_NUMPAD_LEFT_PAREN = 162;</code>
   */
  public static final int KEYCODE_NUMPAD_LEFT_PAREN_VALUE = 162;
  /**
   * <code>KEYCODE_NUMPAD_RIGHT_PAREN = 163;</code>
   */
  public static final int KEYCODE_NUMPAD_RIGHT_PAREN_VALUE = 163;
  /**
   * <code>KEYCODE_VOLUME_MUTE = 164;</code>
   */
  public static final int KEYCODE_VOLUME_MUTE_VALUE = 164;
  /**
   * <code>KEYCODE_INFO = 165;</code>
   */
  public static final int KEYCODE_INFO_VALUE = 165;
  /**
   * <code>KEYCODE_CHANNEL_UP = 166;</code>
   */
  public static final int KEYCODE_CHANNEL_UP_VALUE = 166;
  /**
   * <code>KEYCODE_CHANNEL_DOWN = 167;</code>
   */
  public static final int KEYCODE_CHANNEL_DOWN_VALUE = 167;
  /**
   * <code>KEYCODE_ZOOM_IN = 168;</code>
   */
  public static final int KEYCODE_ZOOM_IN_VALUE = 168;
  /**
   * <code>KEYCODE_ZOOM_OUT = 169;</code>
   */
  public static final int KEYCODE_ZOOM_OUT_VALUE = 169;
  /**
   * <code>KEYCODE_TV = 170;</code>
   */
  public static final int KEYCODE_TV_VALUE = 170;
  /**
   * <code>KEYCODE_WINDOW = 171;</code>
   */
  public static final int KEYCODE_WINDOW_VALUE = 171;
  /**
   * <code>KEYCODE_GUIDE = 172;</code>
   */
  public static final int KEYCODE_GUIDE_VALUE = 172;
  /**
   * <code>KEYCODE_DVR = 173;</code>
   */
  public static final int KEYCODE_DVR_VALUE = 173;
  /**
   * <code>KEYCODE_BOOKMARK = 174;</code>
   */
  public static final int KEYCODE_BOOKMARK_VALUE = 174;
  /**
   * <code>KEYCODE_CAPTIONS = 175;</code>
   */
  public static final int KEYCODE_CAPTIONS_VALUE = 175;
  /**
   * <code>KEYCODE_SETTINGS = 176;</code>
   */
  public static final int KEYCODE_SETTINGS_VALUE = 176;
  /**
   * <code>KEYCODE_TV_POWER = 177;</code>
   */
  public static final int KEYCODE_TV_POWER_VALUE = 177;
  /**
   * <code>KEYCODE_TV_INPUT = 178;</code>
   */
  public static final int KEYCODE_TV_INPUT_VALUE = 178;
  /**
   * <code>KEYCODE_STB_POWER = 179;</code>
   */
  public static final int KEYCODE_STB_POWER_VALUE = 179;
  /**
   * <code>KEYCODE_STB_INPUT = 180;</code>
   */
  public static final int KEYCODE_STB_INPUT_VALUE = 180;
  /**
   * <code>KEYCODE_AVR_POWER = 181;</code>
   */
  public static final int KEYCODE_AVR_POWER_VALUE = 181;
  /**
   * <code>KEYCODE_AVR_INPUT = 182;</code>
   */
  public static final int KEYCODE_AVR_INPUT_VALUE = 182;
  /**
   * <code>KEYCODE_PROG_RED = 183;</code>
   */
  public static final int KEYCODE_PROG_RED_VALUE = 183;
  /**
   * <code>KEYCODE_PROG_GREEN = 184;</code>
   */
  public static final int KEYCODE_PROG_GREEN_VALUE = 184;
  /**
   * <code>KEYCODE_PROG_YELLOW = 185;</code>
   */
  public static final int KEYCODE_PROG_YELLOW_VALUE = 185;
  /**
   * <code>KEYCODE_PROG_BLUE = 186;</code>
   */
  public static final int KEYCODE_PROG_BLUE_VALUE = 186;
  /**
   * <code>KEYCODE_APP_SWITCH = 187;</code>
   */
  public static final int KEYCODE_APP_SWITCH_VALUE = 187;
  /**
   * <code>KEYCODE_BUTTON_1 = 188;</code>
   */
  public static final int KEYCODE_BUTTON_1_VALUE = 188;
  /**
   * <code>KEYCODE_BUTTON_2 = 189;</code>
   */
  public static final int KEYCODE_BUTTON_2_VALUE = 189;
  /**
   * <code>KEYCODE_BUTTON_3 = 190;</code>
   */
  public static final int KEYCODE_BUTTON_3_VALUE = 190;
  /**
   * <code>KEYCODE_BUTTON_4 = 191;</code>
   */
  public static final int KEYCODE_BUTTON_4_VALUE = 191;
  /**
   * <code>KEYCODE_BUTTON_5 = 192;</code>
   */
  public static final int KEYCODE_BUTTON_5_VALUE = 192;
  /**
   * <code>KEYCODE_BUTTON_6 = 193;</code>
   */
  public static final int KEYCODE_BUTTON_6_VALUE = 193;
  /**
   * <code>KEYCODE_BUTTON_7 = 194;</code>
   */
  public static final int KEYCODE_BUTTON_7_VALUE = 194;
  /**
   * <code>KEYCODE_BUTTON_8 = 195;</code>
   */
  public static final int KEYCODE_BUTTON_8_VALUE = 195;
  /**
   * <code>KEYCODE_BUTTON_9 = 196;</code>
   */
  public static final int KEYCODE_BUTTON_9_VALUE = 196;
  /**
   * <code>KEYCODE_BUTTON_10 = 197;</code>
   */
  public static final int KEYCODE_BUTTON_10_VALUE = 197;
  /**
   * <code>KEYCODE_BUTTON_11 = 198;</code>
   */
  public static final int KEYCODE_BUTTON_11_VALUE = 198;
  /**
   * <code>KEYCODE_BUTTON_12 = 199;</code>
   */
  public static final int KEYCODE_BUTTON_12_VALUE = 199;
  /**
   * <code>KEYCODE_BUTTON_13 = 200;</code>
   */
  public static final int KEYCODE_BUTTON_13_VALUE = 200;
  /**
   * <code>KEYCODE_BUTTON_14 = 201;</code>
   */
  public static final int KEYCODE_BUTTON_14_VALUE = 201;
  /**
   * <code>KEYCODE_BUTTON_15 = 202;</code>
   */
  public static final int KEYCODE_BUTTON_15_VALUE = 202;
  /**
   * <code>KEYCODE_BUTTON_16 = 203;</code>
   */
  public static final int KEYCODE_BUTTON_16_VALUE = 203;
  /**
   * <code>KEYCODE_LANGUAGE_SWITCH = 204;</code>
   */
  public static final int KEYCODE_LANGUAGE_SWITCH_VALUE = 204;
  /**
   * <code>KEYCODE_MANNER_MODE = 205;</code>
   */
  public static final int KEYCODE_MANNER_MODE_VALUE = 205;
  /**
   * <code>KEYCODE_3D_MODE = 206;</code>
   */
  public static final int KEYCODE_3D_MODE_VALUE = 206;
  /**
   * <code>KEYCODE_CONTACTS = 207;</code>
   */
  public static final int KEYCODE_CONTACTS_VALUE = 207;
  /**
   * <code>KEYCODE_CALENDAR = 208;</code>
   */
  public static final int KEYCODE_CALENDAR_VALUE = 208;
  /**
   * <code>KEYCODE_MUSIC = 209;</code>
   */
  public static final int KEYCODE_MUSIC_VALUE = 209;
  /**
   * <code>KEYCODE_CALCULATOR = 210;</code>
   */
  public static final int KEYCODE_CALCULATOR_VALUE = 210;
  /**
   * <code>KEYCODE_ZENKAKU_HANKAKU = 211;</code>
   */
  public static final int KEYCODE_ZENKAKU_HANKAKU_VALUE = 211;
  /**
   * <code>KEYCODE_EISU = 212;</code>
   */
  public static final int KEYCODE_EISU_VALUE = 212;
  /**
   * <code>KEYCODE_MUHENKAN = 213;</code>
   */
  public static final int KEYCODE_MUHENKAN_VALUE = 213;
  /**
   * <code>KEYCODE_HENKAN = 214;</code>
   */
  public static final int KEYCODE_HENKAN_VALUE = 214;
  /**
   * <code>KEYCODE_KATAKANA_HIRAGANA = 215;</code>
   */
  public static final int KEYCODE_KATAKANA_HIRAGANA_VALUE = 215;
  /**
   * <code>KEYCODE_YEN = 216;</code>
   */
  public static final int KEYCODE_YEN_VALUE = 216;
  /**
   * <code>KEYCODE_RO = 217;</code>
   */
  public static final int KEYCODE_RO_VALUE = 217;
  /**
   * <code>KEYCODE_KANA = 218;</code>
   */
  public static final int KEYCODE_KANA_VALUE = 218;
  /**
   * <code>KEYCODE_ASSIST = 219;</code>
   */
  public static final int KEYCODE_ASSIST_VALUE = 219;
  /**
   * <code>KEYCODE_BRIGHTNESS_DOWN = 220;</code>
   */
  public static final int KEYCODE_BRIGHTNESS_DOWN_VALUE = 220;
  /**
   * <code>KEYCODE_BRIGHTNESS_UP = 221;</code>
   */
  public static final int KEYCODE_BRIGHTNESS_UP_VALUE = 221;
  /**
   * <code>KEYCODE_MEDIA_AUDIO_TRACK = 222;</code>
   */
  public static final int KEYCODE_MEDIA_AUDIO_TRACK_VALUE = 222;
  /**
   * <code>KEYCODE_SLEEP = 223;</code>
   */
  public static final int KEYCODE_SLEEP_VALUE = 223;
  /**
   * <code>KEYCODE_WAKEUP = 224;</code>
   */
  public static final int KEYCODE_WAKEUP_VALUE = 224;
  /**
   * <code>KEYCODE_PAIRING = 225;</code>
   */
  public static final int KEYCODE_PAIRING_VALUE = 225;
  /**
   * <code>KEYCODE_MEDIA_TOP_MENU = 226;</code>
   */
  public static final int KEYCODE_MEDIA_TOP_MENU_VALUE = 226;
  /**
   * <code>KEYCODE_11 = 227;</code>
   */
  public static final int KEYCODE_11_VALUE = 227;
  /**
   * <code>KEYCODE_12 = 228;</code>
   */
  public static final int KEYCODE_12_VALUE = 228;
  /**
   * <code>KEYCODE_LAST_CHANNEL = 229;</code>
   */
  public static final int KEYCODE_LAST_CHANNEL_VALUE = 229;
  /**
   * <code>KEYCODE_TV_DATA_SERVICE = 230;</code>
   */
  public static final int KEYCODE_TV_DATA_SERVICE_VALUE = 230;
  /**
   * <code>KEYCODE_VOICE_ASSIST = 231;</code>
   */
  public static final int KEYCODE_VOICE_ASSIST_VALUE = 231;
  /**
   * <code>KEYCODE_TV_RADIO_SERVICE = 232;</code>
   */
  public static final int KEYCODE_TV_RADIO_SERVICE_VALUE = 232;
  /**
   * <code>KEYCODE_TV_TELETEXT = 233;</code>
   */
  public static final int KEYCODE_TV_TELETEXT_VALUE = 233;
  /**
   * <code>KEYCODE_TV_NUMBER_ENTRY = 234;</code>
   */
  public static final int KEYCODE_TV_NUMBER_ENTRY_VALUE = 234;
  /**
   * <code>KEYCODE_TV_TERRESTRIAL_ANALOG = 235;</code>
   */
  public static final int KEYCODE_TV_TERRESTRIAL_ANALOG_VALUE = 235;
  /**
   * <code>KEYCODE_TV_TERRESTRIAL_DIGITAL = 236;</code>
   */
  public static final int KEYCODE_TV_TERRESTRIAL_DIGITAL_VALUE = 236;
  /**
   * <code>KEYCODE_TV_SATELLITE = 237;</code>
   */
  public static final int KEYCODE_TV_SATELLITE_VALUE = 237;
  /**
   * <code>KEYCODE_TV_SATELLITE_BS = 238;</code>
   */
  public static final int KEYCODE_TV_SATELLITE_BS_VALUE = 238;
  /**
   * <code>KEYCODE_TV_SATELLITE_CS = 239;</code>
   */
  public static final int KEYCODE_TV_SATELLITE_CS_VALUE = 239;
  /**
   * <code>KEYCODE_TV_SATELLITE_SERVICE = 240;</code>
   */
  public static final int KEYCODE_TV_SATELLITE_SERVICE_VALUE = 240;
  /**
   * <code>KEYCODE_TV_NETWORK = 241;</code>
   */
  public static final int KEYCODE_TV_NETWORK_VALUE = 241;
  /**
   * <code>KEYCODE_TV_ANTENNA_CABLE = 242;</code>
   */
  public static final int KEYCODE_TV_ANTENNA_CABLE_VALUE = 242;
  /**
   * <code>KEYCODE_TV_INPUT_HDMI_1 = 243;</code>
   */
  public static final int KEYCODE_TV_INPUT_HDMI_1_VALUE = 243;
  /**
   * <code>KEYCODE_TV_INPUT_HDMI_2 = 244;</code>
   */
  public static final int KEYCODE_TV_INPUT_HDMI_2_VALUE = 244;
  /**
   * <code>KEYCODE_TV_INPUT_HDMI_3 = 245;</code>
   */
  public static final int KEYCODE_TV_INPUT_HDMI_3_VALUE = 245;
  /**
   * <code>KEYCODE_TV_INPUT_HDMI_4 = 246;</code>
   */
  public static final int KEYCODE_TV_INPUT_HDMI_4_VALUE = 246;
  /**
   * <code>KEYCODE_TV_INPUT_COMPOSITE_1 = 247;</code>
   */
  public static final int KEYCODE_TV_INPUT_COMPOSITE_1_VALUE = 247;
  /**
   * <code>KEYCODE_TV_INPUT_COMPOSITE_2 = 248;</code>
   */
  public static final int KEYCODE_TV_INPUT_COMPOSITE_2_VALUE = 248;
  /**
   * <code>KEYCODE_TV_INPUT_COMPONENT_1 = 249;</code>
   */
  public static final int KEYCODE_TV_INPUT_COMPONENT_1_VALUE = 249;
  /**
   * <code>KEYCODE_TV_INPUT_COMPONENT_2 = 250;</code>
   */
  public static final int KEYCODE_TV_INPUT_COMPONENT_2_VALUE = 250;
  /**
   * <code>KEYCODE_TV_INPUT_VGA_1 = 251;</code>
   */
  public static final int KEYCODE_TV_INPUT_VGA_1_VALUE = 251;
  /**
   * <code>KEYCODE_TV_AUDIO_DESCRIPTION = 252;</code>
   */
  public static final int KEYCODE_TV_AUDIO_DESCRIPTION_VALUE = 252;
  /**
   * <code>KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP = 253;</code>
   */
  public static final int KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP_VALUE = 253;
  /**
   * <code>KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN = 254;</code>
   */
  public static final int KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN_VALUE = 254;
  /**
   * <code>KEYCODE_TV_ZOOM_MODE = 255;</code>
   */
  public static final int KEYCODE_TV_ZOOM_MODE_VALUE = 255;
  /**
   * <code>KEYCODE_TV_CONTENTS_MENU = 256;</code>
   */
  public static final int KEYCODE_TV_CONTENTS_MENU_VALUE = 256;
  /**
   * <code>KEYCODE_TV_MEDIA_CONTEXT_MENU = 257;</code>
   */
  public static final int KEYCODE_TV_MEDIA_CONTEXT_MENU_VALUE = 257;
  /**
   * <code>KEYCODE_TV_TIMER_PROGRAMMING = 258;</code>
   */
  public static final int KEYCODE_TV_TIMER_PROGRAMMING_VALUE = 258;
  /**
   * <code>KEYCODE_HELP = 259;</code>
   */
  public static final int KEYCODE_HELP_VALUE = 259;
  /**
   * <code>KEYCODE_NAVIGATE_PREVIOUS = 260;</code>
   */
  public static final int KEYCODE_NAVIGATE_PREVIOUS_VALUE = 260;
  /**
   * <code>KEYCODE_NAVIGATE_NEXT = 261;</code>
   */
  public static final int KEYCODE_NAVIGATE_NEXT_VALUE = 261;
  /**
   * <code>KEYCODE_NAVIGATE_IN = 262;</code>
   */
  public static final int KEYCODE_NAVIGATE_IN_VALUE = 262;
  /**
   * <code>KEYCODE_NAVIGATE_OUT = 263;</code>
   */
  public static final int KEYCODE_NAVIGATE_OUT_VALUE = 263;
  /**
   * <code>KEYCODE_STEM_PRIMARY = 264;</code>
   */
  public static final int KEYCODE_STEM_PRIMARY_VALUE = 264;
  /**
   * <code>KEYCODE_STEM_1 = 265;</code>
   */
  public static final int KEYCODE_STEM_1_VALUE = 265;
  /**
   * <code>KEYCODE_STEM_2 = 266;</code>
   */
  public static final int KEYCODE_STEM_2_VALUE = 266;
  /**
   * <code>KEYCODE_STEM_3 = 267;</code>
   */
  public static final int KEYCODE_STEM_3_VALUE = 267;
  /**
   * <code>KEYCODE_DPAD_UP_LEFT = 268;</code>
   */
  public static final int KEYCODE_DPAD_UP_LEFT_VALUE = 268;
  /**
   * <code>KEYCODE_DPAD_DOWN_LEFT = 269;</code>
   */
  public static final int KEYCODE_DPAD_DOWN_LEFT_VALUE = 269;
  /**
   * <code>KEYCODE_DPAD_UP_RIGHT = 270;</code>
   */
  public static final int KEYCODE_DPAD_UP_RIGHT_VALUE = 270;
  /**
   * <code>KEYCODE_DPAD_DOWN_RIGHT = 271;</code>
   */
  public static final int KEYCODE_DPAD_DOWN_RIGHT_VALUE = 271;
  /**
   * <code>KEYCODE_MEDIA_SKIP_FORWARD = 272;</code>
   */
  public static final int KEYCODE_MEDIA_SKIP_FORWARD_VALUE = 272;
  /**
   * <code>KEYCODE_MEDIA_SKIP_BACKWARD = 273;</code>
   */
  public static final int KEYCODE_MEDIA_SKIP_BACKWARD_VALUE = 273;
  /**
   * <code>KEYCODE_MEDIA_STEP_FORWARD = 274;</code>
   */
  public static final int KEYCODE_MEDIA_STEP_FORWARD_VALUE = 274;
  /**
   * <code>KEYCODE_MEDIA_STEP_BACKWARD = 275;</code>
   */
  public static final int KEYCODE_MEDIA_STEP_BACKWARD_VALUE = 275;
  /**
   * <code>KEYCODE_SOFT_SLEEP = 276;</code>
   */
  public static final int KEYCODE_SOFT_SLEEP_VALUE = 276;
  /**
   * <code>KEYCODE_CUT = 277;</code>
   */
  public static final int KEYCODE_CUT_VALUE = 277;
  /**
   * <code>KEYCODE_COPY = 278;</code>
   */
  public static final int KEYCODE_COPY_VALUE = 278;
  /**
   * <code>KEYCODE_PASTE = 279;</code>
   */
  public static final int KEYCODE_PASTE_VALUE = 279;
  /**
   * <code>KEYCODE_SYSTEM_NAVIGATION_UP = 280;</code>
   */
  public static final int KEYCODE_SYSTEM_NAVIGATION_UP_VALUE = 280;
  /**
   * <code>KEYCODE_SYSTEM_NAVIGATION_DOWN = 281;</code>
   */
  public static final int KEYCODE_SYSTEM_NAVIGATION_DOWN_VALUE = 281;
  /**
   * <code>KEYCODE_SYSTEM_NAVIGATION_LEFT = 282;</code>
   */
  public static final int KEYCODE_SYSTEM_NAVIGATION_LEFT_VALUE = 282;
  /**
   * <code>KEYCODE_SYSTEM_NAVIGATION_RIGHT = 283;</code>
   */
  public static final int KEYCODE_SYSTEM_NAVIGATION_RIGHT_VALUE = 283;
  /**
   * <code>KEYCODE_ALL_APPS = 284;</code>
   */
  public static final int KEYCODE_ALL_APPS_VALUE = 284;
  /**
   * <code>KEYCODE_REFRESH = 285;</code>
   */
  public static final int KEYCODE_REFRESH_VALUE = 285;
  /**
   * <code>KEYCODE_THUMBS_UP = 286;</code>
   */
  public static final int KEYCODE_THUMBS_UP_VALUE = 286;
  /**
   * <code>KEYCODE_THUMBS_DOWN = 287;</code>
   */
  public static final int KEYCODE_THUMBS_DOWN_VALUE = 287;
  /**
   * <code>KEYCODE_PROFILE_SWITCH = 288;</code>
   */
  public static final int KEYCODE_PROFILE_SWITCH_VALUE = 288;
  /**
   * <code>KEYCODE_VIDEO_APP_1 = 289;</code>
   */
  public static final int KEYCODE_VIDEO_APP_1_VALUE = 289;
  /**
   * <code>KEYCODE_VIDEO_APP_2 = 290;</code>
   */
  public static final int KEYCODE_VIDEO_APP_2_VALUE = 290;
  /**
   * <code>KEYCODE_VIDEO_APP_3 = 291;</code>
   */
  public static final int KEYCODE_VIDEO_APP_3_VALUE = 291;
  /**
   * <code>KEYCODE_VIDEO_APP_4 = 292;</code>
   */
  public static final int KEYCODE_VIDEO_APP_4_VALUE = 292;
  /**
   * <code>KEYCODE_VIDEO_APP_5 = 293;</code>
   */
  public static final int KEYCODE_VIDEO_APP_5_VALUE = 293;
  /**
   * <code>KEYCODE_VIDEO_APP_6 = 294;</code>
   */
  public static final int KEYCODE_VIDEO_APP_6_VALUE = 294;
  /**
   * <code>KEYCODE_VIDEO_APP_7 = 295;</code>
   */
  public static final int KEYCODE_VIDEO_APP_7_VALUE = 295;
  /**
   * <code>KEYCODE_VIDEO_APP_8 = 296;</code>
   */
  public static final int KEYCODE_VIDEO_APP_8_VALUE = 296;
  /**
   * <code>KEYCODE_FEATURED_APP_1 = 297;</code>
   */
  public static final int KEYCODE_FEATURED_APP_1_VALUE = 297;
  /**
   * <code>KEYCODE_FEATURED_APP_2 = 298;</code>
   */
  public static final int KEYCODE_FEATURED_APP_2_VALUE = 298;
  /**
   * <code>KEYCODE_FEATURED_APP_3 = 299;</code>
   */
  public static final int KEYCODE_FEATURED_APP_3_VALUE = 299;
  /**
   * <code>KEYCODE_FEATURED_APP_4 = 300;</code>
   */
  public static final int KEYCODE_FEATURED_APP_4_VALUE = 300;
  /**
   * <code>KEYCODE_DEMO_APP_1 = 301;</code>
   */
  public static final int KEYCODE_DEMO_APP_1_VALUE = 301;
  /**
   * <code>KEYCODE_DEMO_APP_2 = 302;</code>
   */
  public static final int KEYCODE_DEMO_APP_2_VALUE = 302;
  /**
   * <code>KEYCODE_DEMO_APP_3 = 303;</code>
   */
  public static final int KEYCODE_DEMO_APP_3_VALUE = 303;
  /**
   * <code>KEYCODE_DEMO_APP_4 = 304;</code>
   */
  public static final int KEYCODE_DEMO_APP_4_VALUE = 304;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RemoteKeyCode valueOf(int value) {
    return forNumber(value);
  }

  public static RemoteKeyCode forNumber(int value) {
    switch (value) {
      case 0: return KEYCODE_UNKNOWN;
      case 1: return KEYCODE_SOFT_LEFT;
      case 2: return KEYCODE_SOFT_RIGHT;
      case 3: return KEYCODE_HOME;
      case 4: return KEYCODE_BACK;
      case 5: return KEYCODE_CALL;
      case 6: return KEYCODE_ENDCALL;
      case 7: return KEYCODE_0;
      case 8: return KEYCODE_1;
      case 9: return KEYCODE_2;
      case 10: return KEYCODE_3;
      case 11: return KEYCODE_4;
      case 12: return KEYCODE_5;
      case 13: return KEYCODE_6;
      case 14: return KEYCODE_7;
      case 15: return KEYCODE_8;
      case 16: return KEYCODE_9;
      case 17: return KEYCODE_STAR;
      case 18: return KEYCODE_POUND;
      case 19: return KEYCODE_DPAD_UP;
      case 20: return KEYCODE_DPAD_DOWN;
      case 21: return KEYCODE_DPAD_LEFT;
      case 22: return KEYCODE_DPAD_RIGHT;
      case 23: return KEYCODE_DPAD_CENTER;
      case 24: return KEYCODE_VOLUME_UP;
      case 25: return KEYCODE_VOLUME_DOWN;
      case 26: return KEYCODE_POWER;
      case 27: return KEYCODE_CAMERA;
      case 28: return KEYCODE_CLEAR;
      case 29: return KEYCODE_A;
      case 30: return KEYCODE_B;
      case 31: return KEYCODE_C;
      case 32: return KEYCODE_D;
      case 33: return KEYCODE_E;
      case 34: return KEYCODE_F;
      case 35: return KEYCODE_G;
      case 36: return KEYCODE_H;
      case 37: return KEYCODE_I;
      case 38: return KEYCODE_J;
      case 39: return KEYCODE_K;
      case 40: return KEYCODE_L;
      case 41: return KEYCODE_M;
      case 42: return KEYCODE_N;
      case 43: return KEYCODE_O;
      case 44: return KEYCODE_P;
      case 45: return KEYCODE_Q;
      case 46: return KEYCODE_R;
      case 47: return KEYCODE_S;
      case 48: return KEYCODE_T;
      case 49: return KEYCODE_U;
      case 50: return KEYCODE_V;
      case 51: return KEYCODE_W;
      case 52: return KEYCODE_X;
      case 53: return KEYCODE_Y;
      case 54: return KEYCODE_Z;
      case 55: return KEYCODE_COMMA;
      case 56: return KEYCODE_PERIOD;
      case 57: return KEYCODE_ALT_LEFT;
      case 58: return KEYCODE_ALT_RIGHT;
      case 59: return KEYCODE_SHIFT_LEFT;
      case 60: return KEYCODE_SHIFT_RIGHT;
      case 61: return KEYCODE_TAB;
      case 62: return KEYCODE_SPACE;
      case 63: return KEYCODE_SYM;
      case 64: return KEYCODE_EXPLORER;
      case 65: return KEYCODE_ENVELOPE;
      case 66: return KEYCODE_ENTER;
      case 67: return KEYCODE_DEL;
      case 68: return KEYCODE_GRAVE;
      case 69: return KEYCODE_MINUS;
      case 70: return KEYCODE_EQUALS;
      case 71: return KEYCODE_LEFT_BRACKET;
      case 72: return KEYCODE_RIGHT_BRACKET;
      case 73: return KEYCODE_BACKSLASH;
      case 74: return KEYCODE_SEMICOLON;
      case 75: return KEYCODE_APOSTROPHE;
      case 76: return KEYCODE_SLASH;
      case 77: return KEYCODE_AT;
      case 78: return KEYCODE_NUM;
      case 79: return KEYCODE_HEADSETHOOK;
      case 80: return KEYCODE_FOCUS;
      case 81: return KEYCODE_PLUS;
      case 82: return KEYCODE_MENU;
      case 83: return KEYCODE_NOTIFICATION;
      case 84: return KEYCODE_SEARCH;
      case 85: return KEYCODE_MEDIA_PLAY_PAUSE;
      case 86: return KEYCODE_MEDIA_STOP;
      case 87: return KEYCODE_MEDIA_NEXT;
      case 88: return KEYCODE_MEDIA_PREVIOUS;
      case 89: return KEYCODE_MEDIA_REWIND;
      case 90: return KEYCODE_MEDIA_FAST_FORWARD;
      case 91: return KEYCODE_MUTE;
      case 92: return KEYCODE_PAGE_UP;
      case 93: return KEYCODE_PAGE_DOWN;
      case 94: return KEYCODE_PICTSYMBOLS;
      case 95: return KEYCODE_SWITCH_CHARSET;
      case 96: return KEYCODE_BUTTON_A;
      case 97: return KEYCODE_BUTTON_B;
      case 98: return KEYCODE_BUTTON_C;
      case 99: return KEYCODE_BUTTON_X;
      case 100: return KEYCODE_BUTTON_Y;
      case 101: return KEYCODE_BUTTON_Z;
      case 102: return KEYCODE_BUTTON_L1;
      case 103: return KEYCODE_BUTTON_R1;
      case 104: return KEYCODE_BUTTON_L2;
      case 105: return KEYCODE_BUTTON_R2;
      case 106: return KEYCODE_BUTTON_THUMBL;
      case 107: return KEYCODE_BUTTON_THUMBR;
      case 108: return KEYCODE_BUTTON_START;
      case 109: return KEYCODE_BUTTON_SELECT;
      case 110: return KEYCODE_BUTTON_MODE;
      case 111: return KEYCODE_ESCAPE;
      case 112: return KEYCODE_FORWARD_DEL;
      case 113: return KEYCODE_CTRL_LEFT;
      case 114: return KEYCODE_CTRL_RIGHT;
      case 115: return KEYCODE_CAPS_LOCK;
      case 116: return KEYCODE_SCROLL_LOCK;
      case 117: return KEYCODE_META_LEFT;
      case 118: return KEYCODE_META_RIGHT;
      case 119: return KEYCODE_FUNCTION;
      case 120: return KEYCODE_SYSRQ;
      case 121: return KEYCODE_BREAK;
      case 122: return KEYCODE_MOVE_HOME;
      case 123: return KEYCODE_MOVE_END;
      case 124: return KEYCODE_INSERT;
      case 125: return KEYCODE_FORWARD;
      case 126: return KEYCODE_MEDIA_PLAY;
      case 127: return KEYCODE_MEDIA_PAUSE;
      case 128: return KEYCODE_MEDIA_CLOSE;
      case 129: return KEYCODE_MEDIA_EJECT;
      case 130: return KEYCODE_MEDIA_RECORD;
      case 131: return KEYCODE_F1;
      case 132: return KEYCODE_F2;
      case 133: return KEYCODE_F3;
      case 134: return KEYCODE_F4;
      case 135: return KEYCODE_F5;
      case 136: return KEYCODE_F6;
      case 137: return KEYCODE_F7;
      case 138: return KEYCODE_F8;
      case 139: return KEYCODE_F9;
      case 140: return KEYCODE_F10;
      case 141: return KEYCODE_F11;
      case 142: return KEYCODE_F12;
      case 143: return KEYCODE_NUM_LOCK;
      case 144: return KEYCODE_NUMPAD_0;
      case 145: return KEYCODE_NUMPAD_1;
      case 146: return KEYCODE_NUMPAD_2;
      case 147: return KEYCODE_NUMPAD_3;
      case 148: return KEYCODE_NUMPAD_4;
      case 149: return KEYCODE_NUMPAD_5;
      case 150: return KEYCODE_NUMPAD_6;
      case 151: return KEYCODE_NUMPAD_7;
      case 152: return KEYCODE_NUMPAD_8;
      case 153: return KEYCODE_NUMPAD_9;
      case 154: return KEYCODE_NUMPAD_DIVIDE;
      case 155: return KEYCODE_NUMPAD_MULTIPLY;
      case 156: return KEYCODE_NUMPAD_SUBTRACT;
      case 157: return KEYCODE_NUMPAD_ADD;
      case 158: return KEYCODE_NUMPAD_DOT;
      case 159: return KEYCODE_NUMPAD_COMMA;
      case 160: return KEYCODE_NUMPAD_ENTER;
      case 161: return KEYCODE_NUMPAD_EQUALS;
      case 162: return KEYCODE_NUMPAD_LEFT_PAREN;
      case 163: return KEYCODE_NUMPAD_RIGHT_PAREN;
      case 164: return KEYCODE_VOLUME_MUTE;
      case 165: return KEYCODE_INFO;
      case 166: return KEYCODE_CHANNEL_UP;
      case 167: return KEYCODE_CHANNEL_DOWN;
      case 168: return KEYCODE_ZOOM_IN;
      case 169: return KEYCODE_ZOOM_OUT;
      case 170: return KEYCODE_TV;
      case 171: return KEYCODE_WINDOW;
      case 172: return KEYCODE_GUIDE;
      case 173: return KEYCODE_DVR;
      case 174: return KEYCODE_BOOKMARK;
      case 175: return KEYCODE_CAPTIONS;
      case 176: return KEYCODE_SETTINGS;
      case 177: return KEYCODE_TV_POWER;
      case 178: return KEYCODE_TV_INPUT;
      case 179: return KEYCODE_STB_POWER;
      case 180: return KEYCODE_STB_INPUT;
      case 181: return KEYCODE_AVR_POWER;
      case 182: return KEYCODE_AVR_INPUT;
      case 183: return KEYCODE_PROG_RED;
      case 184: return KEYCODE_PROG_GREEN;
      case 185: return KEYCODE_PROG_YELLOW;
      case 186: return KEYCODE_PROG_BLUE;
      case 187: return KEYCODE_APP_SWITCH;
      case 188: return KEYCODE_BUTTON_1;
      case 189: return KEYCODE_BUTTON_2;
      case 190: return KEYCODE_BUTTON_3;
      case 191: return KEYCODE_BUTTON_4;
      case 192: return KEYCODE_BUTTON_5;
      case 193: return KEYCODE_BUTTON_6;
      case 194: return KEYCODE_BUTTON_7;
      case 195: return KEYCODE_BUTTON_8;
      case 196: return KEYCODE_BUTTON_9;
      case 197: return KEYCODE_BUTTON_10;
      case 198: return KEYCODE_BUTTON_11;
      case 199: return KEYCODE_BUTTON_12;
      case 200: return KEYCODE_BUTTON_13;
      case 201: return KEYCODE_BUTTON_14;
      case 202: return KEYCODE_BUTTON_15;
      case 203: return KEYCODE_BUTTON_16;
      case 204: return KEYCODE_LANGUAGE_SWITCH;
      case 205: return KEYCODE_MANNER_MODE;
      case 206: return KEYCODE_3D_MODE;
      case 207: return KEYCODE_CONTACTS;
      case 208: return KEYCODE_CALENDAR;
      case 209: return KEYCODE_MUSIC;
      case 210: return KEYCODE_CALCULATOR;
      case 211: return KEYCODE_ZENKAKU_HANKAKU;
      case 212: return KEYCODE_EISU;
      case 213: return KEYCODE_MUHENKAN;
      case 214: return KEYCODE_HENKAN;
      case 215: return KEYCODE_KATAKANA_HIRAGANA;
      case 216: return KEYCODE_YEN;
      case 217: return KEYCODE_RO;
      case 218: return KEYCODE_KANA;
      case 219: return KEYCODE_ASSIST;
      case 220: return KEYCODE_BRIGHTNESS_DOWN;
      case 221: return KEYCODE_BRIGHTNESS_UP;
      case 222: return KEYCODE_MEDIA_AUDIO_TRACK;
      case 223: return KEYCODE_SLEEP;
      case 224: return KEYCODE_WAKEUP;
      case 225: return KEYCODE_PAIRING;
      case 226: return KEYCODE_MEDIA_TOP_MENU;
      case 227: return KEYCODE_11;
      case 228: return KEYCODE_12;
      case 229: return KEYCODE_LAST_CHANNEL;
      case 230: return KEYCODE_TV_DATA_SERVICE;
      case 231: return KEYCODE_VOICE_ASSIST;
      case 232: return KEYCODE_TV_RADIO_SERVICE;
      case 233: return KEYCODE_TV_TELETEXT;
      case 234: return KEYCODE_TV_NUMBER_ENTRY;
      case 235: return KEYCODE_TV_TERRESTRIAL_ANALOG;
      case 236: return KEYCODE_TV_TERRESTRIAL_DIGITAL;
      case 237: return KEYCODE_TV_SATELLITE;
      case 238: return KEYCODE_TV_SATELLITE_BS;
      case 239: return KEYCODE_TV_SATELLITE_CS;
      case 240: return KEYCODE_TV_SATELLITE_SERVICE;
      case 241: return KEYCODE_TV_NETWORK;
      case 242: return KEYCODE_TV_ANTENNA_CABLE;
      case 243: return KEYCODE_TV_INPUT_HDMI_1;
      case 244: return KEYCODE_TV_INPUT_HDMI_2;
      case 245: return KEYCODE_TV_INPUT_HDMI_3;
      case 246: return KEYCODE_TV_INPUT_HDMI_4;
      case 247: return KEYCODE_TV_INPUT_COMPOSITE_1;
      case 248: return KEYCODE_TV_INPUT_COMPOSITE_2;
      case 249: return KEYCODE_TV_INPUT_COMPONENT_1;
      case 250: return KEYCODE_TV_INPUT_COMPONENT_2;
      case 251: return KEYCODE_TV_INPUT_VGA_1;
      case 252: return KEYCODE_TV_AUDIO_DESCRIPTION;
      case 253: return KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP;
      case 254: return KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN;
      case 255: return KEYCODE_TV_ZOOM_MODE;
      case 256: return KEYCODE_TV_CONTENTS_MENU;
      case 257: return KEYCODE_TV_MEDIA_CONTEXT_MENU;
      case 258: return KEYCODE_TV_TIMER_PROGRAMMING;
      case 259: return KEYCODE_HELP;
      case 260: return KEYCODE_NAVIGATE_PREVIOUS;
      case 261: return KEYCODE_NAVIGATE_NEXT;
      case 262: return KEYCODE_NAVIGATE_IN;
      case 263: return KEYCODE_NAVIGATE_OUT;
      case 264: return KEYCODE_STEM_PRIMARY;
      case 265: return KEYCODE_STEM_1;
      case 266: return KEYCODE_STEM_2;
      case 267: return KEYCODE_STEM_3;
      case 268: return KEYCODE_DPAD_UP_LEFT;
      case 269: return KEYCODE_DPAD_DOWN_LEFT;
      case 270: return KEYCODE_DPAD_UP_RIGHT;
      case 271: return KEYCODE_DPAD_DOWN_RIGHT;
      case 272: return KEYCODE_MEDIA_SKIP_FORWARD;
      case 273: return KEYCODE_MEDIA_SKIP_BACKWARD;
      case 274: return KEYCODE_MEDIA_STEP_FORWARD;
      case 275: return KEYCODE_MEDIA_STEP_BACKWARD;
      case 276: return KEYCODE_SOFT_SLEEP;
      case 277: return KEYCODE_CUT;
      case 278: return KEYCODE_COPY;
      case 279: return KEYCODE_PASTE;
      case 280: return KEYCODE_SYSTEM_NAVIGATION_UP;
      case 281: return KEYCODE_SYSTEM_NAVIGATION_DOWN;
      case 282: return KEYCODE_SYSTEM_NAVIGATION_LEFT;
      case 283: return KEYCODE_SYSTEM_NAVIGATION_RIGHT;
      case 284: return KEYCODE_ALL_APPS;
      case 285: return KEYCODE_REFRESH;
      case 286: return KEYCODE_THUMBS_UP;
      case 287: return KEYCODE_THUMBS_DOWN;
      case 288: return KEYCODE_PROFILE_SWITCH;
      case 289: return KEYCODE_VIDEO_APP_1;
      case 290: return KEYCODE_VIDEO_APP_2;
      case 291: return KEYCODE_VIDEO_APP_3;
      case 292: return KEYCODE_VIDEO_APP_4;
      case 293: return KEYCODE_VIDEO_APP_5;
      case 294: return KEYCODE_VIDEO_APP_6;
      case 295: return KEYCODE_VIDEO_APP_7;
      case 296: return KEYCODE_VIDEO_APP_8;
      case 297: return KEYCODE_FEATURED_APP_1;
      case 298: return KEYCODE_FEATURED_APP_2;
      case 299: return KEYCODE_FEATURED_APP_3;
      case 300: return KEYCODE_FEATURED_APP_4;
      case 301: return KEYCODE_DEMO_APP_1;
      case 302: return KEYCODE_DEMO_APP_2;
      case 303: return KEYCODE_DEMO_APP_3;
      case 304: return KEYCODE_DEMO_APP_4;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RemoteKeyCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RemoteKeyCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RemoteKeyCode>() {
          @java.lang.Override
          public RemoteKeyCode findValueByNumber(int number) {
            return RemoteKeyCode.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return RemoteKeyCodeVerifier.INSTANCE;
  }

  private static final class RemoteKeyCodeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new RemoteKeyCodeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return RemoteKeyCode.forNumber(number) != null;
          }
        };

  private final int value;

  private RemoteKeyCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:remote.RemoteKeyCode)
}

