// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

@com.google.protobuf.Generated
public interface ConfigurationAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polo.wire.protobuf.ConfigurationAck)
    com.google.protobuf.MessageLiteOrBuilder {
}
