// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

@com.google.protobuf.Generated
public interface ConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polo.wire.protobuf.Configuration)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
   * @return Whether the encoding field is set.
   */
  boolean hasEncoding();
  /**
   * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
   * @return The encoding.
   */
  com.sprit.tvremote.proto.polo.Options.Encoding getEncoding();

  /**
   * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
   * @return Whether the clientRole field is set.
   */
  boolean hasClientRole();
  /**
   * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
   * @return The clientRole.
   */
  com.sprit.tvremote.proto.polo.Options.RoleType getClientRole();
}
