// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

/**
 * Protobuf type {@code polo.wire.protobuf.Configuration}
 */
@com.google.protobuf.Generated
public  final class Configuration extends
    com.google.protobuf.GeneratedMessageLite<
        Configuration, Configuration.Builder> implements
    // @@protoc_insertion_point(message_implements:polo.wire.protobuf.Configuration)
    ConfigurationOrBuilder {
  private Configuration() {
  }
  private int bitField0_;
  public static final int ENCODING_FIELD_NUMBER = 1;
  private com.sprit.tvremote.proto.polo.Options.Encoding encoding_;
  /**
   * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
   */
  @java.lang.Override
  public boolean hasEncoding() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.polo.Options.Encoding getEncoding() {
    return encoding_ == null ? com.sprit.tvremote.proto.polo.Options.Encoding.getDefaultInstance() : encoding_;
  }
  /**
   * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setEncoding(com.sprit.tvremote.proto.polo.Options.Encoding value) {
    value.getClass();  // minimal bytecode null check
    encoding_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeEncoding(com.sprit.tvremote.proto.polo.Options.Encoding value) {
    value.getClass();  // minimal bytecode null check
    if (encoding_ != null &&
        encoding_ != com.sprit.tvremote.proto.polo.Options.Encoding.getDefaultInstance()) {
      encoding_ =
        com.sprit.tvremote.proto.polo.Options.Encoding.newBuilder(encoding_).mergeFrom(value).buildPartial();
    } else {
      encoding_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
   */
  private void clearEncoding() {
    encoding_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int CLIENT_ROLE_FIELD_NUMBER = 2;
  private int clientRole_;
  /**
   * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
   * @return Whether the clientRole field is set.
   */
  @java.lang.Override
  public boolean hasClientRole() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
   * @return The clientRole.
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.polo.Options.RoleType getClientRole() {
    com.sprit.tvremote.proto.polo.Options.RoleType result = com.sprit.tvremote.proto.polo.Options.RoleType.forNumber(clientRole_);
    return result == null ? com.sprit.tvremote.proto.polo.Options.RoleType.ROLE_TYPE_UNKNOWN : result;
  }
  /**
   * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
   * @param value The clientRole to set.
   */
  private void setClientRole(com.sprit.tvremote.proto.polo.Options.RoleType value) {
    clientRole_ = value.getNumber();
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
   */
  private void clearClientRole() {
    bitField0_ = (bitField0_ & ~0x00000002);
    clientRole_ = 0;
  }

  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.polo.Configuration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.polo.Configuration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.polo.Configuration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.polo.Configuration prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code polo.wire.protobuf.Configuration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.polo.Configuration, Builder> implements
      // @@protoc_insertion_point(builder_implements:polo.wire.protobuf.Configuration)
      com.sprit.tvremote.proto.polo.ConfigurationOrBuilder {
    // Construct using com.sprit.tvremote.proto.polo.Configuration.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
     */
    @java.lang.Override
    public boolean hasEncoding() {
      return instance.hasEncoding();
    }
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.polo.Options.Encoding getEncoding() {
      return instance.getEncoding();
    }
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
     */
    public Builder setEncoding(com.sprit.tvremote.proto.polo.Options.Encoding value) {
      copyOnWrite();
      instance.setEncoding(value);
      return this;
      }
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
     */
    public Builder setEncoding(
        com.sprit.tvremote.proto.polo.Options.Encoding.Builder builderForValue) {
      copyOnWrite();
      instance.setEncoding(builderForValue.build());
      return this;
    }
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
     */
    public Builder mergeEncoding(com.sprit.tvremote.proto.polo.Options.Encoding value) {
      copyOnWrite();
      instance.mergeEncoding(value);
      return this;
    }
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding encoding = 1;</code>
     */
    public Builder clearEncoding() {  copyOnWrite();
      instance.clearEncoding();
      return this;
    }

    /**
     * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
     * @return Whether the clientRole field is set.
     */
    @java.lang.Override
    public boolean hasClientRole() {
      return instance.hasClientRole();
    }
    /**
     * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
     * @return The clientRole.
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.polo.Options.RoleType getClientRole() {
      return instance.getClientRole();
    }
    /**
     * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
     * @param value The enum numeric value on the wire for clientRole to set.
     * @return This builder for chaining.
     */
    public Builder setClientRole(com.sprit.tvremote.proto.polo.Options.RoleType value) {
      copyOnWrite();
      instance.setClientRole(value);
      return this;
    }
    /**
     * <code>required .polo.wire.protobuf.Options.RoleType client_role = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientRole() {
      copyOnWrite();
      instance.clearClientRole();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:polo.wire.protobuf.Configuration)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.polo.Configuration();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "encoding_",
            "clientRole_",
            com.sprit.tvremote.proto.polo.Options.RoleType.internalGetVerifier(),
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u1509\u0000\u0002" +
              "\u1d0c\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.polo.Configuration> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.polo.Configuration.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.polo.Configuration>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:polo.wire.protobuf.Configuration)
  private static final com.sprit.tvremote.proto.polo.Configuration DEFAULT_INSTANCE;
  static {
    Configuration defaultInstance = new Configuration();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Configuration.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.polo.Configuration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Configuration> PARSER;

  public static com.google.protobuf.Parser<Configuration> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

