// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

/**
 * Protobuf type {@code polo.wire.protobuf.Options}
 */
@com.google.protobuf.Generated
public  final class Options extends
    com.google.protobuf.GeneratedMessageLite<
        Options, Options.Builder> implements
    // @@protoc_insertion_point(message_implements:polo.wire.protobuf.Options)
    OptionsOrBuilder {
  private Options() {
    inputEncodings_ = emptyProtobufList();
    outputEncodings_ = emptyProtobufList();
  }
  /**
   * Protobuf enum {@code polo.wire.protobuf.Options.RoleType}
   */
  public enum RoleType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ROLE_TYPE_UNKNOWN = 0;</code>
     */
    ROLE_TYPE_UNKNOWN(0),
    /**
     * <code>ROLE_TYPE_INPUT = 1;</code>
     */
    ROLE_TYPE_INPUT(1),
    /**
     * <code>ROLE_TYPE_OUTPUT = 2;</code>
     */
    ROLE_TYPE_OUTPUT(2),
    ;

    /**
     * <code>ROLE_TYPE_UNKNOWN = 0;</code>
     */
    public static final int ROLE_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <code>ROLE_TYPE_INPUT = 1;</code>
     */
    public static final int ROLE_TYPE_INPUT_VALUE = 1;
    /**
     * <code>ROLE_TYPE_OUTPUT = 2;</code>
     */
    public static final int ROLE_TYPE_OUTPUT_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RoleType valueOf(int value) {
      return forNumber(value);
    }

    public static RoleType forNumber(int value) {
      switch (value) {
        case 0: return ROLE_TYPE_UNKNOWN;
        case 1: return ROLE_TYPE_INPUT;
        case 2: return ROLE_TYPE_OUTPUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RoleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RoleType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoleType>() {
            @java.lang.Override
            public RoleType findValueByNumber(int number) {
              return RoleType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return RoleTypeVerifier.INSTANCE;
    }

    private static final class RoleTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new RoleTypeVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return RoleType.forNumber(number) != null;
            }
          };

    private final int value;

    private RoleType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:polo.wire.protobuf.Options.RoleType)
  }

  public interface EncodingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:polo.wire.protobuf.Options.Encoding)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
     * @return The type.
     */
    com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType getType();

    /**
     * <code>required uint32 symbol_length = 2;</code>
     * @return Whether the symbolLength field is set.
     */
    boolean hasSymbolLength();
    /**
     * <code>required uint32 symbol_length = 2;</code>
     * @return The symbolLength.
     */
    int getSymbolLength();
  }
  /**
   * Protobuf type {@code polo.wire.protobuf.Options.Encoding}
   */
  public  static final class Encoding extends
      com.google.protobuf.GeneratedMessageLite<
          Encoding, Encoding.Builder> implements
      // @@protoc_insertion_point(message_implements:polo.wire.protobuf.Options.Encoding)
      EncodingOrBuilder {
    private Encoding() {
    }
    /**
     * Protobuf enum {@code polo.wire.protobuf.Options.Encoding.EncodingType}
     */
    public enum EncodingType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>ENCODING_TYPE_UNKNOWN = 0;</code>
       */
      ENCODING_TYPE_UNKNOWN(0),
      /**
       * <code>ENCODING_TYPE_ALPHANUMERIC = 1;</code>
       */
      ENCODING_TYPE_ALPHANUMERIC(1),
      /**
       * <code>ENCODING_TYPE_NUMERIC = 2;</code>
       */
      ENCODING_TYPE_NUMERIC(2),
      /**
       * <code>ENCODING_TYPE_HEXADECIMAL = 3;</code>
       */
      ENCODING_TYPE_HEXADECIMAL(3),
      /**
       * <code>ENCODING_TYPE_QRCODE = 4;</code>
       */
      ENCODING_TYPE_QRCODE(4),
      ;

      /**
       * <code>ENCODING_TYPE_UNKNOWN = 0;</code>
       */
      public static final int ENCODING_TYPE_UNKNOWN_VALUE = 0;
      /**
       * <code>ENCODING_TYPE_ALPHANUMERIC = 1;</code>
       */
      public static final int ENCODING_TYPE_ALPHANUMERIC_VALUE = 1;
      /**
       * <code>ENCODING_TYPE_NUMERIC = 2;</code>
       */
      public static final int ENCODING_TYPE_NUMERIC_VALUE = 2;
      /**
       * <code>ENCODING_TYPE_HEXADECIMAL = 3;</code>
       */
      public static final int ENCODING_TYPE_HEXADECIMAL_VALUE = 3;
      /**
       * <code>ENCODING_TYPE_QRCODE = 4;</code>
       */
      public static final int ENCODING_TYPE_QRCODE_VALUE = 4;


      @java.lang.Override
      public final int getNumber() {
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EncodingType valueOf(int value) {
        return forNumber(value);
      }

      public static EncodingType forNumber(int value) {
        switch (value) {
          case 0: return ENCODING_TYPE_UNKNOWN;
          case 1: return ENCODING_TYPE_ALPHANUMERIC;
          case 2: return ENCODING_TYPE_NUMERIC;
          case 3: return ENCODING_TYPE_HEXADECIMAL;
          case 4: return ENCODING_TYPE_QRCODE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EncodingType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EncodingType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EncodingType>() {
              @java.lang.Override
              public EncodingType findValueByNumber(int number) {
                return EncodingType.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return EncodingTypeVerifier.INSTANCE;
      }

      private static final class EncodingTypeVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier
                  INSTANCE = new EncodingTypeVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return EncodingType.forNumber(number) != null;
              }
            };

      private final int value;

      private EncodingType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:polo.wire.protobuf.Options.Encoding.EncodingType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType getType() {
      com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType result = com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType.forNumber(type_);
      return result == null ? com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType.ENCODING_TYPE_UNKNOWN : result;
    }
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
     * @param value The type to set.
     */
    private void setType(com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType value) {
      type_ = value.getNumber();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
     */
    private void clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
    }

    public static final int SYMBOL_LENGTH_FIELD_NUMBER = 2;
    private int symbolLength_;
    /**
     * <code>required uint32 symbol_length = 2;</code>
     * @return Whether the symbolLength field is set.
     */
    @java.lang.Override
    public boolean hasSymbolLength() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required uint32 symbol_length = 2;</code>
     * @return The symbolLength.
     */
    @java.lang.Override
    public int getSymbolLength() {
      return symbolLength_;
    }
    /**
     * <code>required uint32 symbol_length = 2;</code>
     * @param value The symbolLength to set.
     */
    private void setSymbolLength(int value) {
      bitField0_ |= 0x00000002;
      symbolLength_ = value;
    }
    /**
     * <code>required uint32 symbol_length = 2;</code>
     */
    private void clearSymbolLength() {
      bitField0_ = (bitField0_ & ~0x00000002);
      symbolLength_ = 0;
    }

    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static com.sprit.tvremote.proto.polo.Options.Encoding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static com.sprit.tvremote.proto.polo.Options.Encoding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.sprit.tvremote.proto.polo.Options.Encoding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.sprit.tvremote.proto.polo.Options.Encoding prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code polo.wire.protobuf.Options.Encoding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.sprit.tvremote.proto.polo.Options.Encoding, Builder> implements
        // @@protoc_insertion_point(builder_implements:polo.wire.protobuf.Options.Encoding)
        com.sprit.tvremote.proto.polo.Options.EncodingOrBuilder {
      // Construct using com.sprit.tvremote.proto.polo.Options.Encoding.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override
      public boolean hasType() {
        return instance.hasType();
      }
      /**
       * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType getType() {
        return instance.getType();
      }
      /**
       * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>required .polo.wire.protobuf.Options.Encoding.EncodingType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <code>required uint32 symbol_length = 2;</code>
       * @return Whether the symbolLength field is set.
       */
      @java.lang.Override
      public boolean hasSymbolLength() {
        return instance.hasSymbolLength();
      }
      /**
       * <code>required uint32 symbol_length = 2;</code>
       * @return The symbolLength.
       */
      @java.lang.Override
      public int getSymbolLength() {
        return instance.getSymbolLength();
      }
      /**
       * <code>required uint32 symbol_length = 2;</code>
       * @param value The symbolLength to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolLength(int value) {
        copyOnWrite();
        instance.setSymbolLength(value);
        return this;
      }
      /**
       * <code>required uint32 symbol_length = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbolLength() {
        copyOnWrite();
        instance.clearSymbolLength();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:polo.wire.protobuf.Options.Encoding)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.sprit.tvremote.proto.polo.Options.Encoding();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "type_",
              com.sprit.tvremote.proto.polo.Options.Encoding.EncodingType.internalGetVerifier(),
              "symbolLength_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u1d0c\u0000\u0002" +
                "\u150b\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.sprit.tvremote.proto.polo.Options.Encoding> parser = PARSER;
          if (parser == null) {
            synchronized (com.sprit.tvremote.proto.polo.Options.Encoding.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.sprit.tvremote.proto.polo.Options.Encoding>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return memoizedIsInitialized;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
          return null;
        }
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:polo.wire.protobuf.Options.Encoding)
    private static final com.sprit.tvremote.proto.polo.Options.Encoding DEFAULT_INSTANCE;
    static {
      Encoding defaultInstance = new Encoding();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Encoding.class, defaultInstance);
    }

    public static com.sprit.tvremote.proto.polo.Options.Encoding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Encoding> PARSER;

    public static com.google.protobuf.Parser<Encoding> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  private int bitField0_;
  public static final int INPUT_ENCODINGS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.sprit.tvremote.proto.polo.Options.Encoding> inputEncodings_;
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.sprit.tvremote.proto.polo.Options.Encoding> getInputEncodingsList() {
    return inputEncodings_;
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  public java.util.List<? extends com.sprit.tvremote.proto.polo.Options.EncodingOrBuilder> 
      getInputEncodingsOrBuilderList() {
    return inputEncodings_;
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  @java.lang.Override
  public int getInputEncodingsCount() {
    return inputEncodings_.size();
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.polo.Options.Encoding getInputEncodings(int index) {
    return inputEncodings_.get(index);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  public com.sprit.tvremote.proto.polo.Options.EncodingOrBuilder getInputEncodingsOrBuilder(
      int index) {
    return inputEncodings_.get(index);
  }
  private void ensureInputEncodingsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.sprit.tvremote.proto.polo.Options.Encoding> tmp = inputEncodings_;
    if (!tmp.isModifiable()) {
      inputEncodings_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setInputEncodings(
      int index, com.sprit.tvremote.proto.polo.Options.Encoding value) {
    value.getClass();  // minimal bytecode null check
    ensureInputEncodingsIsMutable();
    inputEncodings_.set(index, value);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addInputEncodings(com.sprit.tvremote.proto.polo.Options.Encoding value) {
    value.getClass();  // minimal bytecode null check
    ensureInputEncodingsIsMutable();
    inputEncodings_.add(value);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addInputEncodings(
      int index, com.sprit.tvremote.proto.polo.Options.Encoding value) {
    value.getClass();  // minimal bytecode null check
    ensureInputEncodingsIsMutable();
    inputEncodings_.add(index, value);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  private void addAllInputEncodings(
      java.lang.Iterable<? extends com.sprit.tvremote.proto.polo.Options.Encoding> values) {
    ensureInputEncodingsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, inputEncodings_);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  private void clearInputEncodings() {
    inputEncodings_ = emptyProtobufList();
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  private void removeInputEncodings(int index) {
    ensureInputEncodingsIsMutable();
    inputEncodings_.remove(index);
  }

  public static final int OUTPUT_ENCODINGS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.sprit.tvremote.proto.polo.Options.Encoding> outputEncodings_;
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.sprit.tvremote.proto.polo.Options.Encoding> getOutputEncodingsList() {
    return outputEncodings_;
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  public java.util.List<? extends com.sprit.tvremote.proto.polo.Options.EncodingOrBuilder> 
      getOutputEncodingsOrBuilderList() {
    return outputEncodings_;
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  @java.lang.Override
  public int getOutputEncodingsCount() {
    return outputEncodings_.size();
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.polo.Options.Encoding getOutputEncodings(int index) {
    return outputEncodings_.get(index);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  public com.sprit.tvremote.proto.polo.Options.EncodingOrBuilder getOutputEncodingsOrBuilder(
      int index) {
    return outputEncodings_.get(index);
  }
  private void ensureOutputEncodingsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.sprit.tvremote.proto.polo.Options.Encoding> tmp = outputEncodings_;
    if (!tmp.isModifiable()) {
      outputEncodings_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setOutputEncodings(
      int index, com.sprit.tvremote.proto.polo.Options.Encoding value) {
    value.getClass();  // minimal bytecode null check
    ensureOutputEncodingsIsMutable();
    outputEncodings_.set(index, value);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addOutputEncodings(com.sprit.tvremote.proto.polo.Options.Encoding value) {
    value.getClass();  // minimal bytecode null check
    ensureOutputEncodingsIsMutable();
    outputEncodings_.add(value);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addOutputEncodings(
      int index, com.sprit.tvremote.proto.polo.Options.Encoding value) {
    value.getClass();  // minimal bytecode null check
    ensureOutputEncodingsIsMutable();
    outputEncodings_.add(index, value);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  private void addAllOutputEncodings(
      java.lang.Iterable<? extends com.sprit.tvremote.proto.polo.Options.Encoding> values) {
    ensureOutputEncodingsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, outputEncodings_);
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  private void clearOutputEncodings() {
    outputEncodings_ = emptyProtobufList();
  }
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  private void removeOutputEncodings(int index) {
    ensureOutputEncodingsIsMutable();
    outputEncodings_.remove(index);
  }

  public static final int PREFERRED_ROLE_FIELD_NUMBER = 3;
  private int preferredRole_;
  /**
   * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
   * @return Whether the preferredRole field is set.
   */
  @java.lang.Override
  public boolean hasPreferredRole() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
   * @return The preferredRole.
   */
  @java.lang.Override
  public com.sprit.tvremote.proto.polo.Options.RoleType getPreferredRole() {
    com.sprit.tvremote.proto.polo.Options.RoleType result = com.sprit.tvremote.proto.polo.Options.RoleType.forNumber(preferredRole_);
    return result == null ? com.sprit.tvremote.proto.polo.Options.RoleType.ROLE_TYPE_UNKNOWN : result;
  }
  /**
   * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
   * @param value The preferredRole to set.
   */
  private void setPreferredRole(com.sprit.tvremote.proto.polo.Options.RoleType value) {
    preferredRole_ = value.getNumber();
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
   */
  private void clearPreferredRole() {
    bitField0_ = (bitField0_ & ~0x00000001);
    preferredRole_ = 0;
  }

  public static com.sprit.tvremote.proto.polo.Options parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.polo.Options parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.polo.Options parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.polo.Options parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.polo.Options prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code polo.wire.protobuf.Options}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.polo.Options, Builder> implements
      // @@protoc_insertion_point(builder_implements:polo.wire.protobuf.Options)
      com.sprit.tvremote.proto.polo.OptionsOrBuilder {
    // Construct using com.sprit.tvremote.proto.polo.Options.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.sprit.tvremote.proto.polo.Options.Encoding> getInputEncodingsList() {
      return java.util.Collections.unmodifiableList(
          instance.getInputEncodingsList());
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    @java.lang.Override
    public int getInputEncodingsCount() {
      return instance.getInputEncodingsCount();
    }/**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.polo.Options.Encoding getInputEncodings(int index) {
      return instance.getInputEncodings(index);
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder setInputEncodings(
        int index, com.sprit.tvremote.proto.polo.Options.Encoding value) {
      copyOnWrite();
      instance.setInputEncodings(index, value);
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder setInputEncodings(
        int index, com.sprit.tvremote.proto.polo.Options.Encoding.Builder builderForValue) {
      copyOnWrite();
      instance.setInputEncodings(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder addInputEncodings(com.sprit.tvremote.proto.polo.Options.Encoding value) {
      copyOnWrite();
      instance.addInputEncodings(value);
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder addInputEncodings(
        int index, com.sprit.tvremote.proto.polo.Options.Encoding value) {
      copyOnWrite();
      instance.addInputEncodings(index, value);
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder addInputEncodings(
        com.sprit.tvremote.proto.polo.Options.Encoding.Builder builderForValue) {
      copyOnWrite();
      instance.addInputEncodings(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder addInputEncodings(
        int index, com.sprit.tvremote.proto.polo.Options.Encoding.Builder builderForValue) {
      copyOnWrite();
      instance.addInputEncodings(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder addAllInputEncodings(
        java.lang.Iterable<? extends com.sprit.tvremote.proto.polo.Options.Encoding> values) {
      copyOnWrite();
      instance.addAllInputEncodings(values);
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder clearInputEncodings() {
      copyOnWrite();
      instance.clearInputEncodings();
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
     */
    public Builder removeInputEncodings(int index) {
      copyOnWrite();
      instance.removeInputEncodings(index);
      return this;
    }

    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.sprit.tvremote.proto.polo.Options.Encoding> getOutputEncodingsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOutputEncodingsList());
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    @java.lang.Override
    public int getOutputEncodingsCount() {
      return instance.getOutputEncodingsCount();
    }/**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.polo.Options.Encoding getOutputEncodings(int index) {
      return instance.getOutputEncodings(index);
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder setOutputEncodings(
        int index, com.sprit.tvremote.proto.polo.Options.Encoding value) {
      copyOnWrite();
      instance.setOutputEncodings(index, value);
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder setOutputEncodings(
        int index, com.sprit.tvremote.proto.polo.Options.Encoding.Builder builderForValue) {
      copyOnWrite();
      instance.setOutputEncodings(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder addOutputEncodings(com.sprit.tvremote.proto.polo.Options.Encoding value) {
      copyOnWrite();
      instance.addOutputEncodings(value);
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder addOutputEncodings(
        int index, com.sprit.tvremote.proto.polo.Options.Encoding value) {
      copyOnWrite();
      instance.addOutputEncodings(index, value);
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder addOutputEncodings(
        com.sprit.tvremote.proto.polo.Options.Encoding.Builder builderForValue) {
      copyOnWrite();
      instance.addOutputEncodings(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder addOutputEncodings(
        int index, com.sprit.tvremote.proto.polo.Options.Encoding.Builder builderForValue) {
      copyOnWrite();
      instance.addOutputEncodings(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder addAllOutputEncodings(
        java.lang.Iterable<? extends com.sprit.tvremote.proto.polo.Options.Encoding> values) {
      copyOnWrite();
      instance.addAllOutputEncodings(values);
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder clearOutputEncodings() {
      copyOnWrite();
      instance.clearOutputEncodings();
      return this;
    }
    /**
     * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
     */
    public Builder removeOutputEncodings(int index) {
      copyOnWrite();
      instance.removeOutputEncodings(index);
      return this;
    }

    /**
     * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
     * @return Whether the preferredRole field is set.
     */
    @java.lang.Override
    public boolean hasPreferredRole() {
      return instance.hasPreferredRole();
    }
    /**
     * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
     * @return The preferredRole.
     */
    @java.lang.Override
    public com.sprit.tvremote.proto.polo.Options.RoleType getPreferredRole() {
      return instance.getPreferredRole();
    }
    /**
     * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
     * @param value The enum numeric value on the wire for preferredRole to set.
     * @return This builder for chaining.
     */
    public Builder setPreferredRole(com.sprit.tvremote.proto.polo.Options.RoleType value) {
      copyOnWrite();
      instance.setPreferredRole(value);
      return this;
    }
    /**
     * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreferredRole() {
      copyOnWrite();
      instance.clearPreferredRole();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:polo.wire.protobuf.Options)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.polo.Options();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "inputEncodings_",
            com.sprit.tvremote.proto.polo.Options.Encoding.class,
            "outputEncodings_",
            com.sprit.tvremote.proto.polo.Options.Encoding.class,
            "preferredRole_",
            com.sprit.tvremote.proto.polo.Options.RoleType.internalGetVerifier(),
          };
          java.lang.String info =
              "\u0001\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0002\u0002\u0001\u041b\u0002\u041b" +
              "\u0003\u180c\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.polo.Options> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.polo.Options.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.polo.Options>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:polo.wire.protobuf.Options)
  private static final com.sprit.tvremote.proto.polo.Options DEFAULT_INSTANCE;
  static {
    Options defaultInstance = new Options();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Options.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.polo.Options getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Options> PARSER;

  public static com.google.protobuf.Parser<Options> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

