// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

@com.google.protobuf.Generated
public interface OptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polo.wire.protobuf.Options)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  java.util.List<com.sprit.tvremote.proto.polo.Options.Encoding> 
      getInputEncodingsList();
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  com.sprit.tvremote.proto.polo.Options.Encoding getInputEncodings(int index);
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding input_encodings = 1;</code>
   */
  int getInputEncodingsCount();

  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  java.util.List<com.sprit.tvremote.proto.polo.Options.Encoding> 
      getOutputEncodingsList();
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  com.sprit.tvremote.proto.polo.Options.Encoding getOutputEncodings(int index);
  /**
   * <code>repeated .polo.wire.protobuf.Options.Encoding output_encodings = 2;</code>
   */
  int getOutputEncodingsCount();

  /**
   * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
   * @return Whether the preferredRole field is set.
   */
  boolean hasPreferredRole();
  /**
   * <code>optional .polo.wire.protobuf.Options.RoleType preferred_role = 3;</code>
   * @return The preferredRole.
   */
  com.sprit.tvremote.proto.polo.Options.RoleType getPreferredRole();
}
