// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

@com.google.protobuf.Generated
public interface OuterMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polo.wire.protobuf.OuterMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required uint32 protocol_version = 1;</code>
   * @return Whether the protocolVersion field is set.
   */
  boolean hasProtocolVersion();
  /**
   * <code>required uint32 protocol_version = 1;</code>
   * @return The protocolVersion.
   */
  int getProtocolVersion();

  /**
   * <code>required .polo.wire.protobuf.OuterMessage.Status status = 2;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>required .polo.wire.protobuf.OuterMessage.Status status = 2;</code>
   * @return The status.
   */
  com.sprit.tvremote.proto.polo.OuterMessage.Status getStatus();

  /**
   * <code>optional .polo.wire.protobuf.PairingRequest pairing_request = 10;</code>
   * @return Whether the pairingRequest field is set.
   */
  boolean hasPairingRequest();
  /**
   * <code>optional .polo.wire.protobuf.PairingRequest pairing_request = 10;</code>
   * @return The pairingRequest.
   */
  com.sprit.tvremote.proto.polo.PairingRequest getPairingRequest();

  /**
   * <code>optional .polo.wire.protobuf.PairingRequestAck pairing_request_ack = 11;</code>
   * @return Whether the pairingRequestAck field is set.
   */
  boolean hasPairingRequestAck();
  /**
   * <code>optional .polo.wire.protobuf.PairingRequestAck pairing_request_ack = 11;</code>
   * @return The pairingRequestAck.
   */
  com.sprit.tvremote.proto.polo.PairingRequestAck getPairingRequestAck();

  /**
   * <code>optional .polo.wire.protobuf.Options options = 20;</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>optional .polo.wire.protobuf.Options options = 20;</code>
   * @return The options.
   */
  com.sprit.tvremote.proto.polo.Options getOptions();

  /**
   * <code>optional .polo.wire.protobuf.Configuration configuration = 30;</code>
   * @return Whether the configuration field is set.
   */
  boolean hasConfiguration();
  /**
   * <code>optional .polo.wire.protobuf.Configuration configuration = 30;</code>
   * @return The configuration.
   */
  com.sprit.tvremote.proto.polo.Configuration getConfiguration();

  /**
   * <code>optional .polo.wire.protobuf.ConfigurationAck configuration_ack = 31;</code>
   * @return Whether the configurationAck field is set.
   */
  boolean hasConfigurationAck();
  /**
   * <code>optional .polo.wire.protobuf.ConfigurationAck configuration_ack = 31;</code>
   * @return The configurationAck.
   */
  com.sprit.tvremote.proto.polo.ConfigurationAck getConfigurationAck();

  /**
   * <code>optional .polo.wire.protobuf.Secret secret = 40;</code>
   * @return Whether the secret field is set.
   */
  boolean hasSecret();
  /**
   * <code>optional .polo.wire.protobuf.Secret secret = 40;</code>
   * @return The secret.
   */
  com.sprit.tvremote.proto.polo.Secret getSecret();

  /**
   * <code>optional .polo.wire.protobuf.SecretAck secret_ack = 41;</code>
   * @return Whether the secretAck field is set.
   */
  boolean hasSecretAck();
  /**
   * <code>optional .polo.wire.protobuf.SecretAck secret_ack = 41;</code>
   * @return The secretAck.
   */
  com.sprit.tvremote.proto.polo.SecretAck getSecretAck();
}
