// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

/**
 * Protobuf type {@code polo.wire.protobuf.PairingRequest}
 */
@com.google.protobuf.Generated
public  final class PairingRequest extends
    com.google.protobuf.GeneratedMessageLite<
        PairingRequest, PairingRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:polo.wire.protobuf.PairingRequest)
    PairingRequestOrBuilder {
  private PairingRequest() {
    serviceName_ = "";
    clientName_ = "";
  }
  private int bitField0_;
  public static final int SERVICE_NAME_FIELD_NUMBER = 1;
  private java.lang.String serviceName_;
  /**
   * <code>required string service_name = 1;</code>
   * @return Whether the serviceName field is set.
   */
  @java.lang.Override
  public boolean hasServiceName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string service_name = 1;</code>
   * @return The serviceName.
   */
  @java.lang.Override
  public java.lang.String getServiceName() {
    return serviceName_;
  }
  /**
   * <code>required string service_name = 1;</code>
   * @return The bytes for serviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serviceName_);
  }
  /**
   * <code>required string service_name = 1;</code>
   * @param value The serviceName to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setServiceName(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000001;
    serviceName_ = value;
  }
  /**
   * <code>required string service_name = 1;</code>
   */
  private void clearServiceName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    serviceName_ = getDefaultInstance().getServiceName();
  }
  /**
   * <code>required string service_name = 1;</code>
   * @param value The bytes for serviceName to set.
   */
  private void setServiceNameBytes(
      com.google.protobuf.ByteString value) {
    serviceName_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int CLIENT_NAME_FIELD_NUMBER = 2;
  private java.lang.String clientName_;
  /**
   * <code>optional string client_name = 2;</code>
   * @return Whether the clientName field is set.
   */
  @java.lang.Override
  public boolean hasClientName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string client_name = 2;</code>
   * @return The clientName.
   */
  @java.lang.Override
  public java.lang.String getClientName() {
    return clientName_;
  }
  /**
   * <code>optional string client_name = 2;</code>
   * @return The bytes for clientName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientName_);
  }
  /**
   * <code>optional string client_name = 2;</code>
   * @param value The clientName to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setClientName(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000002;
    clientName_ = value;
  }
  /**
   * <code>optional string client_name = 2;</code>
   */
  private void clearClientName() {
    bitField0_ = (bitField0_ & ~0x00000002);
    clientName_ = getDefaultInstance().getClientName();
  }
  /**
   * <code>optional string client_name = 2;</code>
   * @param value The bytes for clientName to set.
   */
  private void setClientNameBytes(
      com.google.protobuf.ByteString value) {
    clientName_ = value.toStringUtf8();
    bitField0_ |= 0x00000002;
  }

  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.polo.PairingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.polo.PairingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.polo.PairingRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code polo.wire.protobuf.PairingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.polo.PairingRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:polo.wire.protobuf.PairingRequest)
      com.sprit.tvremote.proto.polo.PairingRequestOrBuilder {
    // Construct using com.sprit.tvremote.proto.polo.PairingRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>required string service_name = 1;</code>
     * @return Whether the serviceName field is set.
     */
    @java.lang.Override
    public boolean hasServiceName() {
      return instance.hasServiceName();
    }
    /**
     * <code>required string service_name = 1;</code>
     * @return The serviceName.
     */
    @java.lang.Override
    public java.lang.String getServiceName() {
      return instance.getServiceName();
    }
    /**
     * <code>required string service_name = 1;</code>
     * @return The bytes for serviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      return instance.getServiceNameBytes();
    }
    /**
     * <code>required string service_name = 1;</code>
     * @param value The serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceName(
        java.lang.String value) {
      copyOnWrite();
      instance.setServiceName(value);
      return this;
    }
    /**
     * <code>required string service_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceName() {
      copyOnWrite();
      instance.clearServiceName();
      return this;
    }
    /**
     * <code>required string service_name = 1;</code>
     * @param value The bytes for serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServiceNameBytes(value);
      return this;
    }

    /**
     * <code>optional string client_name = 2;</code>
     * @return Whether the clientName field is set.
     */
    @java.lang.Override
    public boolean hasClientName() {
      return instance.hasClientName();
    }
    /**
     * <code>optional string client_name = 2;</code>
     * @return The clientName.
     */
    @java.lang.Override
    public java.lang.String getClientName() {
      return instance.getClientName();
    }
    /**
     * <code>optional string client_name = 2;</code>
     * @return The bytes for clientName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientNameBytes() {
      return instance.getClientNameBytes();
    }
    /**
     * <code>optional string client_name = 2;</code>
     * @param value The clientName to set.
     * @return This builder for chaining.
     */
    public Builder setClientName(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientName(value);
      return this;
    }
    /**
     * <code>optional string client_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientName() {
      copyOnWrite();
      instance.clearClientName();
      return this;
    }
    /**
     * <code>optional string client_name = 2;</code>
     * @param value The bytes for clientName to set.
     * @return This builder for chaining.
     */
    public Builder setClientNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:polo.wire.protobuf.PairingRequest)
  }
  private byte memoizedIsInitialized = 2;
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.polo.PairingRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "serviceName_",
            "clientName_",
          };
          java.lang.String info =
              "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0001\u0001\u1508\u0000\u0002" +
              "\u1008\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.polo.PairingRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.polo.PairingRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.polo.PairingRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:polo.wire.protobuf.PairingRequest)
  private static final com.sprit.tvremote.proto.polo.PairingRequest DEFAULT_INSTANCE;
  static {
    PairingRequest defaultInstance = new PairingRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PairingRequest.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.polo.PairingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PairingRequest> PARSER;

  public static com.google.protobuf.Parser<PairingRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

