// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

@com.google.protobuf.Generated
public interface PairingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polo.wire.protobuf.PairingRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required string service_name = 1;</code>
   * @return Whether the serviceName field is set.
   */
  boolean hasServiceName();
  /**
   * <code>required string service_name = 1;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>required string service_name = 1;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>optional string client_name = 2;</code>
   * @return Whether the clientName field is set.
   */
  boolean hasClientName();
  /**
   * <code>optional string client_name = 2;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>optional string client_name = 2;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();
}
