// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

/**
 * Protobuf type {@code polo.wire.protobuf.PairingRequestAck}
 */
@com.google.protobuf.Generated
public  final class PairingRequestAck extends
    com.google.protobuf.GeneratedMessageLite<
        PairingRequestAck, PairingRequestAck.Builder> implements
    // @@protoc_insertion_point(message_implements:polo.wire.protobuf.PairingRequestAck)
    PairingRequestAckOrBuilder {
  private PairingRequestAck() {
    serverName_ = "";
  }
  private int bitField0_;
  public static final int SERVER_NAME_FIELD_NUMBER = 1;
  private java.lang.String serverName_;
  /**
   * <code>optional string server_name = 1;</code>
   * @return Whether the serverName field is set.
   */
  @java.lang.Override
  public boolean hasServerName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string server_name = 1;</code>
   * @return The serverName.
   */
  @java.lang.Override
  public java.lang.String getServerName() {
    return serverName_;
  }
  /**
   * <code>optional string server_name = 1;</code>
   * @return The bytes for serverName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serverName_);
  }
  /**
   * <code>optional string server_name = 1;</code>
   * @param value The serverName to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setServerName(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000001;
    serverName_ = value;
  }
  /**
   * <code>optional string server_name = 1;</code>
   */
  private void clearServerName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    serverName_ = getDefaultInstance().getServerName();
  }
  /**
   * <code>optional string server_name = 1;</code>
   * @param value The bytes for serverName to set.
   */
  private void setServerNameBytes(
      com.google.protobuf.ByteString value) {
    serverName_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.sprit.tvremote.proto.polo.PairingRequestAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.sprit.tvremote.proto.polo.PairingRequestAck prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code polo.wire.protobuf.PairingRequestAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.sprit.tvremote.proto.polo.PairingRequestAck, Builder> implements
      // @@protoc_insertion_point(builder_implements:polo.wire.protobuf.PairingRequestAck)
      com.sprit.tvremote.proto.polo.PairingRequestAckOrBuilder {
    // Construct using com.sprit.tvremote.proto.polo.PairingRequestAck.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string server_name = 1;</code>
     * @return Whether the serverName field is set.
     */
    @java.lang.Override
    public boolean hasServerName() {
      return instance.hasServerName();
    }
    /**
     * <code>optional string server_name = 1;</code>
     * @return The serverName.
     */
    @java.lang.Override
    public java.lang.String getServerName() {
      return instance.getServerName();
    }
    /**
     * <code>optional string server_name = 1;</code>
     * @return The bytes for serverName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      return instance.getServerNameBytes();
    }
    /**
     * <code>optional string server_name = 1;</code>
     * @param value The serverName to set.
     * @return This builder for chaining.
     */
    public Builder setServerName(
        java.lang.String value) {
      copyOnWrite();
      instance.setServerName(value);
      return this;
    }
    /**
     * <code>optional string server_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerName() {
      copyOnWrite();
      instance.clearServerName();
      return this;
    }
    /**
     * <code>optional string server_name = 1;</code>
     * @param value The bytes for serverName to set.
     * @return This builder for chaining.
     */
    public Builder setServerNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServerNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:polo.wire.protobuf.PairingRequestAck)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.sprit.tvremote.proto.polo.PairingRequestAck();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "serverName_",
          };
          java.lang.String info =
              "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1008\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.sprit.tvremote.proto.polo.PairingRequestAck> parser = PARSER;
        if (parser == null) {
          synchronized (com.sprit.tvremote.proto.polo.PairingRequestAck.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.sprit.tvremote.proto.polo.PairingRequestAck>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:polo.wire.protobuf.PairingRequestAck)
  private static final com.sprit.tvremote.proto.polo.PairingRequestAck DEFAULT_INSTANCE;
  static {
    PairingRequestAck defaultInstance = new PairingRequestAck();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PairingRequestAck.class, defaultInstance);
  }

  public static com.sprit.tvremote.proto.polo.PairingRequestAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PairingRequestAck> PARSER;

  public static com.google.protobuf.Parser<PairingRequestAck> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

