// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

@com.google.protobuf.Generated
public interface PairingRequestAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polo.wire.protobuf.PairingRequestAck)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string server_name = 1;</code>
   * @return Whether the serverName field is set.
   */
  boolean hasServerName();
  /**
   * <code>optional string server_name = 1;</code>
   * @return The serverName.
   */
  java.lang.String getServerName();
  /**
   * <code>optional string server_name = 1;</code>
   * @return The bytes for serverName.
   */
  com.google.protobuf.ByteString
      getServerNameBytes();
}
