// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: polo.proto
// Protobuf Java Version: 4.35.1

package com.sprit.tvremote.proto.polo;

@com.google.protobuf.Generated
public interface SecretOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polo.wire.protobuf.Secret)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required bytes secret = 1;</code>
   * @return Whether the secret field is set.
   */
  boolean hasSecret();
  /**
   * <code>required bytes secret = 1;</code>
   * @return The secret.
   */
  com.google.protobuf.ByteString getSecret();
}
